### ISSUE TITLE
meld 3.21.0 segfault in libgdk-3-0.dll

### ISSUE THREAD

**Issue by sdbbs** [msys2/MINGW-packages#10540]
I try to keep my MSYS2 install updated, am on Windows 10.

I've noticed a somewhat strange crash with meld:

* Start `meld` from MINGW64 terminal
* On "New comparison" (start) screen, click "File", then "Blank comparison"
* In the new comparison window, click on either side to focus it, and press <kbd>ENTER</kbd>
* Program crashes/segfaults.

This is what I could get from `gdb`:

```none
$ meld --version

(meld:8344): Gdk-CRITICAL **: 21:36:32.200: load_layout_dll: assertion 'dll != NULL' failed
meld 3.21.0

$ gdb --args python3 `which meld`
GNU gdb (GDB) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) r
Starting program: C:\msys64\mingw64\bin\python3.exe C:/msys64/mingw64/bin/meld
[New Thread 2024.0x49a4]
[New Thread 2024.0x32ec]
[New Thread 2024.0x3a80]
[New Thread 2024.0xf48]

(meld:2024): Gdk-CRITICAL **: 21:26:44.245: load_layout_dll: assertion 'dll != NULL' failed
[New Thread 2024.0x4910]
[New Thread 2024.0x4a80]
[New Thread 2024.0x37e4]
...
[Thread 2024.0x2e40 exited with code 0]
[Thread 2024.0x408c exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fffa02d2a0c in ?? () from C:\msys64\mingw64\bin\libgdk-3-0.dll
(gdb) bt
#0  0x00007fffa02d2a0c in ?? () from C:\msys64\mingw64\bin\libgdk-3-0.dll
#1  0x00007fff746c32aa in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#2  0x00007fff746c3353 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#3  0x00007fff746c3685 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#4  0x00007fff7485555f in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#5  0x00007fff748558f3 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#6  0x00007fff74582df1 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#7  0x00007fffbbca73b3 in ?? () from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
#8  0x00007fffbbcbe7e3 in ?? () from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
#9  0x00007fffbbcbf3a8 in ?? () from C:\msys64\mingw64\bin\libgobject-2.0-0.dll
#10 0x00007fff7482f905 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#11 0x00007fff746df991 in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#12 0x00007fff746e172b in ?? () from C:\msys64\mingw64\bin\libgtk-3-0.dll
#13 0x00007fffa028f5aa in ?? () from C:\msys64\mingw64\bin\libgdk-3-0.dll
#14 0x00007fffa02c911f in ?? () from C:\msys64\mingw64\bin\libgdk-3-0.dll
#15 0x00007fff7a998e84 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
#16 0x00007fff7a99bede in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
#17 0x00007fff7a99c201 in ?? () from C:\msys64\mingw64\bin\libglib-2.0-0.dll
#18 0x00007fff7835db7d in ?? () from C:\msys64\mingw64\bin\libgio-2.0-0.dll
#19 0x00007fffc3054851 in ?? () from C:\msys64\mingw64\bin\libffi-7.dll
#20 0x00007fffc305449b in ?? () from C:\msys64\mingw64\bin\libffi-7.dll
#21 0x00007fffc3054662 in ?? () from C:\msys64\mingw64\bin\libffi-7.dll
#22 0x00007fffbc38f36d in ?? () from C:\msys64\mingw64\lib\python3.9\site-packages\gi\_gi.cp39-mingw_x86_64.pyd
#23 0x00007fffbc39105f in ?? () from C:\msys64\mingw64\lib\python3.9\site-packages\gi\_gi.cp39-mingw_x86_64.pyd
#24 0x00007fff76a2aaa5 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#25 0x00007fff76aba70e in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#26 0x00007fff76ab711a in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#27 0x00007fff76a29da6 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#28 0x00007fff76ab816c in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
--Type <RET> for more, q to quit, c to continue without paging--
#29 0x00007fff76ab711a in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#30 0x00007fff76a29da6 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#31 0x00007fff76ab7f2f in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#32 0x00007fff76a29f9c in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#33 0x00007fff76a29d1b in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#34 0x00007fff76ab7f2f in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#35 0x00007fff76ab711a in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#36 0x00007fff769baeba in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#37 0x00007fff769badf4 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#38 0x00007fff769bad58 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#39 0x00007fff769cd874 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#40 0x00007fff769cd7f6 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#41 0x00007fff76adef76 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#42 0x00007fff769cdb12 in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#43 0x00007fff769d5c1e in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#44 0x00007fff769d57ac in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#45 0x00007ff63d5413d4 in ?? ()
#46 0x00007ff63d541506 in ?? ()
#47 0x00007fffe7927034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#48 0x00007fffe98c2651 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#49 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) quit
A debugging session is active.

        Inferior 1 [process 2024] will be killed.

Quit anyway? (y or n) y
```

**Comment by jeremyd2019** [comment]
That assertion looks an awful lot like what was fixed in #10532

**Comment by lazka** [comment]
repo is updated, try again now

**Comment by sdbbs** [comment]
Thanks @lazka:

> repo is updated with #10532 now, please try again

Indeed, just updated, the report is:

````none
$ grep 2022-01-13 /var/log/pacman.log | grep upgraded
[2022-01-13T10:26:41+0100] [ALPM] upgraded make (4.3-2 -> 4.3-3)
[2022-01-13T10:26:54+0100] [ALPM] upgraded mingw-w64-ucrt-x86_64-expat (2.4.1-1 -> 2.4.2-1)
[2022-01-13T10:26:59+0100] [ALPM] upgraded mingw-w64-ucrt-x86_64-gettext (0.21-1 -> 0.21-3)
[2022-01-13T10:26:59+0100] [ALPM] upgraded mingw-w64-ucrt-x86_64-harfbuzz (3.1.2-1 -> 3.2.0-1)
[2022-01-13T10:26:59+0100] [ALPM] upgraded mingw-w64-x86_64-SDL2 (2.0.18-2 -> 2.0.20-1)
[2022-01-13T10:26:59+0100] [ALPM] upgraded mingw-w64-x86_64-expat (2.4.1-1 -> 2.4.2-1)
[2022-01-13T10:27:05+0100] [ALPM] upgraded mingw-w64-x86_64-gettext (0.21-1 -> 0.21-3)
[2022-01-13T10:27:05+0100] [ALPM] upgraded mingw-w64-x86_64-asciidoc (10.0.2-1 -> 10.1.1-1)
[2022-01-13T10:27:06+0100] [ALPM] upgraded mingw-w64-x86_64-double-conversion (3.1.7-1 -> 3.2.0-1)
[2022-01-13T10:27:06+0100] [ALPM] upgraded mingw-w64-x86_64-doxygen (1.9.2-2 -> 1.9.3-1)
[2022-01-13T10:27:06+0100] [ALPM] upgraded mingw-w64-x86_64-harfbuzz (3.1.2-1 -> 3.2.0-1)
[2022-01-13T10:27:06+0100] [ALPM] upgraded mingw-w64-x86_64-gtk-update-icon-cache (3.24.31+44+g0e09bb75b5-1 -> 3.24.31+56+g7e9935e381-1)
[2022-01-13T10:27:09+0100] [ALPM] upgraded mingw-w64-x86_64-gtk3 (3.24.31+44+g0e09bb75b5-1 -> 3.24.31+56+g7e9935e381-1)
[2022-01-13T10:27:09+0100] [ALPM] upgraded mingw-w64-x86_64-nghttp2 (1.45.1-1 -> 1.46.0-1)
```

.... and no more crash when I press ENTER as described above! 😃 

Although I should probably report that there are some other messages appearing now, when I start from command line:

```none
$ meld

(meld:10188): Gdk-WARNING **: 10:34:39.578: Could not open registry key 'SYSTEM\CurrentControlSet\Control\Keyboard Layouts\D0010409'. Error code: 2

(meld:10188): Gdk-WARNING **: 10:34:39.578: Failed to load keyboard layout DLL for layout D0010409: (NULL)
```

.... however, everything runs, and the problem that this bug originally reported is gone - so I'll be closing this one...
