### ISSUE TITLE
Crash with `mesa` OpenGL on MINGW32

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#10876]
Octave crashes when rendering off-screen with the `opengl32.dll` installed with the mesa package.

Steps to reproduce in then MINGW32 environment. (Sorry, not really minimal. But I don't know enough about OpenGL to break this further down.)
```
$ pacman -S mingw-w64-i686-octave
[snip]
$ octave --eval "test getframe"
PASSES 2 out of 2 tests
$ pacman -S mingw-w64-i686-mesa
[snip]
$ octave --eval "test getframe"
C:\msys64\mingw32\bin\octave.exe: No error
Segmentation fault
```
It works correctly in the MINGW64 environment with or without `mesa` installed.

`gdb` backtrace in case this helps:
```
Markus@Markus-PC MINGW32 ~
$ gdb -r octave-gui
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from octave-gui...
Expanding full symbols from octave-gui...
(No debugging symbols found in octave-gui)
(gdb) r
Starting program: C:\msys64\mingw32\bin\octave-gui.exe
[New Thread 12976.0x5134]
[New Thread 12976.0x1904]
[New Thread 12976.0x3918]
[New Thread 12976.0x32d0]
[New Thread 12976.0x3d40]
[New Thread 12976.0x54b8]
[New Thread 12976.0x1d58]
[New Thread 12976.0x2b6c]
[New Thread 12976.0x4250]
[New Thread 12976.0x5144]
[New Thread 12976.0x2644]
[New Thread 12976.0xc30]
[New Thread 12976.0x6250]
[New Thread 12976.0x3ae8]
[New Thread 12976.0x1bb4]
[New Thread 12976.0x402c]
[New Thread 12976.0x5cac]
[New Thread 12976.0x4b14]
warning: onecore\net\netprofiles\service\src\nsp\dll\namespaceserviceprovider.cpp(550)\nlansp_c.dll!702C85D4: (caller: 76EBCD00) LogHr(1) tid(374c) 8007277C Der angegebene Dienst ist unbekannt. Der Dienst wurde nicht im angegebenen Namespace gefunden.
[New Thread 12976.0x3b74]
[New Thread 12976.0x1eec]
[New Thread 12976.0x2c0]
GNU Octave, version 6.4.0
Copyright (C) 2021 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "i686-w64-mingw32".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> test getframe
[New Thread 12976.0x5bf0]
[New Thread 12976.0x10f8]
[New Thread 12976.0xb08]
[New Thread 12976.0x543c]
[New Thread 12976.0x558c]
[New Thread 12976.0xe78]
[Thread 12976.0xe78 exited with code 0]
warning: NVD3DREL:
warning: GR-805 : DX9 Overlay is DISABLED
warning: NVD3DREL:
warning: GR-805 : DX9 Overlay is DISABLED
[New Thread 12976.0x3420]
[New Thread 12976.0x4214]
[New Thread 12976.0x52a8]
[New Thread 12976.0x4444]
[New Thread 12976.0x6010]
[New Thread 12976.0x2b88]
[New Thread 12976.0x2d40]
[New Thread 12976.0x3cc4]
[New Thread 12976.0x62b8]
[New Thread 12976.0x3a14]
[New Thread 12976.0x397c]
[New Thread 12976.0x396c]
[New Thread 12976.0x3e50]
[New Thread 12976.0x4310]
[New Thread 12976.0x2060]
[New Thread 12976.0x5688]
[New Thread 12976.0x5bd8]
[New Thread 12976.0x206c]
[New Thread 12976.0x3c5c]
[New Thread 12976.0x1d68]
[New Thread 12976.0x3144]
[New Thread 12976.0x1bbc]
[New Thread 12976.0x6200]
[New Thread 12976.0x118c]
[New Thread 12976.0x5c18]
[New Thread 12976.0x4cc4]
[New Thread 12976.0x3f8c]
[New Thread 12976.0x2c9c]
[New Thread 12976.0x386c]
[New Thread 12976.0x60a8]
[New Thread 12976.0x32a4]
[New Thread 12976.0x5008]
[New Thread 12976.0x2de8]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x5783d122 in QString::append(QString const&) () from C:\msys64\mingw32\bin\Qt5Core.dll
(gdb) bt
#0  0x5783d122 in QString::append(QString const&) () from C:\msys64\mingw32\bin\Qt5Core.dll
#1  0x50487d6a in QWindowsContext::createDummyWindow(QString const&, wchar_t const*, long ( stdcall*)(HWND__*, unsigned int, unsigned int, long), unsigned long) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#2  0x504cd7f5 in QWindowsGLContext::QWindowsGLContext(QOpenGLStaticContext*, QOpenGLContext*) ()
   from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#3  0x57afaa84 in QLinkedListData::shared_null () from C:\msys64\mingw32\bin\Qt5Core.dll
#4  0x00dfd3a8 in ?? ()
#5  0x1a981d60 in ?? ()
#6  0x50520e60 in QAccessibleInterface::interface_cast(QAccessible::InterfaceType) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#7  0x504d09d0 in QWindowsGLContext::QWindowsGLContext(QOpenGLStaticContext*, QOpenGLContext*) ()
   from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#8  0x5052fde0 in WindowCreationData::create(QWindow const*, QWindowsWindowData const&, QString) const ()
   from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#9  0x50522ea0 in QWindowsXpNativeFileDialog::~QWindowsXpNativeFileDialog() () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#10 0x5054cb48 in _fu5___ZTVN10__cxxabiv117__class_type_infoE () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#11 0x505176a8 in qt_addBitmapToPath(double, double, unsigned char const*, int, int, int, QPainterPath*) ()
   from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#12 0x505176c8 in QThread::event(QEvent*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#13 0x505176d0 in QThread::qt_metacast(char const*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#14 0x50521270 in QShGetFileInfoThread::~QShGetFileInfoThread() () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#15 0x50517700 in QObject::qt_metacall(QMetaObject::Call, int, void**) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#16 0x50517710 in QObject::customEvent(QEvent*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#17 0x50517718 in QObject::timerEvent(QTimerEvent*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#18 0x50517708 in QObject::eventFilter(QObject*, QEvent*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#19 0x505176e8 in QObject::disconnectNotify(QMetaMethod const&) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#20 0x505176e0 in QObject::event(QEvent*) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#21 0x50521010 in QOpenGLStaticContext::~QOpenGLStaticContext() () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#22 0x5054cb54 in _fu38___ZTVN10__cxxabiv120__si_class_type_infoE () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#23 0x504f1470 in QWindowsBackingStore::scroll(QRegion const&, int, int) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#24 0x504f17e0 in QWindowsBackingStore::beginPaint(QRegion const&) () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#25 0x504f15f0 in QWindowsBackingStore::~QWindowsBackingStore() () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#26 0x505174c0 in QPlatformFontDatabase::invalidate() () from C:\msys64\mingw32\share\qt5\plugins\platforms\qwindows.dll
#27 0x00000000 in ?? ()
(gdb)
```

The output of `thread apply all bt` at that point: 
[mesa-thread-apply-all.zip](https://github.com/msys2/MINGW-packages/files/8159757/mesa-thread-apply-all.zip)

This might also be an issue with Octave or Qt5. But it works if `mesa` is not installed...

**Comment by mmuetzel** [comment]
Still crashes on MINGW32 with mesa3d 22.0.0-1.

**Comment by mmuetzel** [comment]
The crash disappeared after the update to mesa3d 22.0.1-1.
