### ISSUE TITLE
[fossil] clone doesn't work

### ISSUE THREAD

**Issue by kuehro** [msys2/MINGW-packages#10942]
Trying to extract the tcl code with the latest pacman fossil does nothing, but gives an error code:

CAMPISOL+keckhard@CAMPISOL MINGW64 ~
# fossil clone https://core.tcl-lang.org/tcl tcl.fossil

CAMPISOL+keckhard@CAMPISOL MINGW64 ~
# echo $?
127

# fossil version
This is fossil version 2.18 [84f25d7eb1] 2022-02-23 13:22:20 UTC

Downloading the fossil source code from today and building in an mingw-w64 prompt with 

#  FOSSIL_ENABLE_SSL=1 X64=1 gmake -f win/Makefile.mingw

works as expected:

# fossil version
This is fossil version 2.18 [84f25d7eb1] 2022-02-23 13:22:20 UTC

# fossil-src-2.18/fossil.exe clone https://core.tcl-lang.org/tcl tcl.fossil
Unable to verify SSL cert from core.tcl-lang.org
  subject:   C = US, ST = California, L = San Francisco, O = "Cloudflare, Inc.", CN = sni.cloudflaressl.com
  issuer:    C = US, O = "Cloudflare, Inc.", CN = Cloudflare Inc ECC CA-3
  notBefore: 2021-07-14 00:00:00 UTC
  notAfter:  2022-07-13 23:59:59 UTC
  sha256:    d264ecc88dd859ec9bcc54a561abdeacfa038149df3b9e6ee415f398a373b287
accept this cert and continue (y/N/fingerprint)? y
remember this exception (y/N)? y
Round-trips: 182   Artifacts sent: 0  received: 197278
Clone done, wire bytes sent: 48572  received: 185403583  ip: 2606:4700::6812:b841
Rebuilding repository meta-data...
  100.0% complete...
Extra delta compression...
Vacuuming the database...
project-id: 1ec9da4c469c29f4717e2a967fe6b916d9c8c06e
server-id:  628c894fa727a2fc53f27712540083ed63f91a79
admin-user: CAMPISOL+keckhard (password is "zzzzzzzzzzz")

# echo $?
0

**Comment by chdka** [comment]
When invoking `fossil timeline` also nothing is shown.

As a workaround I've downgraded to version 2.17 from my cache.

`pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-fossil-2.17-1-any.pkg.tar.zst`

**Comment by kuehro** [comment]
Some debugging infos:

# gdb /mingw64/bin/fossil.exe
...
(gdb) run open ../tcl.fossil
Starting program: C:\msys64\mingw64\bin\fossil.exe open ../tcl.fossil
[New Thread 6780.0x26b4]
[New Thread 6780.0x1d6c]
[New Thread 6780.0x262c]
Pull from https://core.tcl-lang.org/tcl
Round-trips: 1   Artifacts sent: 0  received: 0
Pull done, wire bytes sent: 385  received: 2740  ip: 2606:4700::6812:b741
warning: Critical error detected c0000374

Thread 1 received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffbbfd0ef13 in ntdll!RtlIsZeroMemory () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffbbfd0ef13 in ntdll!RtlIsZeroMemory ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007ffbbfd17cd2 in ntdll!RtlpNtSetValueKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007ffbbfd17fba in ntdll!RtlpNtSetValueKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007ffbbfd1dc41 in ntdll!RtlpNtSetValueKey ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007ffbbfc35b43 in ntdll!RtlGetCurrentServiceSessionId ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#5  0x00007ffbbfc347b1 in ntdll!RtlFreeHeap ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#6  0x00007ffbbe139c9c in msvcrt!free () from C:\WINDOWS\System32\msvcrt.dll
#7  0x00007ff7c97a3960 in ?? ()
#8  0x00007ff7c97a722c in ?? ()
#9  0x00007ff7c97a8393 in ?? ()
#10 0x00007ff7c97ebf64 in ?? ()
#11 0x00007ff7c98b481e in ?? ()
#12 0x00007ff7c96413b1 in ?? ()
#13 0x00007ff7c96414e6 in ?? ()
#14 0x00007ffbbf8d7034 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#15 0x00007ffbbfc62651 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#16 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) quit

An sqlite file .fslckout has been created in the directory.

**Comment by kuehro** [comment]
The new fossil package 2.19 is still broken. 

\# fossil version
This is fossil version 2.19 [1e131febd3] 2022-07-21 16:10:55 UTC

**Comment by kuehro** [comment]
The package 2.20 is still broken. Something is wrong with the patches in msys2 and with the quality control of packages.
I will try to debug the package build.

**Comment by kuehro** [comment]
**Now it works**. Tested with mingw-w64-ucrt-x86_64-fossil-2.27-2 (with the optional  mingw-w64-ucrt-x86_64-putty-0.83-1 and mingw-w64-ucrt-x86_64-putty-ssh-0.0-4).

Thanks.
