### ISSUE TITLE
python-jupyter-nbformat: Mandatory dependency `python-fastjsonschema` missed

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#11568]
```console
$ python
Python 3.9.11 (main, Mar 18 2022, 16:52:43)  [GCC 11.2.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import nbformat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:/msys32/mingw32/lib/python3.9/site-packages/nbformat/__init__.py", line 11, in <module>
    from . import v1, v2, v3, v4
  File "D:/msys32/mingw32/lib/python3.9/site-packages/nbformat/v4/__init__.py", line 39, in <module>
    from .convert import downgrade, upgrade
  File "D:/msys32/mingw32/lib/python3.9/site-packages/nbformat/v4/convert.py", line 13, in <module>
    from .. import validator
  File "D:/msys32/mingw32/lib/python3.9/site-packages/nbformat/validator.py", line 13, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "D:/msys32/mingw32/lib/python3.9/site-packages/nbformat/json_compat.py", line 10, in <module>
    import fastjsonschema
ModuleNotFoundError: No module named 'fastjsonschema'
>>> exit()

```

**Comment by podsvirov** [comment]
Good! We have two solutions :-) What is best? :-)

**Comment by Biswa96** [comment]
Let's settle this with rock-paper-scissors 😄

**Comment by podsvirov** [comment]
@Biswa96 thanks for fix!
