### ISSUE TITLE
Help v8 to repair  package and build error

### ISSUE THREAD

**Issue by marklove5102** [msys2/MINGW-packages#11694]
mingw-w64-v8
https://github.com/NativeScript/android-v8/issues/20
missing  libc++ dll  and include
````bash
$ g++ v8dll.cpp -lv8 -shared
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\msys64\tmp\cc6wepyo.o:v8dll.cpp:(.text+0x56): undefined reference to `v8::platform::NewDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, std::unique_ptr<v8::TracingController, std::default_delete<v8::TracingController> >)'
collect2.exe: error: ld returned 1 exit status
````
or 
rebuild 
set gn
use_custom_libcxx = false

build error
`````bash
freem@DESKTOP-R102CHR MINGW64 ~/pkg/mingw-packages/mingw-w64-v8
$ makepkg -si
==> Making package: mingw-w64-v8 9.1.269.39-2 (Fri May 20 13:30:53 2022)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating bare-clones/gn git repo...
Fetching origin
  -> Found 9.1.269.39.zip
  -> Updating bare-clones/build git repo...
Fetching origin
  -> Updating bare-clones/zlib git repo...
Fetching origin
  -> Updating bare-clones/common git repo...
Fetching origin
  -> Updating bare-clones/googletest git repo...
Fetching origin
  -> Updating bare-clones/jinja2 git repo...
Fetching origin
  -> Updating bare-clones/markupsafe git repo...
Fetching origin
  -> Updating bare-clones/clang git repo...
Fetching origin
  -> Found 0000-add-mingw-main-code-changes.patch
  -> Found 0001-add-mingw-toolchain.patch
  -> Found 0002-gn-ninja-deletes-objs-workaround.patch
  -> Found icu.gn
  -> Found zlib.gn
  -> Found v8_libbase.pc
  -> Found v8_libplatform.pc
  -> Found v8.pc
==> Validating source files with sha256sums...
    bare-clones/gn ... Skipped
    9.1.269.39.zip ... Passed
    bare-clones/build ... Skipped
    bare-clones/zlib ... Skipped
    bare-clones/common ... Skipped
    bare-clones/googletest ... Skipped
    bare-clones/jinja2 ... Skipped
    bare-clones/markupsafe ... Skipped
    bare-clones/clang ... Skipped
    0000-add-mingw-main-code-changes.patch ... Passed
    0001-add-mingw-toolchain.patch ... Passed
    0002-gn-ninja-deletes-objs-workaround.patch ... Passed
    icu.gn ... Passed
    zlib.gn ... Passed
    v8_libbase.pc ... Passed
    v8_libplatform.pc ... Passed
    v8.pc ... Passed
==> Extracting sources...
  -> Creating working copy of bare-clones/gn git repo...
Reset branch 'makepkg'
  -> Extracting 9.1.269.39.zip with bsdtar
  -> Creating working copy of bare-clones/build git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/zlib git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/common git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/googletest git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/jinja2 git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/markupsafe git repo...
Reset branch 'makepkg'
  -> Creating working copy of bare-clones/clang git repo...
Reset branch 'makepkg'
==> Starting prepare()...
Preparing GN source
warning: build/gen.py has type 100644, expected 100755
Patching v8 source
patching file BUILD.gn
patching file include/v8.h
patching file include/v8config.h
patching file src/base/bits.h
patching file src/base/export-template.h
patching file src/base/platform/platform-win32.cc
patching file src/base/platform/time.cc
patching file src/base/win32-headers.h
patching file src/codegen/code-stub-assembler.h
patching file src/codegen/handler-table.cc
patching file src/common/assert-scope.h
patching file src/common/globals.h
patching file src/compiler/node-cache.h
patching file src/compiler/representation-change.cc
patching file src/compiler/type-cache.h
patching file src/heap/paged-spaces-inl.h
patching file src/heap/paged-spaces.h
patching file src/objects/feedback-vector.cc
patching file src/objects/fixed-array-inl.h
patching file src/objects/fixed-array.h
patching file src/objects/ordered-hash-table.h
patching file src/profiler/heap-snapshot-generator.cc
patching file src/snapshot/snapshot-utils.cc
patching file src/trap-handler/handler-inside-win.cc
patching file src/trap-handler/handler-inside-win.h
patching file src/trap-handler/handler-outside-win.cc
patching file src/wasm/function-body-decoder-impl.h
patching file src/wasm/wasm-external-refs.cc
patching file test/cctest/BUILD.gn
patching file test/unittests/BUILD.gn
patching file test/unittests/wasm/trap-handler-win-unittest.cc
patching file test/unittests/wasm/trap-handler-x64-unittest.cc
patching file third_party/googletest/BUILD.gn
patching file tools/BUILD.gn
patching file tools/debug_helper/BUILD.gn
patching file tools/v8windbg/BUILD.gn
patching file tools/v8windbg/base/dbgext.h
patching file tools/v8windbg/src/v8-debug-helper-interop.h
patching file tools/v8windbg/test/debug-callbacks.h
Patching build directory
Patching build directory python
/home/freem/pkg/mingw-packages/mingw-w64-v8/src/build/util/lastchange.py -o /home/freem/pkg/mingw-packages/mingw-w64-v8/src/build/util/LASTCHANGE
ERROR:root:Failed to get version info: Git command 'git log -1 --format=%H %ct --grep=^Change-Id: HEAD' in C:\msys64\home\freem\pkg\MINGW-packages\mingw-w64-v8\src\build failed: rc=128, stdout='' stderr='error: object directory /home/freem/pkg/mingw-packages/mingw-w64-v8/bare-clones/build/objects does not exist; check .git/objects/info/alternates
fatal: bad object HEAD
'
Patching build directory rm
ln Patching build directory rm
Patching zlib directory
Patching icu directory
Soft linking extra repos
==> Removing existing $pkgdir/ directory...
==> Starting build()...
error: object directory /home/freem/pkg/mingw-packages/mingw-w64-v8/bare-clones/gn/objects does not exist; check .git/objects/info/alternates
fatal: HEAD is neither a commit nor blob
Traceback (most recent call last):
  File "C:\msys64\home\freem\pkg\mingw-packages\mingw-w64-v8\src\gn\build\gen.py", line 809, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\msys64\home\freem\pkg\mingw-packages\mingw-w64-v8\src\gn\build\gen.py", line 145, in main
    GenerateLastCommitPosition(host,
  File "C:\msys64\home\freem\pkg\mingw-packages\mingw-w64-v8\src\gn\build\gen.py", line 153, in GenerateLastCommitPosition
    describe_output = subprocess.check_output(
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:/msys64/mingw64/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'describe', 'HEAD', '--match', 'initial-commit']' returned non-zero exit status 128.
==> ERROR: A failure occurred in build().
    Aborting...

`````

**Comment by Biswa96** [comment]
@Kwizatz Can you provide any hint about this issue?

**Comment by marklove5102** [comment]
`````
ERROR:root:Failed to get version info: Git command 'git log -1 --format=%H %ct --grep=^Change-Id: HEAD' in C:\msys64\home\freem\pkg\MINGW-packages\mingw-w64-v8\src\build failed: rc=128, stdout='' stderr='error: object directory /home/freem/pkg/mingw-packages/mingw-w64-v8/bare-clones/build/objects does not exist; check .git/objects/info/alternates
fatal: bad object HEAD
'
------------------------------------------and----------------------------------
==> Starting build()...
error: object directory /home/freem/pkg/mingw-packages/mingw-w64-v8/bare-clones/gn/objects does not exist; check .git/objects/info/alternates
`````

source=("bare-clones/gn::git+https://gn.googlesource.com/gn#tag=5da62d5e9d0f10cb8ece7c30563a6a214c78b68d"
        "bare-clones/build::git+https://chromium.googlesource.com/chromium/src/build.git#commit=fd86d60f33cbc794537c4da2ef7e298d7f81138e"

This problem is caused by makepkg
cd src
git clone https://gn.googlesource.com/gn
cd gn
git checkou 5da62d5e9d0f10cb8ece7c30563a6a214c78b68d
git clone https://chromium.googlesource.com/chromium/src/build
cd build
git checkou fd86d60f33cbc794537c4da2ef7e298d7f81138e

The problem no longer occurs

**Comment by marklove5102** [comment]
fix 
gn/src/base/files/file_enumerator_win.cc
add #include <limits>

make -si
error
````
==> Starting prepare()...
Preparing GN source
Patching v8 source
Patching build directory
Patching zlib directory
Patching icu directory
Soft linking extra repos
==> Removing existing $pkgdir/ directory...
==> Starting build()...
ninja: Entering directory `out/x86_64'
ninja: no work to do.
ERROR at //build/config/compiler/BUILD.gn:16:1: Unable to load "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/config/gclient_args.gni".
import("//build/config/gclient_args.gni")
^---------------------------------------
See //BUILD.gn:308:5: which caused the file to be included.
    "//build/config/compiler:wexit_time_destructors",
    ^-----------------------------------------------
Traceback (most recent call last):
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 573, in <module>
    sys.exit(main())
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
  File "C:/msys64/home/freem/pkg/mingw-packages/mingw-w64-v8/src/v8-8.3.110.13/build/vs_toolchain.py", line 187, in GetVisualStudioVersion
    ' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
==> ERROR: A failure occurred in build().
    Aborting...
````
Finally msys2 mingw64 was recognized as ms vs_toolchain

**Comment by marklove5102** [comment]
@lazka 
@jeremyd2019 

Can you provide any hint about this issue?

**Comment by Kwizatz** [comment]
I am in the process of updating to 10.1.124.12, my guess is that some update to some other component is not sitting well with the current PKGBUILD which is a bit stale at the moment.

Other than that... do you have Visual Studio or the WinSDK 10.0.19x installed? They are not required, but it looks like vs_toolchain.py is looking for those, since I have VS installed it never complained and the CI did not complain either, so it may have slipped... sorry about that.

If you have none, I recomend installing the [standalone SDK](https://go.microsoft.com/fwlink/?linkid=2120843) first and give it a try, you'll have to go into the setup (go to uninstall programs on control panel, find the sdk and click on uninstall/change and then change, tick all boxes) to add debug tools. if that does not work uninstall it and install VS community, make sure you install the SDK from the VS installer as well and do the same thing to change the SDK from the control panel.

**Comment by marklove5102** [comment]
[VS community](https://visualstudio.microsoft.com/vs/community/)  2019 AND [standalone SDK](https://go.microsoft.com/fwlink/?linkid=2120843)  
Finally I chose vs2019 community to continue working

**Comment by Biswa96** [comment]
> Finally I chose vs2019 community to continue working

OP was influenced by dark force and went to dark side.

![image](https://media.tenor.com/HBIVp8Qu_n8AAAAd/never-turn-dark-side.gif)
