### ISSUE TITLE
ImageMagick 7.1.0-33 broken support for gif and png formats

### ISSUE THREAD

**Issue by ice0** [msys2/MINGW-packages#11713]
If you try to use png or gif format for conversion (for example), it will silently die without error.
Tiff and bmp formats works ok:
```
$ convert ./duck_vertex_icon.bmp ./duck_vertex_icon1.tiff
$ echo $?
0

$ convert ./duck_vertex_icon.bmp ./duck_vertex_icon1.bmp
$ echo $?
0

$ convert ./duck_vertex_icon.bmp ./duck_vertex_icon1.png
$ echo $?
127

$ convert ./duck_vertex_icon.bmp ./duck_vertex_icon1.gif
$ echo $?
127
```

```
$ convert --version
Version: ImageMagick 7.1.0-33 Q16-HDRI x86_64 20040 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fftw flif fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf xml zlib
Compiler: gcc (11.3)
```

**Comment by ice0** [comment]
> I can't reproduce. Does it depend on the input maybe?

Maybe. Then I'll try to check on a clean installation.

**Comment by ice0** [comment]
@lazka 
Does this command works? It should create an empty `green.png` file.
```
convert -size 800x800 xc:green green.png
```

**Comment by Biswa96** [comment]
I have built ImageMagick7 from git repository. The command with green.png works but _only_ the png convert command does not. I can try to open a issue in upstream. One of my archenemy appears in stack trace 😎 

```
#5  0x00007ffbc33f47b1 in ntdll!RtlFreeHeap () from C:\Windows\SYSTEM32\ntdll.dll
#6  0x00007ffbc0d6f05b in ucrtbase!_free_base () from C:\Windows\System32\ucrtbase.dll
```

**Comment by Biswa96** [comment]
I have reported the issue in upstream here https://github.com/ImageMagick/ImageMagick/issues/5172

**Comment by ice0** [comment]
Just tested on clean install (Windows 10).
```
$ pacman -Syu
$ pacman -S mingw-w64-x86_64-imagemagick
$ magick -size 800x800 xc:green green.png
$ echo $?
127
```

File is not created.

**Comment by Biswa96** [comment]
After some random tests, this seems to be an issue of openmp in GCC 12. Adding `--disable-openmp` option wiht configure command fixes the issue. But GCC 12 needs some fixing. A bug report will be filed in gcc upstream.
