### ISSUE TITLE
gnome-calculator crash when inputting a variable name

### ISSUE THREAD

**Issue by jack6th** [msys2/MINGW-packages#11804]
mingw-w64-i686-gnome-calculator 42.1-1 on Windows 10 x64 21H2

reproduce:
1. run gnome-calculator
2. change to 'Advanced' mode
3. click 'x' button on the bottom row (below the button x! and |x|)
4. click the entry which shows 'Variable name'
5. input 'a'

Now the gnome-calculator crash.

**Comment by Biswa96** [comment]
Thanks for reporting this issue. I can reproduce the issue with mingw-w64-ucrt-x86_64-gnome-calculator package also.

**Comment by lb90** [comment]
Here's the stacktrace:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007fff06d4a33e in ntdll!RtlRegisterSecureMemoryCacheCallback () from C:\WINDOWS\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007fff06d4a33e in ntdll!RtlRegisterSecureMemoryCacheCallback ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#1  0x00007fff06d487cb in ntdll!RtlRegisterSecureMemoryCacheCallback ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#2  0x00007fff06c7d255 in ntdll!RtlAllocateHeap ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#3  0x00007fff06c7b44d in ntdll!RtlAllocateHeap ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#4  0x00007fff04d39d40 in msvcrt!malloc () from C:\WINDOWS\System32\msvcrt.dll
#5  0x00007ffec7362046 in ?? () from D:\msys64\mingw64\bin\libglib-2.0-0.dll
#6  0x00007ffee2ec8cb2 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#7  0x00007ffee2eb86a6 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#8  0x00007ffee2ec093d in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#9  0x00007ffec4aa30a3 in end_change (self=0x2035a703f90)
    at ../gtk4/gtk/gtktext.c:2058
#10 0x00007ffec4aa60d8 in gtk_text_delete_text (self=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:3403
#11 0x00007ffec4aa13dd in editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:1528
#12 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x81186048f0,
    invocation_hint=0x8118604850,
    marshal_data=0x7ffec4aa13a6 <editable_delete_text>)
    at gtk/gtkmarshalers.c:5484
#13 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#14 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#15 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#16 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#17 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a703f90, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#18 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#19 0x00007ffec491542f in gtk_editable_default_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:232
#20 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118604e10,
    invocation_hint=0x8118604d70,
    marshal_data=0x7ffec49153f3 <gtk_editable_default_delete_text>)
    at gtk/gtkmarshalers.c:5484
#21 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#22 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#23 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#24 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#25 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#26 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a2d63b0,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#27 0x00007ffec4915ed2 in gtk_editable_set_text (editable=0x2035a2d63b0,
    text=0x2036f6b42f0 "") at ../gtk4/gtk/gtkeditable.c:599
#28 0x00007ff7e8064b16 in ?? ()
#29 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#30 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#31 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#32 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#33 0x00007ffec4916bae in delegate_changed (delegate=0x2035a703f90,
    editable=0x2035a2d63b0) at ../gtk4/gtk/gtkeditable.c:974
#34 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#35 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#36 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#37 0x00007ffee2ec08e7 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#38 0x00007ffec4aa30a3 in end_change (self=0x2035a703f90)
    at ../gtk4/gtk/gtktext.c:2058
#39 0x00007ffec4aa60d8 in gtk_text_delete_text (self=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:3403
#40 0x00007ffec4aa13dd in editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:1528
#41 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118605c40,
    invocation_hint=0x8118605ba0,
    marshal_data=0x7ffec4aa13a6 <editable_delete_text>)
    at gtk/gtkmarshalers.c:5484
#42 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#43 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#44 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#45 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#46 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a703f90, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#47 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#48 0x00007ffec491542f in gtk_editable_default_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:232
#49 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118606160,
    invocation_hint=0x81186060c0,
    marshal_data=0x7ffec49153f3 <gtk_editable_default_delete_text>)
    at gtk/gtkmarshalers.c:5484
#50 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#51 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#52 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#53 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#54 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#55 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a2d63b0,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#56 0x00007ffec4915ed2 in gtk_editable_set_text (editable=0x2035a2d63b0,
    text=0x2036f6b42b0 "") at ../gtk4/gtk/gtkeditable.c:599
#57 0x00007ff7e8064b16 in ?? ()
#58 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#59 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#60 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#61 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#62 0x00007ffec4916bae in delegate_changed (delegate=0x2035a703f90,
    editable=0x2035a2d63b0) at ../gtk4/gtk/gtkeditable.c:974
#63 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#64 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#65 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#66 0x00007ffee2ec08e7 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#67 0x00007ffec4aa30a3 in end_change (self=0x2035a703f90)
    at ../gtk4/gtk/gtktext.c:2058
#68 0x00007ffec4aa60d8 in gtk_text_delete_text (self=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:3403
#69 0x00007ffec4aa13dd in editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:1528
#70 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118606f90,
    invocation_hint=0x8118606ef0,
    marshal_data=0x7ffec4aa13a6 <editable_delete_text>)
    at gtk/gtkmarshalers.c:5484
#71 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#72 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#73 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#74 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#75 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a703f90, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#76 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#77 0x00007ffec491542f in gtk_editable_default_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:232
#78 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x81186074b0,
    invocation_hint=0x8118607410,
    marshal_data=0x7ffec49153f3 <gtk_editable_default_delete_text>)
    at gtk/gtkmarshalers.c:5484
#79 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#80 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#81 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#82 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#83 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#84 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a2d63b0,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#85 0x00007ffec4915ed2 in gtk_editable_set_text (editable=0x2035a2d63b0,
    text=0x2036f6b4270 "") at ../gtk4/gtk/gtkeditable.c:599
#86 0x00007ff7e8064b16 in ?? ()
#87 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#88 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#89 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#90 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#91 0x00007ffec4916bae in delegate_changed (delegate=0x2035a703f90,
    editable=0x2035a2d63b0) at ../gtk4/gtk/gtkeditable.c:974
#92 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#93 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#94 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#95 0x00007ffee2ec08e7 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#96 0x00007ffec4aa30a3 in end_change (self=0x2035a703f90)
    at ../gtk4/gtk/gtktext.c:2058
#97 0x00007ffec4aa60d8 in gtk_text_delete_text (self=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:3403
#98 0x00007ffec4aa13dd in editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:1528
#99 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x81186082e0,
    invocation_hint=0x8118608240,
    marshal_data=0x7ffec4aa13a6 <editable_delete_text>)
    at gtk/gtkmarshalers.c:5484
#100 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#101 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#102 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#103 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#104 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a703f90, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#105 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#106 0x00007ffec491542f in gtk_editable_default_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:232
#107 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118608800,
    invocation_hint=0x8118608760,
    marshal_data=0x7ffec49153f3 <gtk_editable_default_delete_text>)
    at gtk/gtkmarshalers.c:5484
#108 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#109 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#110 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#111 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#112 0x00007ffec49153ec in gtk_editable_default_do_delete_text (
    editable=0x2035a2d63b0, start_pos=0, end_pos=-1)
    at ../gtk4/gtk/gtkeditable.c:221
#113 0x00007ffec4915c06 in gtk_editable_delete_text (editable=0x2035a2d63b0,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtkeditable.c:515
#114 0x00007ffec4915ed2 in gtk_editable_set_text (editable=0x2035a2d63b0,
    text=0x2036f6b4230 "") at ../gtk4/gtk/gtkeditable.c:599
#115 0x00007ff7e8064b16 in ?? ()
#116 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#117 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#118 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#119 0x00007ffee2ec0778 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#120 0x00007ffec4916bae in delegate_changed (delegate=0x2035a703f90,
    editable=0x2035a2d63b0) at ../gtk4/gtk/gtkeditable.c:974
#121 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#122 0x00007ffee2eba5d8 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#123 0x00007ffee2ec0314 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#124 0x00007ffee2ec08e7 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#125 0x00007ffec4aa30a3 in end_change (self=0x2035a703f90)
    at ../gtk4/gtk/gtktext.c:2058
#126 0x00007ffec4aa60d8 in gtk_text_delete_text (self=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:3403
#127 0x00007ffec4aa13dd in editable_delete_text (editable=0x2035a703f90,
    start_pos=0, end_pos=-1) at ../gtk4/gtk/gtktext.c:1528
#128 0x00007ffec484c3c3 in _gtk_marshal_VOID__INT_INT (closure=0x2035a2ad180,
    return_value=0x0, n_param_values=3, param_values=0x8118609630,
    invocation_hint=0x8118609590,
    marshal_data=0x7ffec4aa13a6 <editable_delete_text>)
    at gtk/gtkmarshalers.c:5484
#129 0x00007ffee2ea820b in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
#130 0x00007ffee2eba021 in ?? ()
   from D:\msys64\mingw64\bin\libgobject-2.0-0.dll
```

And so on. I guess the problem is in gnome-calculator or in GTK.

**Comment by lb90** [comment]
I can reproduce on Linux too. I'm going to open a ticket on GNOME gitlab

**Comment by lb90** [comment]
Ok opened https://gitlab.gnome.org/GNOME/gnome-calculator/-/issues/282

**Comment by lb90** [comment]
Fixed upstream!
