### ISSUE TITLE
Current ruby does not support libffi-8.dll

### ISSUE THREAD

**Issue by hkinke** [msys2/MINGW-packages#12987]
### Description

`irb` crashes

```bash
<internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': 126: The specified module could not be found.   - C:/msys64/mingw64/lib/ruby/3.1.0/x64-mingw32/fiddle.so (LoadError)
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/3.1.0/fiddle.rb:3:in `<top (required)>'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/3.1.0/fiddle/import.rb:2:in `<top (required)>'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/3.1.0/reline/windows.rb:1:in `<top (required)>'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/3.1.0/reline.rb:567:in `<top (required)>'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/3.1.0/irb.rb:13:in `<top (required)>'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/msys64/mingw64/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/msys64/mingw64/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:9:in `<top (required)>'
        from C:/msys64/mingw64/bin/irb:33:in `load'
        from C:/msys64/mingw64/bin/irb:33:in `<main>'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.22000.918]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

irb prompt

### Actual behavior

`LoadError`

### Repro steps

Revert to libffi-7.dll (instead of libffi-8.dll) or rebuild ruby with libffi-8.dll.

**Comment by Biswa96** [comment]
Hi @hkinke, Thank you for reporting the issue. I can reproduce it. The reason is that ruby was not rebuilt after libffi update. ruby package will be updated quickly.

**Comment by lazka** [comment]
hm, might be package-grokker didn't pick it up because of the ".so" extension. should be fixed there.

sorry for the breakage

**Comment by hkinke** [comment]
issue resolved, thank you
