### ISSUE TITLE
Add [python-pyqt5-webengine]

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#13100]
### Package name

python-pyqt5-webengine

### Brief description of package

Missing `python-pyqt5-webengine` package required to launch [spyder](https://packages.msys2.org/base/mingw-w64-python-spyder) IDE.

```console
 Traceback (most recent call last):
  File "D:/msys32/mingw32/lib/python3.10/site-packages/qtpy/QtWebEngineWidgets.py", line 29, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\msys32\mingw32\bin\spyder-script.pyw", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.3.3', 'gui_scripts', 'spyder')())
  File "D:/msys32/mingw32/lib/python3.10/site-packages/spyder/app/start.py", line 248, in main
    from spyder.app import mainwindow
  File "D:/msys32/mingw32/lib/python3.10/site-packages/spyder/app/mainwindow.py", line 57, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "D:/msys32/mingw32/lib/python3.10/site-packages/qtpy/QtWebEngineWidgets.py", line 37, in <module>
    raise QtModuleNotInstalledError(
qtpy.QtModuleNotInstalledError: The QtWebEngineWidgets module was not found. It must be installed separately as PyQtWebEngine.
```

### URL for package's homepage

https://archlinux.org/packages/extra/x86_64/python-pyqt5-webengine

### Provide a basic test case to validate the package's functionality.

Just launch `spyder` IDE.

### MINGW environments where you need the package

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [ ] CLANGARM64

**Comment by podsvirov** [comment]
Cc: @MehdiChinoune, @Biswa96

**Comment by MehdiChinoune** [comment]
duplicate of #8444
see also: #12039 and #9362

**Comment by podsvirov** [comment]
Sorry for duplication and thanks for related links.

**Comment by podsvirov** [comment]
Another solution to restore launching `spyder` application is rollback the [python-qtpy](https://packages.msys2.org/package/mingw-w64-i686-python-qtpy) package to `2.1.0` version that support `webkit`.
Cc: @MehdiChinoune

**Comment by podsvirov** [comment]
@lazka can we rollback package and how do it?

**Comment by MehdiChinoune** [comment]
I think we could fix qtpy by reverting some of: https://github.com/spyder-ide/qtpy/commit/cecb9fce208a6d00cac15cbf38a1c59470e7c3cd

**Comment by lazka** [comment]
> @lazka can we rollback package and how do it?

in theory yes, but what is the plan to fix things after that?

**Comment by podsvirov** [comment]
Plan already there #13112
