### ISSUE TITLE
mingw-w64-python-skia-pathops: fails to rebuild

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MINGW-packages#14044]
```
  Traceback (most recent call last):
    File "C:\_\mingw-w64-python-skia-pathops\src\python-build-CLANG32\setup.py", line 409, in <module>
      setup(**setup_params)
    File "D:/M/msys64/clang32/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "D:/M/msys64/clang32/lib/python3.10/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "D:/M/msys64/clang32/lib/python3.10/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:/M/msys64/clang32/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "D:/M/msys64/clang32/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:/M/msys64/clang32/lib/python3.10/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:/M/msys64/clang32/lib/python3.10/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:/M/msys64/clang32/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "D:/M/msys64/clang32/lib/python3.10/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\_\mingw-w64-python-skia-pathops\src\python-build-CLANG32\setup.py", line 218, in run
      self._copy_windows_dlls()
    File "C:\_\mingw-w64-python-skia-pathops\src\python-build-CLANG32\setup.py", line 232, in _copy_windows_dlls
      dll_filename, ", ".join(ext.library_dirs)
  UnboundLocalError: local variable 'dll_filename' referenced before assignment
```

**Comment by lazka** [comment]
Fixed by #14044
