### ISSUE TITLE
mingw-w64-grep: version 3.8 results in segmentation fault

### ISSUE THREAD

**Issue by cyrilarnould** [msys2/MINGW-packages#14472]
### Description

Since updating, mingw-w64-grep doesn't work anymore, resulting in segmentation faults every time. The only exceptions I've seen so far are when called with the --help or --version options or without any options.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2251]

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Expected behavior

I would expect it to behave as with grep 3.6:
```
$ echo hello > test.txt
$ grep hello test.txt
hello
$ grep nothello test.txt

```

### Actual behavior

After updating, I only get segmentation faults:
```
$ echo hello > test.txt
$ grep hello test.txt
Segmentation fault
$ grep nothello test.txt
Segmentation fault
```

### Repro steps

Execute the following in the MINGW64 environment:
```
$ echo hello > test.txt
$ grep hello test.txt
Segmentation fault
$ grep nothello test.txt
Segmentation fault
```

**Comment by Biswa96** [comment]
Yeah, I can reproduce the issue in mingw64. Here is the backtrace.

```
(gdb) set $pc = *(void **)$rsp
(gdb) set $rsp = $rsp + 8
(gdb) bt
#0  0x00007ff783726442 in re_compile_internal (preg=0x3e881ff890, pattern=0x18291fe48d0 "hello\n", '«' <repeats 16 times>, "î_î_î_î_î_", length=5, syntax=33622598)
    at ../../lib/regcomp.c:733
#1  0x00007ff783725420 in rpl_re_compile_pattern (pattern=0x18291fe48d0 "hello\n", '«' <repeats 16 times>, "î_î_î_î_î_", length=5, bufp=0x3e881ff890)
    at ../../lib/regcomp.c:217
#2  0x00007ff783701824 in regex_compile (dc=0x18291fe4850, p=0x18291fe48d0 "hello\n", '«' <repeats 16 times>, "î_î_î_î_î_", len=5, pcount=0, lineno=0,
    syntax_bits=68166, syntax_only=true) at ../../src/dfasearch.c:163
#3  0x00007ff783701c33 in GEAcompile (pattern=0x18291fe48d0 "hello\n", '«' <repeats 16 times>, "î_î_î_î_î_", size=5, syntax_bits=68166, exact=false)
    at ../../src/dfasearch.c:266
#4  0x00007ff78370778a in main (argc=3, argv=0x18291fe4610) at ../../src/grep.c:2975
```


 not sure what fails, gnulib? 🤔
