### ISSUE TITLE
SuiteSparse 6 crashes on 32-bit

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MINGW-packages#14658]
### Description / Steps to reproduce the issue

1. Install `octave` for MINGW32: `pacman -S mingw-w64-i686-octave`.
2. Start Octave with `octave` from the MINGW32 shell.
3. Execute, e.g., the following commands:
```
a = sparse (5, 6);
a(3,1) = 0.8;
a(2,2) = 1.4;
a(1,6) = -0.5;
r = qr (a);
```

### Expected behavior

The QR decomposition of `a` should be returned.

### Actual behavior

Octave crashes with the following output:
```
$ octave
GNU Octave, version 7.3.0
Copyright (C) 1993-2022 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "i686-w64-mingw32".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

octave:1> a = sparse (5, 6);
octave:2> a(3,1) = 0.8;
octave:3> a(2,2) = 1.4;
octave:4> a(1,6) = -0.5;
octave:5> r = qr (a);
fatal: caught signal Segmentation fault -- stopping myself...
```

I compiled SuiteSparse with debug flags and without stripping symbols. With that version, I see the following top of the backtrace when catching the segfault with `gdb`:
```
Thread 7 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 4692.0x7938]
0x56672a86 in cholmod_l_postorder (Parent=Parent@entry=0x1e1f0d20, n=<optimized out>, n@entry=0, Weight=Weight@entry=0x0, Post=Post@entry=0x1e1f0d20, Common=Common@entry=0x1e17ef80) at D:/mingw-w64-suitesparse/src/build-MINGW32/CHOLMOD/Cholesky/cholmod_postorder.c:202
warning: Source file is more recent than executable.
202                 p = Parent [j] ;
(gdb) bt
#0  0x56672a86 in cholmod_l_postorder (Parent=Parent@entry=0x1e1f0d20, n=<optimized out>, n@entry=0,
    Weight=Weight@entry=0x0, Post=Post@entry=0x1e1f0d20, Common=Common@entry=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/CHOLMOD/Cholesky/cholmod_postorder.c:202
#1  0x5666ff7f in cholmod_l_analyze_ordering (A=A@entry=0x1e1f0990, ordering=ordering@entry=0,
    Perm=Perm@entry=0x1e2b6710, fset=fset@entry=0x0, fsize=fsize@entry=0, Parent=Parent@entry=0x1e1f0d20,
    Post=Post@entry=0x1e1f0d20, ColCount=ColCount@entry=0x1e2b67b0, First=First@entry=0x1e1f0d20,
    Level=Level@entry=0x1e1f0d20, Common=Common@entry=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/CHOLMOD/Cholesky/cholmod_analyze.c:344
#2  0x566709d4 in cholmod_l_analyze_p2 (for_whom=0, A=0x1e1f0990, UserPerm=0x0, fset=0x0, fsize=0, Common=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/CHOLMOD/Cholesky/cholmod_analyze.c:729
#3  0x572b238e in spqr_analyze (A=0x1e1efe50, ordering=ordering@entry=0, Quser=Quser@entry=0x0, do_rank_detection=1,
    keepH=keepH@entry=1, cc=cc@entry=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/SPQR/Source/spqr_analyze.cpp:286
#4  0x572c73d8 in spqr_1factor<double> (ordering=ordering@entry=0, tol=6.8389738316909643e-14, tol@entry=-2,
    bncols=0, keepH=keepH@entry=1, A=<optimized out>, A@entry=0x1df3d2e8, ldb=0, Bp=Bp@entry=0x0, Bi=Bi@entry=0x0,
    Bx=<optimized out>, Bx@entry=0x0, cc=cc@entry=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/SPQR/Source/spqr_1factor.cpp:642
#5  0x572ccfca in SuiteSparseQR<double> (ordering=ordering@entry=0, tol=tol@entry=-2, econ=5, getCTX=getCTX@entry=-1,
    A=A@entry=0x1df3d2e8, Bsparse=Bsparse@entry=0x0, Bdense=<optimized out>, Bdense@entry=0x0,
    p_Zsparse=p_Zsparse@entry=0x0, p_Zdense=p_Zdense@entry=0x0, p_R=p_R@entry=0x1e17f7d8, p_E=p_E@entry=0x1e17f7dc,
    p_H=p_H@entry=0x1e17f7e0, p_HPinv=p_HPinv@entry=0x1e17f7e8, p_HTau=p_HTau@entry=0x1e17f7e4,
    cc=cc@entry=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/SPQR/Source/SuiteSparseQR.cpp:265
#6  0x572cc74f in SuiteSparseQR<double> (ordering=0, tol=-2, econ=5, A=0x1df3d2e8, R=0x1e17f7d8, E=0x1e17f7dc,
    H=0x1e17f7e0, HPinv=0x1e17f7e8, HTau=0x1e17f7e4, cc=0x1e17ef80)
    at D:/mingw-w64-suitesparse/src/build-MINGW32/SPQR/Source/SuiteSparseQR.cpp:1404--Type <RET> for more, q to quit, c to continue without paging--
```

The remainder of the backtrace is in function in Octave.

This was still working correctly with SuiteSparse 5.13.0.

See also this upstream report: https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/221

Should we revert to the older version until this is fixed by upstream?

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-10.0-22621

### MINGW environments affected

- [ ] MINGW64
- [X] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by mmuetzel** [comment]
This has been "fixed" by reverting to SuiteSparse 5 for the 32-bit environments.
