### ISSUE TITLE
DistutilsPlatformError

### ISSUE THREAD

**Issue by DarkAbhi** [msys2/MINGW-packages#14887]
### Description / Steps to reproduce the issue

Installing requirements for a Django project from requiremts.txt file causes this.
Python version: Python 3.11.1

Related issue from pip package with their response: https://github.com/pypa/pip/issues/11258

### Expected behavior

Install pip package

### Actual behavior

```
Collecting cffi==1.15.0
  Using cached cffi-1.15.0.tar.gz (484 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\basev\AppData\Local\Temp\pip-install-is6bvsva\cffi_529b071c420640fd9d83b37784c3507a\setup.py", line 126, in <module>
          if sys.platform == "win32" and uses_msvc():
                                         ^^^^^^^^^^^
        File "C:\Users\basev\AppData\Local\Temp\pip-install-is6bvsva\cffi_529b071c420640fd9d83b37784c3507a\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\_distutils\command\config.py", line 224, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\_distutils\command\config.py", line 129, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 344, in compile
          self.initialize()
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\msvc.py", line 214, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\Work-Iku\iku-django-backend\venv\Lib\site-packages\setuptools\msvc.py", line 168, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

CYGWIN_NT-10.0

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
Some aspects of mingw python are not compatible with pypi packages, see https://www.msys2.org/docs/python/. You have to use the mingw python packages.

**Comment by MehdiChinoune** [comment]
How could your Python be 3.11.1, mingw-w64-python is still at 3.10.x

**Comment by DarkAbhi** [comment]
> How could your Python be 3.11.1, mingw-w64-python is still at 3.10.x

My system python version is 3.11.1, I update from 3.10.x a few days back

**Comment by MehdiChinoune** [comment]
> My system python version is 3.11.1, I update from 3.10.x a few days back

So, your issue is not related to mingw-w64-python.

**Comment by Biswa96** [comment]
The issue is not related to mingw packages. Please use mingw python and mingw python-cffi package using pacman command. mingw python-cffi package details can be found here https://packages.msys2.org/base/mingw-w64-python-cffi
