### ISSUE TITLE
Blender 2.93.14 Bug?

### ISSUE THREAD

**Issue by gphg** [msys2/MINGW-packages#15712]
### Description / Steps to reproduce the issue

1. Get `mingw-w64-clang-x86_64-blender` installed
  * Optional: `mingw-w64-clang-x86_64-toolchain` is installed
2. Open it by execute `blender` on terminal under Clang64 shell.
```
$ blender
Read prefs: C:\msys2\home\gphg\.blender\2.93\config\userpref.blend
Bundled Python not found and is expected on this platform (the 'install' target may have not been built)
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
NameError: name 'WM_OT_url_open_preset' is not defined
File "<string>", line 1, in <lambda>
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
NameError: name 'WM_OT_url_open_preset' is not defined
File "<string>", line 1, in <lambda>
Python: Traceback (most recent call last):
  File "C:/msys2/clang64/share/blender/2.93/scripts/startup/bl_operators/wm.py", line 2725, in draw
    col2.operator("wm.url_open_preset", text="Manual", icon='URL').type = 'MANUAL'
TypeError: bpy_struct: item.attr = val: enum "MANUAL" not found in ()

location: <unknown location>:-1
Saved session recovery to 'C:\msys2\tmp\quit.blend'

Blender quit
```

Info on Blender:
```
$ blender -v
Blender 2.93.14
        build date: 2023-01-24
        build time: 01:11:13
        build commit date: 1970-01-01
        build commit time: 00:00
        build hash: unknown
        build platform: Windows
        build type: Release
        build c flags:  -Wall -Werror=implicit-function-declaration -Werror=return-type -Wno-tautological-compare -Wno-unknown-pragmas -Wno-char-subscripts -Wstrict-prototypes -Wmissing-prototypes -Wunused-parameter -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -fopenmp=libomp -std=gnu11 -msse -pipe -funsigned-char -fno-strict-aliasing -msse2
        build c++ flags:  -Wall -Wno-tautological-compare -Wno-unknown-pragmas -Wno-char-subscripts -Wno-overloaded-virtual -Wno-sign-compare -Wno-invalid-offsetof -Wno-suggest-override -march=nocona -msahf -mtune=generic -O2 -pipe -Wno-c++11-narrowing -Wno-array-parameter -Wno-unreachable-code-generic-assoc -fpermissive -fopenmp=libomp -std=c++17 -msse -pipe-funsigned-char -fno-strict-aliasing -msse2
        build link flags: -Xlinker --stack=2097152
        build system: CMake
```

### Expected behavior

No error occur.

### Actual behavior

An error (or two) occur.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### MINGW environments affected

- [x] MINGW64
- [ ] MINGW32
- [x] UCRT64
- [X] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

No.

**Comment by hmartinez82** [comment]
@gphg can you try this with Blender 3.4.1 once it's out in MSYS2?

**Comment by gphg** [comment]
> @gphg can you try this with Blender 3.4.1 once it's out in MSYS2?

With pleasure.

**Comment by gphg** [comment]
3.5.0-1 is out. I'm installing it on my machine now. Closing this since it is irrelevant.
