### ISSUE TITLE
[python-pip] pip v23.0-2 not working under MINGW64

### ISSUE THREAD

**Issue by 17matejka** [msys2/MINGW-packages#15775]
### Description / Steps to reproduce the issue

Everything should be up to date, but after installing/re-installing pip is not working - see bellow.
Just simple **`pip`** command show error.

### Expected behavior

$ pip

Usage:
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the main subroutine, instead of logging them to stderr.
  --isolated                  Run pip in an isolated mode, ignoring environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment; exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be used up to 3 times (corresponding to WARNING, ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --proxy <proxy>             Specify a proxy in the form scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists: (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted, even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If provided, overrides the default. See 'SSL Certificate Verification' in pip documentation for more information.
  --client-cert <path>        Path to SSL client certificate, a single file containing the private key and the certificate in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine whether a new version of pip is available for download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be removed in the future.

### Actual behavior

$ pip
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip-script.py", line 10, in <module>
    from importlib.metadata import distribution
  File "C:/msys64/mingw64/lib/python3.10/importlib/metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "C:/msys64/mingw64/lib/python3.10/importlib/metadata/_adapters.py", line 3, in <module>
    import email.message
  File "C:/msys64/mingw64/lib/python3.10/email/message.py", line 15, in <module>
    from email import utils
  File "C:/msys64/mingw64/lib/python3.10/email/utils.py", line 29, in <module>
    import socket
  File "C:/msys64/mingw64/lib/python3.10/socket.py", line 51, in <module>
    import _socket
ImportError: DLL load failed while importing _socket: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip-script.py", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip-script.py", line 15, in <module>
    from pkg_resources import load_entry_point
  File "C:/msys64/mingw64/lib/python3.10/site-packages/pkg_resources/__init__.py", line 32, in <module>
    import plistlib
  File "C:/msys64/mingw64/lib/python3.10/plistlib.py", line 61, in <module>
    from xml.parsers.expat import ParserCreate
  File "C:/msys64/mingw64/lib/python3.10/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: DLL load failed while importing pyexpat: The specified module could not be found.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by 17matejka** [comment]
MINGW64 was using my Win10 env PYTHONPATH
```
$ echo $PYTHONPATH
C:\Users\xxx\AppData\Local\Programs\Python\Python39;C:\Users\xxx\AppData\Local\Programs\Python\Python39\Scripts
```
So did custom export

`$ export PYTHONPATH=/c/msys64/mingw64/bin:/c/msys64/mingw64/lib/python3.10/site-packages`
