### ISSUE TITLE
The time is 7 hours difference in msys2 and windows term

### ISSUE THREAD

**Issue by maryjeck** [msys2/MINGW-packages#17850]
windows cmd below

 	C:\Users\xxxxxx>python3
	 Python 3.10.6 (main, Aug 12 2022, 18:00:29)  [GCC 12.1.0 64 bit (AMD64)] on win32
	 Type "help", "copyright", "credits" or "license" for more information.
	 >>> from datetime import datetime
	 >>> datetime.now()
	 datetime.datetime(2022, 9, 12, 11, 21, 4, 285171)
	 >>>

msys2 below

	# xxxxxx @ xxxxxx-computer in ~ [11:19:28]
	$ python3
	Python 3.10.6 (main, Aug 12 2022, 18:00:29)  [GCC 12.1.0 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from datetime import datetime
	>>> datetime.now()
	datetime.datetime(2022, 9, 12, 4, 19, 54, 709405)
	>>>

There is run just in the sametime

what is happed?

**Comment by lazka** [comment]
```
$ python -c "import os; print(os.environ['TZ'])"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys64/ucrt64/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'TZ'
$ winpty python -c "import os; print(os.environ['TZ'])"
Europe/Vienna
```

winpty results in TZ being passed to python, which uses https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-s-localtime32-s-localtime64-s?view=msvc-170 internally and affects the timezone there.

I haven't looked into it, but it seems like cygwin doesn't pass TZ to mingw processes, since the format is different. winpty shouldn't then either.
