### ISSUE TITLE
pip install tries to use VC instead of gcc and fails

### ISSUE THREAD

**Issue by sam-s** [msys2/MINGW-packages#18192]
### Description / Steps to reproduce the issue

using `pacman` I install
* mingw-w64-x86_64-python-3.11.4-5
* mingw-w64-x86_64-python-pip-23.2.1-2
* mingw-w64-x86_64-python-distlib-0.3.7-1 
* mingw-w64-x86_64-python-setuptools-68.0.0-2

However, `pip install` fails with 
```
distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
```
after
```
/mingw64/bin/python -m venv ~/venv/mingw
. ~/venv/mingw/bin/activate
python -m pip install --upgrade pip
pip install numpy
```

The same happens with `ucrt64`.

This is similar to 
* https://github.com/msys2/MINGW-packages/issues/14887
* https://github.com/msys2/MINGW-packages/issues/5155

See also
* [Distutils VC 6.0 Errors When Using mingw-w64 GCC](https://bugs.python.org/issue36539)
* [msys2/mingw64: pip: VC 6.0 is not supported by this module](https://stackoverflow.com/q/52166914/850781)

### Expected behavior

no errors, `numpy` installed

### Actual behavior

```
Looking in indexes: https://artifactory.inf.bloomberg.com/artifactory/api/pypi/bloomberg-pypi/simple
Collecting numpy
  Using cached https://artifactory.inf.bloomberg.com/artifactory/api/pypi/bloomberg-pypi/packages/pa
ckages/a0/41/8f53eff8e969dd8576ddfb45e7ed315407d27c7518ae49418be8ed532b07/numpy-1.25.2.tar.gz (10.8
MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Traceback (most recent call last):
        File "C:/msys64/home/ssteingold/venv/mingw/lib/python3.11/site-packages/pip/_vendor/pyprojec
t_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "C:/msys64/home/ssteingold/venv/mingw/lib/python3.11/site-packages/pip/_vendor/pyprojec
t_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:/msys64/home/ssteingold/venv/mingw/lib/python3.11/site-packages/pip/_vendor/pyprojec
t_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:/msys64/home/ssteingold/venv/mingw/lib/python3.11/site-packages/pip/_vendor/pyprojec
t_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:/msys64/mingw64/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 944, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:/msys64/tmp/pip-build-env-exdhv9qf/overlay/lib/python3.11/site-packages/setuptools/_
_init__.py", line 242, in <module>
          monkey.patch_all()
        File "C:/msys64/tmp/pip-build-env-exdhv9qf/overlay/lib/python3.11/site-packages/setuptools/m
onkey.py", line 99, in patch_all
          patch_for_msvc_specialized_compiler()
        File "C:/msys64/tmp/pip-build-env-exdhv9qf/overlay/lib/python3.11/site-packages/setuptools/m
onkey.py", line 162, in patch_for_msvc_specialized_compiler
          patch_func(*msvc9('find_vcvarsall'))
                      ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:/msys64/tmp/pip-build-env-exdhv9qf/overlay/lib/python3.11/site-packages/setuptools/m
onkey.py", line 149, in patch_params
          mod = import_module(mod_name)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:/msys64/mingw64/lib/python3.11/importlib/__init__.py", line 126, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 944, in exec_module
        File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
        File "C:/msys64/tmp/pip-build-env-exdhv9qf/overlay/lib/python3.11/site-packages/setuptools/_
distutils/msvc9compiler.py", line 295, in <module>
          raise DistutilsPlatformError("VC %0.1f is not supported by this module" % VERSION)
      distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19044

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by Biswa96** [comment]
The mingw python numpy package uses some patches here https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-numpy

**Comment by sam-s** [comment]
When I replace the package `gcc` with `mingw-w64-x86_64-gcc` and set [`SETUPTOOLS_USE_DISTUTILS=stdlib`](https://github.com/pyproj4/pyproj/issues/1009), I get a whole different set of errors:
```
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [2647 lines of output]
.....
        INFO: gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D
_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pipe -Wp,-D_
FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEF
ILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=0 -Inumpy/random -Inumpy/random/src -Inumpy/random/src/mt1993
7 -Inumpy/core/include -Ibuild/src.mingw_x86_64-3.11/numpy/core/include/numpy -Ibuild/src.mingw_x86_
64-3.11/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/s
rc/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inumpy/core/
src/_simd -IC:/msys64/home/ssteingold/venv/mingw/include -IC:/msys64/mingw64/include/python3.11 -Ibu
ild/src.mingw_x86_64-3.11/numpy/core/src/common -Ibuild/src.mingw_x86_64-3.11/numpy/core/src/npymath
 -c numpy/random/src/mt19937/mt19937-jump.c -o build/temp.mingw_x86_64-3.11/numpy/random/src/mt19937
/mt19937-jump.o -U__GNUC_GNU_INLINE__ -std=c99 -msse -msse2 -msse3
        In file included from numpy/random/src/mt19937/mt19937-jump.h:2,
                         from numpy/random/src/mt19937/mt19937-jump.c:1:
        numpy/random/src/mt19937/mt19937.h:27:1: error: multiple storage classes in declaration spec
ifiers
           27 | static inline uint32_t mt19937_next(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:48:1: error: multiple storage classes in declaration spec
ifiers
           48 | static inline uint64_t mt19937_next64(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:52:1: error: multiple storage classes in declaration spec
ifiers
           52 | static inline uint32_t mt19937_next32(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:56:1: error: multiple storage classes in declaration spec
ifiers
           56 | static inline double mt19937_next_double(mt19937_state *state) {
              | ^~~~~~
        In file included from numpy/random/src/mt19937/mt19937.c:1:
        numpy/random/src/mt19937/mt19937.h:27:1: error: multiple storage classes in declaration spec
ifiers
           27 | static inline uint32_t mt19937_next(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:48:1: error: multiple storage classes in declaration spec
ifiers
           48 | static inline uint64_t mt19937_next64(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:52:1: error: multiple storage classes in declaration spec
ifiers
           52 | static inline uint32_t mt19937_next32(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:56:1: error: multiple storage classes in declaration spec
ifiers
           56 | static inline double mt19937_next_double(mt19937_state *state) {
              | ^~~~~~
        In file included from numpy/random/src/mt19937/mt19937-jump.h:3:
        C:/msys64/mingw64/include/stdlib.h:398:3: error: duplicate 'extern'
          398 |   __CRT_INLINE __MINGW_ATTRIB_NORETURN void  __cdecl _Exit(int status)
              |   ^~~~~~~~~~~~
        C:/msys64/mingw64/include/stdlib.h:735:3: error: duplicate 'extern'
          735 |   __MINGW_EXTENSION __CRT_INLINE long long __cdecl llabs(long long _j) { return (_j
>= 0 ? _j : -_j); }
              |   ^~~~~~~~~~~~~~~~~
        In file included from numpy/random/src/mt19937/mt19937-jump.h:3,
                         from numpy/random/src/mt19937/mt19937.c:2:
        C:/msys64/mingw64/include/stdlib.h:398:3: error: duplicate 'extern'
          398 |   __CRT_INLINE __MINGW_ATTRIB_NORETURN void  __cdecl _Exit(int status)
              |   ^~~~~~~~~~~~
        C:/msys64/mingw64/include/stdlib.h:735:3: error: duplicate 'extern'
          735 |   __MINGW_EXTENSION __CRT_INLINE long long __cdecl llabs(long long _j) { return (_j
>= 0 ? _j : -_j); }
              |   ^~~~~~~~~~~~~~~~~
        numpy/random/src/mt19937/mt19937.c:100:1: error: duplicate 'extern'
          100 | extern inline uint64_t mt19937_next64(mt19937_state *state);
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.c:102:1: error: duplicate 'extern'
          102 | extern inline uint32_t mt19937_next32(mt19937_state *state);
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.c:104:1: error: duplicate 'extern'
          104 | extern inline double mt19937_next_double(mt19937_state *state);
              | ^~~~~~
        In file included from numpy/random/_mt19937.c:762:
        numpy/random/src/mt19937/mt19937.h:27:1: error: multiple storage classes in declaration spec
ifiers
           27 | static inline uint32_t mt19937_next(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:48:1: error: multiple storage classes in declaration spec
ifiers
           48 | static inline uint64_t mt19937_next64(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:52:1: error: multiple storage classes in declaration spec
ifiers
           52 | static inline uint32_t mt19937_next32(mt19937_state *state) {
              | ^~~~~~
        numpy/random/src/mt19937/mt19937.h:56:1: error: multiple storage classes in declaration spec
ifiers
           56 | static inline double mt19937_next_double(mt19937_state *state) {
              | ^~~~~~
        In file included from numpy/random/_mt19937.c:7877:
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:72:1: error: multiple storage c
lasses in declaration specifiers
           72 | static inline PyObject **_PyFrame_Stackbase(_PyInterpreterFrame *f) {
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:76:1: error: multiple storage c
lasses in declaration specifiers
           76 | static inline PyObject *_PyFrame_StackPeek(_PyInterpreterFrame *f) {
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:82:1: error: multiple storage c
lasses in declaration specifiers
           82 | static inline PyObject *_PyFrame_StackPop(_PyInterpreterFrame *f) {
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:88:1: error: multiple storage c
lasses in declaration specifiers
           88 | static inline void _PyFrame_StackPush(_PyInterpreterFrame *f, PyObject *value) {
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:101:1: error: multiple storage
classes in declaration specifiers
          101 | static inline void
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:121:1: error: multiple storage
classes in declaration specifiers
          121 | static inline PyObject**
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:127:1: error: multiple storage
classes in declaration specifiers
          127 | static inline PyObject**
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:133:1: error: multiple storage
classes in declaration specifiers
          133 | static inline void
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:147:1: error: multiple storage
classes in declaration specifiers
          147 | static inline bool
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:162:1: error: multiple storage
classes in declaration specifiers
          162 | static inline PyFrameObject *
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:198:1: error: multiple storage
classes in declaration specifiers
          198 | static inline bool
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:210:1: error: multiple storage
classes in declaration specifiers
          210 | static inline _PyInterpreterFrame *
              | ^~~~~~
        C:/msys64/mingw64/include/python3.11/internal/pycore_frame.h:229:1: error: multiple storage
classes in declaration specifiers
          229 | static inline
              | ^~~~~~
        error: Command "gcc -DNDEBUG -g -fwrapv -O3 -Wall -march=nocona -msahf -mtune=generic -O2 -p
ipe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -march=nocona -msahf -mtune=generic -O2 -pi
pe -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong -O3 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1
 -D_LARGEFILE64_SOURCE=1 -DNPY_NO_DEPRECATED_API=0 -Inumpy/random -Inumpy/random/src -Inumpy/random/
src/mt19937 -Inumpy/core/include -Ibuild/src.mingw_x86_64-3.11/numpy/core/include/numpy -Ibuild/src.
mingw_x86_64-3.11/numpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inu
mpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -In
umpy/core/src/_simd -IC:/msys64/home/ssteingold/venv/mingw/include -IC:/msys64/mingw64/include/pytho
n3.11 -Ibuild/src.mingw_x86_64-3.11/numpy/core/src/common -Ibuild/src.mingw_x86_64-3.11/numpy/core/s
rc/npymath -c numpy/random/_mt19937.c -o build/temp.mingw_x86_64-3.11/numpy/random/_mt19937.o -U__GN
UC_GNU_INLINE__ -std=c99 -msse -msse2 -msse3" failed with exit status 1
...
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based pro
jects
      [end of output]

```

**Comment by Rybec** [comment]
Similar problems here.  Completely fresh MSYS2 install, freshly installed MINGW tools.  Using MSYS2 MINGW64 environment.

Originally, it was complaining about `--plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')`, so I tried the above mentioned `SETUPTOOLS_USE_DISTUTILS=stdlib` suggestion.  The error changed to ` FileNotFoundError: [WinError 2] The system cannot find the file specified`, and now it gives that same error even without the environment variable line.


Following is the full output without setting the environment variable.  (I double checked to make sure it was unset.)  It appears to be identical to the output when it is set though.

```
Collecting cascadetoml (from -r requirements-dev.txt (line 2))
  Using cached cascadetoml-0.3.3-py2.py3-none-any.whl (7.2 kB)
Requirement already satisfied: jinja2 in c:/msys64/mingw64/lib/python3.10/site-packages (from -r requirements-dev.txt (line 3)) (3.1.2)
Collecting typer (from -r requirements-dev.txt (line 4))
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
Collecting sh (from -r requirements-dev.txt (line 6))
  Using cached sh-2.0.6-py3-none-any.whl (38 kB)
Requirement already satisfied: click in c:/msys64/mingw64/lib/python3.10/site-packages (from -r requirements-dev.txt (line 7)) (8.1.7)
Collecting cpp-coveralls (from -r requirements-dev.txt (line 8))
  Using cached cpp-coveralls-0.4.2.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in c:/msys64/mingw64/lib/python3.10/site-packages (from -r requirements-dev.txt (line 10)) (2.31.0)
Collecting requests-cache (from -r requirements-dev.txt (line 11))
  Using cached requests_cache-1.1.0-py3-none-any.whl (60 kB)
Collecting polib (from -r requirements-dev.txt (line 14))
  Using cached polib-1.2.0-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: black in c:/msys64/mingw64/lib/python3.10/site-packages (from -r requirements-dev.txt (line 17)) (23.7.0)
Requirement already satisfied: pyyaml in c:/msys64/mingw64/lib/python3.10/site-packages (from -r requirements-dev.txt (line 18)) (6.0.1)
Collecting pre-commit (from -r requirements-dev.txt (line 19))
  Using cached pre_commit-3.3.3-py2.py3-none-any.whl (202 kB)
Collecting intelhex (from -r requirements-dev.txt (line 22))
  Using cached intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Collecting pyelftools (from -r requirements-dev.txt (line 25))
  Using cached pyelftools-0.29-py2.py3-none-any.whl (174 kB)
Collecting cryptography (from -r requirements-dev.txt (line 28))
  Using cached cryptography-41.0.3.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      Collecting setuptools>=61.0.0
        Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
      Collecting wheel
        Using cached wheel-0.41.1-py3-none-any.whl (64 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'error'
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [28 lines of output]
        C:/msys64/tmp/pip-install-h1ggc48b/cffi_0b0486f2ae6749ae8cc57bab215c0d32/setup.py:69: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
          from distutils.sysconfig import get_config_vars
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "C:/msys64/tmp/pip-install-h1ggc48b/cffi_0b0486f2ae6749ae8cc57bab215c0d32/setup.py", line 126, in <module>
            if sys.platform == "win32" and uses_msvc():
          File "C:/msys64/tmp/pip-install-h1ggc48b/cffi_0b0486f2ae6749ae8cc57bab215c0d32/setup.py", line 105, in uses_msvc
            return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
          File "C:/msys64/mingw64/lib/python3.10/distutils/command/config.py", line 223, in try_compile
            self._check_compiler()
          File "C:/msys64/mingw64/lib/python3.10/distutils/command/config.py", line 97, in _check_compiler
            self.compiler = new_compiler(compiler=self.compiler,
          File "C:/msys64/mingw64/lib/python3.10/distutils/ccompiler.py", line 1034, in new_compiler
            return klass(None, dry_run, force)
          File "C:/msys64/mingw64/lib/python3.10/distutils/cygwinccompiler.py", line 285, in __init__
            if is_cygwincc(self.cc):
          File "C:/msys64/mingw64/lib/python3.10/distutils/cygwinccompiler.py", line 364, in is_cygwincc
            out_string = check_output(shlex.split(cc) + ['-dumpmachine'])
          File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 421, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 503, in run
            with Popen(*popenargs, **kwargs) as process:
          File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 971, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "C:/msys64/mingw64/lib/python3.10/subprocess.py", line 1456, in _execute_child
            hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
        FileNotFoundError: [WinError 2] The system cannot find the file specified
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Rybec** [comment]
I added a print line to subprocess.py, and here's the results:

```
Executable:  None
Args:  gcc -dumpmachine
```

Tracked it down.  GCC wasn't installed in the MINGW environment specifically.  My particular case wasn't a bug with the software.  It's a bug with the _setup documentation,_ which gives instructions for installing the ucrt version of GCC but doesn't say _anything at all_ about environments or the fact that the ucrt compiler is not available in the MINGW terminal.

Maybe someone should make a new issue for this documentation bug.  I'm not going to.  I've already wasted an hour and a half trying to figure something out that someone just neglected to mention in the initial setup documentation.  (I've been using MSYS2 for years.  I don't know when this change to "environments" happened, but it's pretty dumb when such a massive change isn't mentioned on the front page, so that existing users who have plenty of experience know that it no longer works the way they've come to expect.)

**Comment by Biswa96** [comment]
>  doesn't say anything at all about environments

Those are already documented here https://www.msys2.org/docs/environments/

**Comment by Rybec** [comment]
[https://www.msys2.org/](https://www.msys2.org/)

No, no it doesn't, and posting a link to a random piece of documentation many pages deep doesn't magically change that.  As a long time, experienced user, I didn't _expect_ that I needed to go deep into the documentation to relearn how to use it, because _the page where that information belongs_ didn't mention that there were _massive changes._

You might have noticed I wrote:

> I've already wasted an hour and a half trying to figure something out that someone just neglected to mention in the **initial setup documentation.**

I went there to download software _I thought I was already familiar with._  It didn't say _anything_ to suggest that I needed to approach it extremely differently from how I did in the past.

Now I see why one of the top rules of Linus Torvalds is "Don't break userspace".  Honestly, such massive changes probably warranted a major version change.  This should really be MSYS3.  At least that way experienced users would know to expect something different, instead of feeling alienated.

**Comment by lazka** [comment]
@Rybec we've had different environments since the beginning, so for 10 years now.

For numpy I'd wait for the next release which moves away from their custom setuptools based build system to meson. If we can manage to upstream build fixes and get rid of all our patches, pip installation should work.

**Comment by lazka** [comment]
> Back to topic: For numpy I'd wait for the next release which moves away from their custom distutils/setuptools based build system to meson (see the recent beta for details: https://github.com/numpy/numpy/releases/tag/v1.26.0b1). If we can manage to upstream build fixes and get rid of all our patches, pip installation should work.

This has happened now in main https://github.com/numpy/numpy/pull/24968#issuecomment-1793780083 Maybe it will be back ported to 1.26, we'll have to wait.

> If anyone wants to help, moving our numpy package to meson using v1.26.0b1 would be a start.

This happened in #18900
