### ISSUE TITLE
gyp: AttributeError: module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#18650]
### Description / Steps to reproduce the issue

Run:
`gyp`
in any of the environments including MSYS2

### Expected behavior

gyp runs

### Actual behavior

```
$ gyp verison
Traceback (most recent call last):
  File "/usr/bin/gyp", line 5, in <module>
    from gyp import script_main
  File "/usr/lib/python3.11/site-packages/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/lib/python3.11/site-packages/gyp/input.py", line 8, in <module>
    import gyp.common
  File "/usr/lib/python3.11/site-packages/gyp/common.py", line 497, in <module>
    class OrderedSet(collections.MutableSet):
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'MutableSet'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

### MINGW environments affected

- [X] MINGW64
- [X] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANG32
- [X] CLANGARM64

### Are you willing to submit a PR?

yes

**Comment by hmartinez82** [comment]
Closing since this is a MSYS2 issue
