### ISSUE TITLE
[python] 

### ISSUE THREAD

**Issue by jdpipe** [msys2/MINGW-packages#18984]
### Description / Steps to reproduce the issue

hi all, I have a curly problem with Python on MSYS2, which is giving me DLL hell when embedding Python in a C program. here is a minimal example:

```
#include <stdio.h>
#include <Python.h>

int main(void) {
    PyConfig config;
    PyConfig_InitIsolatedConfig(&config);

    PyStatus status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status)) {
        Py_ExitStatusException(status);
        exit(1);  // Exit if initialization failed
    }

    PyObject *sys_module = PyImport_ImportModule("sys");
    PyObject *sys_path = PyObject_GetAttrString(sys_module, "path");
    
    if (PyList_Check(sys_path)) {
        Py_ssize_t len = PyList_Size(sys_path);
        for (Py_ssize_t i = 0; i < len; i++) {
            PyObject *item = PyList_GetItem(sys_path, i);
            if (PyUnicode_Check(item)) {
                const char* path_str = PyUnicode_AsUTF8(item);
                printf("SYS.PATH[%zd]: %s\n", i, path_str);
            }
        }
    }
    
    Py_DECREF(sys_path);
    Py_DECREF(sys_module);

    Py_Finalize();

    return 0;
}
```

which gives the output:
```
john@windo MINGW64 ~
$ gcc pyembed.c -o pyembed `python-config --embed --libs --cflags`

john@windo MINGW64 ~
$ ./pyembed.exe
SYS.PATH[0]: C:/msys64/mingw64/lib/python311.zip
SYS.PATH[1]: C:/msys64/mingw64/lib/python3.11
SYS.PATH[2]: D:/a/msys64/mingw64/lib/python3.11/lib-dynload
SYS.PATH[3]: C:/msys64/mingw64/lib/python3.11/site-packages
```

As you can see `SYS.PATH[2]` references a non-existent path that I believe relates to the MSYS2 build system. Is that right? Looks like a bug?

### Expected behavior

I would expect all reported paths on C

### Actual behavior

One sys.path entry comes out on D:, which is a non-existent drive on my system. I believe this is an artifact of the MSYS2 build system.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

i'm not sure where to start!

**Comment by jdpipe** [comment]
i also posted here: https://discord.com/channels/792780131906617355/792780132398006315/1168061777699946556

**Comment by jdpipe** [comment]
here is an expanded example that shows why this is a problem:

```
#include <stdio.h>
#include <Python.h>

int main(void) {
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);

	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);  // Exit if initialization failed
	}

	PyObject *sys_module = PyImport_ImportModule("sys");
	PyObject *sys_path = PyObject_GetAttrString(sys_module, "path");

	if (PyList_Check(sys_path)) {
		Py_ssize_t len = PyList_Size(sys_path);
		for (Py_ssize_t i = 0; i < len; i++) {
			PyObject *item = PyList_GetItem(sys_path, i);
			if (PyUnicode_Check(item)) {
				const char* path_str = PyUnicode_AsUTF8(item);
				printf("SYS.PATH[%zd]: %s\n", i, path_str);
			}
		}
	}

	// let's import 'ctypes'
	const char *importname = "ctypes";
	PyObject *pName = PyUnicode_FromString(importname);
	PyObject *pModule = PyImport_Import(pName);

	if(!pModule){
		if(PyErr_Occurred())PyErr_Print();
		fprintf(stderr, "Failed to load \"%s\"\n", importname);
	}

	Py_DECREF(pName);
	Py_DECREF(pModule);
	Py_DECREF(sys_path);
	Py_DECREF(sys_module);

	Py_Finalize();

	return 0;
}
// vim: ts=4:sw=4:tw=80:noet
```

which gives

```
john@windo MINGW64 ~
$ gcc pyembed.c -o pyembed `python-config --embed --libs --cflags`

john@windo MINGW64 ~
$ ./pyembed.exe
SYS.PATH[0]: C:/msys64/mingw64/lib/python311.zip
SYS.PATH[1]: C:/msys64/mingw64/lib/python3.11
SYS.PATH[2]: D:/a/msys64/mingw64/lib/python3.11/lib-dynload
SYS.PATH[3]: C:/msys64/mingw64/lib/python3.11/site-packages
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
Failed to load "ctypes"
Segmentation fault
```

Even if one manually forces the required lib-dynload directory into sys.path[1] by setting it explicitly, you still then get a DLL loading error.

Same issues occur eg with `binascii`, which is a external module with no Python proxy module.

**Comment by jdpipe** [comment]
Further testing on MSYS2. If I configure embedded Python as follows:
```
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.platlibdir = L"c:\\msys64\\mingw64\\lib";

	PyStatus status = Py_InitializeFromConfig(&config);
```
then I get this output:
```
john@windo MINGW64 ~
$ gcc pyembed.c -o pyembed `python-config --embed --libs --cflags` && ./pyembed.exe
SYS.PATH[0]: c:/msys64/mingw64/lib/python311.zip
SYS.PATH[1]: c:/msys64/mingw64/lib/python3.11
SYS.PATH[2]: c:/msys64/mingw64/lib/python3.11/lib-dynload
SYS.PATH[3]: c:/msys64/mingw64/lib/python3.11/site-packages
Traceback (most recent call last):
  File "c:/msys64/mingw64/lib/python3.11/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
Failed to load "ctypes"
Segmentation fault
```

Note that setting `platlibdir` has correctedd the `sys.path[2]` issue, and it is now an `ImportError` rather than `ModuleNotFoundError`.

**Comment by lazka** [comment]
just curious, does the last error go away if you set `PYTHONLEGACYWINDOWSDLLLOADING=1`?

**Comment by jdpipe** [comment]
> just curious, does the last error go away if you set `PYTHONLEGACYWINDOWSDLLLOADING=1`?

Yes, it does work! Here is an updated minimal example.

```
#include <stdio.h>
#include <Python.h>
#include <stdlib.h>

int main(void) {
	int retcode = -1;
#if 0
	// this arrangement works, but is not using 'isolated' config
	putenv("PYTHONLEGACYWINDOWSDLLLOADING=1");
	Py_SetPythonHome(L"c:\\msys64\\mingw64");
	Py_Initialize();
#else
	//this arrangement works
	putenv("PYTHONLEGACYWINDOWSDLLLOADING=1");
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.platlibdir = L"c:\\msys64\\mingw64\\lib";
	config.dev_mode = 1;
	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);  // Exit if initialization failed
	}
#endif

	PyObject *sys_module = PyImport_ImportModule("sys");
	PyObject *sys_path = PyObject_GetAttrString(sys_module, "path");

	if (PyList_Check(sys_path)) {
		Py_ssize_t len = PyList_Size(sys_path);
		for (Py_ssize_t i = 0; i < len; i++) {
			PyObject *item = PyList_GetItem(sys_path, i);
			if (PyUnicode_Check(item)) {
				const char* path_str = PyUnicode_AsUTF8(item);
				printf("SYS.PATH[%zd]: %s\n", i, path_str);
			}
		}
		printf("ENV PATH: %s\n",getenv("PATH"));
	}

	// let's import 'ctypes'
	const char *importname = "binascii";
	PyObject *pName = PyUnicode_FromString(importname);
	PyObject *pModule = PyImport_Import(pName);
	Py_DECREF(pName);

	if(!pModule){
		if(PyErr_Occurred())PyErr_Print();
		fprintf(stderr, "FAILED TO LOAD \"%s\"\n", importname);
		goto cleanup;
	}

	fprintf(stderr,"SUCCESS! LOADED \"%s\"\n",importname);
	retcode = 0;
	Py_DECREF(pModule);
cleanup:
	Py_DECREF(sys_path);
	Py_DECREF(sys_module);

	Py_Finalize();
	return retcode;
}
// vim: ts=4:sw=4:tw=80:noet
```

**Comment by lazka** [comment]
> Yes, it does work! Here is an updated minimal example.

OK, thanks, then `AddDllDirectoryW(L"c:\\msys64\\mingw64\\bin")` should also work instead of PYTHONLEGACYWINDOWSDLLLOADING.

**Comment by jdpipe** [comment]
@lazka I tried `AddDllDirectoryW`, but it was not available in `<windows.h>` so I reverted to `AddDllDirectory`.  I found that I still need to set `config.platlibdir` as well, so that seems to me to be a bug. It strikes me that whenever Py_Initialize does its thing with `platlibdir`, it should be making calls to `AddDllDirectory` automatically.
FYI in this application it is not an option to move the binary to `/bin`, since it's actually a DLL and needs to be located in the OpenModelica search path for our application (namely calling from a Modelica model out to a Python function).

Updated not-so-minimal example:
```c
#include <stdio.h>
#include <Python.h>
#include <stdlib.h>
#include <windows.h>

int main(void) {
	int retcode = -1;
#if 0
	// this arrangement works, but is not using 'isolated' config
	putenv("PYTHONLEGACYWINDOWSDLLLOADING=1");
	Py_SetPythonHome(L"c:\\msys64\\mingw64");
	Py_Initialize();
#elseif 0
	//this arrangement works
	putenv("PYTHONLEGACYWINDOWSDLLLOADING=1");
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.platlibdir = L"c:\\msys64\\mingw64\\bin";
	config.dev_mode = 1;
	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);
	}
#elseif 0
	// this arrangement also works, but it requires TWO hardcoded paths
	AddDllDirectory(L"c:\\msys64\\mingw64\\bin");
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.platlibdir = L"c:\\msys64\\mingw64\\lib";
	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);
	}	
#elseif 0
	// this arrangement works, and is simple, but reflects a bug which is that
	// 
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.home = L"c:\\msys64\\mingw64";
	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);
	}	
#else
	// this arrangement works, but depends on an env var. would fail if
	// running from outside MSYS2 prompt. however, we can use a different env 
	// var of our own here, which could be set at install time.
	PyConfig config;
	PyConfig_InitIsolatedConfig(&config);
	config.home = _wgetenv(L"MSYSTEM_PREFIX");
	PyStatus status = Py_InitializeFromConfig(&config);
	if (PyStatus_Exception(status)) {
		Py_ExitStatusException(status);
		exit(1);
	}	
#endif

	PyObject *sys_module = PyImport_ImportModule("sys");
	PyObject *sys_path = PyObject_GetAttrString(sys_module, "path");

	if (PyList_Check(sys_path)) {
		Py_ssize_t len = PyList_Size(sys_path);
		for (Py_ssize_t i = 0; i < len; i++) {
			PyObject *item = PyList_GetItem(sys_path, i);
			if (PyUnicode_Check(item)) {
				const char* path_str = PyUnicode_AsUTF8(item);
				printf("SYS.PATH[%zd]: %s\n", i, path_str);
			}
		}
		printf("ENV PATH: %s\n",getenv("PATH"));
	}

	// let's import something with a .pyd dependency in lib-dynaload:
	const char *importname = "numpy";
	PyObject *pName = PyUnicode_FromString(importname);
	AddDllDirectory(L"c:\\msys64\\mingw64\\bin");
	PyObject *pModule = PyImport_Import(pName);
	Py_DECREF(pName);

	if(!pModule){
		if(PyErr_Occurred())PyErr_Print();
		fprintf(stderr, "FAILED TO LOAD \"%s\"\n", importname);
		goto cleanup;
	}

	fprintf(stderr,"SUCCESS! LOADED \"%s\"\n",importname);
	retcode = 0;
	Py_DECREF(pModule);
cleanup:
	Py_DECREF(sys_path);
	Py_DECREF(sys_module);

	Py_Finalize();
	return retcode;
}
// vim: ts=4:sw=4:tw=80:noet
```

**Comment by lazka** [comment]
> @lazka I tried `AddDllDirectoryW`, but it was not available in `<windows.h>` so I reverted to `AddDllDirectory`. I found that I still need to set `config.platlibdir` as well, so that seems to me to be a bug. It strikes me that whenever Py_Initialize does its thing with `platlibdir`, it should be making calls to `AddDllDirectory` automatically.

Yeah, upstream CPython avoids this by putting all .pyd files and DLLs it uses in the same directory

```
$ pwd
/c/Python311/DLLs
$ tree .
.
├── _asyncio.pyd
├── _bz2.pyd
├── _ctypes.pyd
├── _ctypes_test.pyd
├── _decimal.pyd
├── _elementtree.pyd
├── _hashlib.pyd
├── _lzma.pyd
├── _msi.pyd
├── _multiprocessing.pyd
├── _overlapped.pyd
├── _queue.pyd
├── _socket.pyd
├── _sqlite3.pyd
├── _ssl.pyd
├── _testbuffer.pyd
├── _testcapi.pyd
├── _testconsole.pyd
├── _testimportmultiple.pyd
├── _testinternalcapi.pyd
├── _testmultiphase.pyd
├── _tkinter.pyd
├── _uuid.pyd
├── _zoneinfo.pyd
├── libcrypto-1_1.dll
├── libffi-8.dll
├── libssl-1_1.dll
├── py.ico
├── pyc.ico
├── pyd.ico
├── pyexpat.pyd
├── python_lib.cat
├── python_tools.cat
├── select.pyd
├── sqlite3.dll
├── tcl86t.dll
├── tk86t.dll
├── unicodedata.pyd
└── winsound.pyd

1 directory, 39 files
```

> FYI in this application it is not an option to move the binary to `/bin`, since it's actually a DLL and needs to be located in the OpenModelica search path for our application (namely calling from a Modelica model out to a Python function).

I see, good to know.

**Comment by jdpipe** [comment]
not sure if this is also relevant...?
https://github.com/msys2-contrib/cpython-mingw/issues/48

**Comment by jdpipe** [comment]
@lazka I tried with the AddDllDirectory approach, and it worked when importing using `PyImport_Import` from C, but I believe it did not work when I dropped down to to Python and attempted to `import` from Python. I solved this by using C API calls equivalent to the Python `os.add_dll_directory(bindir)` where bindir is `c:\msys64\mingw64\bin`.

I also realised that my attempts at an 'isolated' mode Python was incorrect anyway, because environment variables are needed to detect a user's use of virtualenv and custom install paths like `~/.local/lib`. But this `add _dll_directory` issue exists whether using isolated or `python` configuration.

I would maintain that MSYS2 Python needs, by default, to do this `add_dll_directory` automatically itself, at least for the package's own directories and especially for `c:\msys64\mingw64\bin` (or whatever it is on the current `$MSYSTEM`) and that this is definitely a bug in the current Python package. As noted here (https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew), system directories should not have to be explicitly added.

**Comment by StanleyWu8787** [comment]
Same problem in mingw32
See https://discuss.python.org/t/importerror-dll-load-failed-while-importing-ctypes/64495
