### ISSUE TITLE
node-pty dioes not compile

### ISSUE THREAD

**Issue by Zibri** [msys2/MINGW-packages#19009]
### Description / Steps to reproduce the issue

npm install node-pty

### Expected behavior

it should download compile and install

### Actual behavior

compilation fails on MSYS2 on windows.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

latest

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [ ] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

**Comment by brisingraerowing** [comment]
Having the terminal output would likely be useful.

**Comment by revelator** [comment]
might need a port first, node had to hacked pretty brutally to even work with msys2 in the first place so not all packages are expected to build out of the box.

**Comment by Zibri** [comment]
Windows native:
```
D:\>mkdir test

D:\>cd test

D:\test>rem Windows Latest native on github actions

D:\test>npm install node-pty

added 2 packages in 36s

D:\test>

```
MSYS2:
```
curl -L 'https://github.com/msys2/msys2-installer/releases/download/2023-10-26/msys2-base-x86_64-20231026.sfx.exe' -o msys2.exe
msys2_shell.cmd -defterm -here -no-start
```
Then in MSYS2/MINGW64:

```
pacman -Suy
pacman -Syu mingw-w64-x86_64-nodejs
pacman -Suy  base-devel gcc vim cmake development
mkdir test
cd test
npm init
npm install node-pty
```

result:
```
npm ERR! make: Entering directory '/test/node_modules/node-pty/build'
npm ERR!   CXX(target) Release/obj.target/conpty/src/win/conpty.o
npm ERR! make: Leaving directory '/test/node_modules/node-pty/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.17.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.7 found at "D:/test/msys64/mingw64/bin/python3.exe"
npm ERR! gyp info spawn D:/test/msys64/mingw64/bin/python3.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\test\\msys64\\test\\node_modules\\node-pty\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\test\\msys64\\mingw64\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=D:\\test\\msys64\\mingw64',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=D:\\test\\msys64\\mingw64\\lib\\libnode.dll.a',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\test\\msys64\\test\\node_modules\\node-pty',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/win/conpty.cc:24:
npm ERR! /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfWorkerA(STRSAFE_LPSTR, size_t, STRSAFE_LPCSTR, va_list)’:
npm ERR! /usr/include/w32api/strsafe.h:1555:12: error: ‘_vsnprintf’ was not declared in this scope
npm ERR!  1555 |     iRet = _vsnprintf(pszDest,cchMax,pszFormat,argList);
npm ERR!       |            ^~~~~~~~~~
npm ERR! /usr/include/w32api/strsafe.h:1555:12: note: the macro ‘_vsnprintf’ had not yet been defined
npm ERR! /usr/include/w32api/strsafe.h:1961: note: it was later defined here
npm ERR!  1961 | #define _vsnprintf _vsnprintf_instead_use_StringCbVPrintfA_or_StringCchVPrintfA;
npm ERR!       |
npm ERR! /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfWorkerW(STRSAFE_LPWSTR, size_t, STRSAFE_LPCWSTR, va_list)’:
npm ERR! /usr/include/w32api/strsafe.h:1575:12: error: ‘_vsnwprintf’ was not declared in this scope
npm ERR!  1575 |     iRet = _vsnwprintf(pszDest,cchMax,pszFormat,argList);
npm ERR!       |            ^~~~~~~~~~~
npm ERR! /usr/include/w32api/strsafe.h:1575:12: note: the macro ‘_vsnwprintf’ had not yet been defined
npm ERR! /usr/include/w32api/strsafe.h:1964: note: it was later defined here
npm ERR!  1964 | #define _vsnwprintf _vsnwprintf_instead_use_StringCbVPrintfW_or_StringCchVPrintfW;
npm ERR!       |
npm ERR! /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfExWorkerA(STRSAFE_LPSTR, size_t, size_t, char**, size_t*, unsigned int, STRSAFE_LPCSTR, va_list)’:
npm ERR! /usr/include/w32api/strsafe.h:1612:16: error: ‘_vsnprintf’ was not declared in this scope
npm ERR!  1612 |         iRet = _vsnprintf(pszDest,cchMax,pszFormat,argList);
npm ERR!       |                ^~~~~~~~~~
npm ERR! /usr/include/w32api/strsafe.h:1612:16: note: the macro ‘_vsnprintf’ had not yet been defined
npm ERR! /usr/include/w32api/strsafe.h:1961: note: it was later defined here
npm ERR!  1961 | #define _vsnprintf _vsnprintf_instead_use_StringCbVPrintfA_or_StringCchVPrintfA;
npm ERR!       |
npm ERR! /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfExWorkerW(STRSAFE_LPWSTR, size_t, size_t, wchar_t**, size_t*, unsigned int, STRSAFE_LPCWSTR, va_list)’:
npm ERR! /usr/include/w32api/strsafe.h:1685:16: error: ‘_vsnwprintf’ was not declared in this scope
npm ERR!  1685 |         iRet = _vsnwprintf(pszDest,cchMax,pszFormat,argList);
npm ERR!       |                ^~~~~~~~~~~
npm ERR! /usr/include/w32api/strsafe.h:1685:16: note: the macro ‘_vsnwprintf’ had not yet been defined
npm ERR! /usr/include/w32api/strsafe.h:1964: note: it was later defined here
npm ERR!  1964 | #define _vsnwprintf _vsnwprintf_instead_use_StringCbVPrintfW_or_StringCchVPrintfW;
npm ERR!       |
npm ERR! make: *** [conpty.target.mk:93: Release/obj.target/conpty/src/win/conpty.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (D:\test\msys64\mingw64\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System MINGW32_NT-10.0 10.0.20348
npm ERR! gyp ERR! command "D:\\test\\msys64\\mingw64\\bin\\node.exe" "D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\test\msys64\test\node_modules\node-pty
npm ERR! gyp ERR! node -v v18.17.1
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\npm\cache\_logs\2023-12-09T17_40_46_193Z-debug-0.log
```

full debug log:

```
# cat "C:\npm\cache\_logs\2023-12-09T17_40_46_193Z-debug-0.log"
0 verbose cli D:\test\msys64\mingw64\bin\node.exe D:\test\msys64\mingw64\lib\node_modules\npm\bin\npm-cli.js
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:D:\test\msys64\mingw64\lib\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\test\msys64\test\.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:C:\Users\runneradmin\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\npm\prefix\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm install node-pty
21 verbose argv "install" "node-pty"
22 timing npm:load:setTitle Completed in 1ms
23 timing config:load:flatten Completed in 2ms
24 timing npm:load:display Completed in 4ms
25 verbose logfile logs-max:10 dir:C:\npm\cache\_logs\2023-12-09T17_40_46_193Z-
26 verbose logfile C:\npm\cache\_logs\2023-12-09T17_40_46_193Z-debug-0.log
27 timing npm:load:logFile Completed in 8ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 24ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile start cleaning logs, removing 2 files
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 12ms
36 timing idealTree:userRequests Completed in 3ms
37 silly idealTree buildDeps
38 silly fetch manifest node-pty@*
39 http fetch GET 200 https://registry.npmjs.org/node-pty 14ms (cache hit)
40 silly placeDep ROOT node-pty@1.0.0 OK for: test@1.0.0 want: *
41 silly fetch manifest nan@^2.17.0
42 http fetch GET 200 https://registry.npmjs.org/nan 4ms (cache hit)
43 timing idealTree:#root Completed in 29ms
44 silly placeDep ROOT nan@2.18.0 OK for: node-pty@1.0.0 want: ^2.17.0
45 timing idealTree:node_modules/node-pty Completed in 3ms
46 timing idealTree:node_modules/nan Completed in 0ms
47 timing idealTree:buildDeps Completed in 33ms
48 timing idealTree:fixDepFlags Completed in 0ms
49 timing idealTree Completed in 49ms
50 timing reify:loadTrees Completed in 49ms
51 timing reify:diffTrees Completed in 0ms
52 silly reify moves {}
53 timing reify:retireShallow Completed in 1ms
54 timing reify:createSparse Completed in 1ms
55 timing reify:loadBundles Completed in 0ms
56 silly audit bulk request { 'node-pty': [ '1.0.0' ], nan: [ '2.18.0' ] }
57 timing reifyNode:node_modules/nan Completed in 104ms
58 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 159ms
59 timing auditReport:getReport Completed in 161ms
60 silly audit report {}
61 timing auditReport:init Completed in 0ms
62 timing reify:audit Completed in 161ms
63 timing reifyNode:node_modules/node-pty Completed in 258ms
64 timing reify:unpack Completed in 259ms
65 timing reify:unretire Completed in 0ms
66 timing build:queue Completed in 0ms
67 info run node-pty@1.0.0 install node_modules/node-pty node-gyp rebuild
68 info run node-pty@1.0.0 install { code: 1, signal: null }
69 warn cleanup Failed to remove some directories [
69 warn cleanup   [
69 warn cleanup     'D:\\test\\msys64\\test\\node_modules\\node-pty',
69 warn cleanup     [Error: EPERM: operation not permitted, rmdir 'D:\test\msys64\test\node_modules\node-pty\build\Release\obj.target\conpty'] {
69 warn cleanup       errno: -4048,
69 warn cleanup       code: 'EPERM',
69 warn cleanup       syscall: 'rmdir',
69 warn cleanup       path: 'D:\\test\\msys64\\test\\node_modules\\node-pty\\build\\Release\\obj.target\\conpty'
69 warn cleanup     }
69 warn cleanup   ]
69 warn cleanup ]
70 timing reify:rollback:createSparse Completed in 35ms
71 timing reify:rollback:retireShallow Completed in 0ms
72 timing command:install Completed in 3731ms
73 verbose stack Error: command failed
73 verbose stack     at ChildProcess.<anonymous> (D:\test\msys64\mingw64\lib\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:53:27)
73 verbose stack     at ChildProcess.emit (node:events:514:28)
73 verbose stack     at maybeClose (node:internal/child_process:1091:16)
73 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
74 verbose pkgid node-pty@1.0.0
75 verbose cwd D:\test\msys64\test
76 verbose MINGW32_NT-10.0 10.0.20348
77 verbose node v18.17.1
78 verbose npm  v9.6.7
79 error code 1
80 error path D:\test\msys64\test\node_modules\node-pty
81 error command failed
82 error command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
83 error make: Entering directory '/test/node_modules/node-pty/build'
83 error   CXX(target) Release/obj.target/conpty/src/win/conpty.o
83 error make: Leaving directory '/test/node_modules/node-pty/build'
84 error gyp info it worked if it ends with ok
84 error gyp info using node-gyp@9.3.1
84 error gyp info using node@18.17.1 | win32 | x64
84 error gyp info find Python using Python version 3.11.7 found at "D:/test/msys64/mingw64/bin/python3.exe"
84 error gyp info spawn D:/test/msys64/mingw64/bin/python3.exe
84 error gyp info spawn args [
84 error gyp info spawn args   'D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
84 error gyp info spawn args   'binding.gyp',
84 error gyp info spawn args   '-f',
84 error gyp info spawn args   'make',
84 error gyp info spawn args   '-I',
84 error gyp info spawn args   'D:\\test\\msys64\\test\\node_modules\\node-pty\\build\\config.gypi',
84 error gyp info spawn args   '-I',
84 error gyp info spawn args   'D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
84 error gyp info spawn args   '-I',
84 error gyp info spawn args   'D:\\test\\msys64\\mingw64\\include\\node\\common.gypi',
84 error gyp info spawn args   '-Dlibrary=shared_library',
84 error gyp info spawn args   '-Dvisibility=default',
84 error gyp info spawn args   '-Dnode_root_dir=D:\\test\\msys64\\mingw64',
84 error gyp info spawn args   '-Dnode_gyp_dir=D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp',
84 error gyp info spawn args   '-Dnode_lib_file=D:\\test\\msys64\\mingw64\\lib\\libnode.dll.a',
84 error gyp info spawn args   '-Dmodule_root_dir=D:\\test\\msys64\\test\\node_modules\\node-pty',
84 error gyp info spawn args   '-Dnode_engine=v8',
84 error gyp info spawn args   '--depth=.',
84 error gyp info spawn args   '--no-parallel',
84 error gyp info spawn args   '--generator-output',
84 error gyp info spawn args   'build',
84 error gyp info spawn args   '-Goutput_dir=.'
84 error gyp info spawn args ]
84 error gyp info spawn make
84 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
84 error In file included from ../src/win/conpty.cc:24:
84 error /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfWorkerA(STRSAFE_LPSTR, size_t, STRSAFE_LPCSTR, va_list)’:
84 error /usr/include/w32api/strsafe.h:1555:12: error: ‘_vsnprintf’ was not declared in this scope
84 error  1555 |     iRet = _vsnprintf(pszDest,cchMax,pszFormat,argList);
84 error       |            ^~~~~~~~~~
84 error /usr/include/w32api/strsafe.h:1555:12: note: the macro ‘_vsnprintf’ had not yet been defined
84 error /usr/include/w32api/strsafe.h:1961: note: it was later defined here
84 error  1961 | #define _vsnprintf _vsnprintf_instead_use_StringCbVPrintfA_or_StringCchVPrintfA;
84 error       |
84 error /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfWorkerW(STRSAFE_LPWSTR, size_t, STRSAFE_LPCWSTR, va_list)’:
84 error /usr/include/w32api/strsafe.h:1575:12: error: ‘_vsnwprintf’ was not declared in this scope
84 error  1575 |     iRet = _vsnwprintf(pszDest,cchMax,pszFormat,argList);
84 error       |            ^~~~~~~~~~~
84 error /usr/include/w32api/strsafe.h:1575:12: note: the macro ‘_vsnwprintf’ had not yet been defined
84 error /usr/include/w32api/strsafe.h:1964: note: it was later defined here
84 error  1964 | #define _vsnwprintf _vsnwprintf_instead_use_StringCbVPrintfW_or_StringCchVPrintfW;
84 error       |
84 error /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfExWorkerA(STRSAFE_LPSTR, size_t, size_t, char**, size_t*, unsigned int, STRSAFE_LPCSTR, va_list)’:
84 error /usr/include/w32api/strsafe.h:1612:16: error: ‘_vsnprintf’ was not declared in this scope
84 error  1612 |         iRet = _vsnprintf(pszDest,cchMax,pszFormat,argList);
84 error       |                ^~~~~~~~~~
84 error /usr/include/w32api/strsafe.h:1612:16: note: the macro ‘_vsnprintf’ had not yet been defined
84 error /usr/include/w32api/strsafe.h:1961: note: it was later defined here
84 error  1961 | #define _vsnprintf _vsnprintf_instead_use_StringCbVPrintfA_or_StringCchVPrintfA;
84 error       |
84 error /usr/include/w32api/strsafe.h: In function ‘HRESULT StringVPrintfExWorkerW(STRSAFE_LPWSTR, size_t, size_t, wchar_t**, size_t*, unsigned int, STRSAFE_LPCWSTR, va_list)’:
84 error /usr/include/w32api/strsafe.h:1685:16: error: ‘_vsnwprintf’ was not declared in this scope
84 error  1685 |         iRet = _vsnwprintf(pszDest,cchMax,pszFormat,argList);
84 error       |                ^~~~~~~~~~~
84 error /usr/include/w32api/strsafe.h:1685:16: note: the macro ‘_vsnwprintf’ had not yet been defined
84 error /usr/include/w32api/strsafe.h:1964: note: it was later defined here
84 error  1964 | #define _vsnwprintf _vsnwprintf_instead_use_StringCbVPrintfW_or_StringCchVPrintfW;
84 error       |
84 error make: *** [conpty.target.mk:93: Release/obj.target/conpty/src/win/conpty.o] Error 1
84 error gyp ERR! build error
84 error gyp ERR! stack Error: `make` failed with exit code: 2
84 error gyp ERR! stack     at ChildProcess.onExit (D:\test\msys64\mingw64\lib\node_modules\npm\node_modules\node-gyp\lib\build.js:203:23)
84 error gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
84 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
84 error gyp ERR! System MINGW32_NT-10.0 10.0.20348
84 error gyp ERR! command "D:\\test\\msys64\\mingw64\\bin\\node.exe" "D:\\test\\msys64\\mingw64\\lib\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
84 error gyp ERR! cwd D:\test\msys64\test\node_modules\node-pty
84 error gyp ERR! node -v v18.17.1
84 error gyp ERR! node-gyp -v v9.3.1
84 error gyp ERR! not ok
85 verbose exit 1
86 timing npm Completed in 4051ms
87 verbose unfinished npm timer reify 1702143646474
88 verbose unfinished npm timer reify:build 1702143646792
89 verbose unfinished npm timer build 1702143646792
90 verbose unfinished npm timer build:deps 1702143646792
91 verbose unfinished npm timer build:run:install 1702143646794
92 verbose unfinished npm timer build:run:install:node_modules/node-pty 1702143646794
93 verbose code 1
94 error A complete log of this run can be found in: C:\npm\cache\_logs\2023-12-09T17_40_46_193Z-debug-0.log
```

**Comment by revelator** [comment]
looks like its using the msys2 compiler instead of the mingw* compilers -> /usr/include/w32api.
do you have the mingw* compilers installed ?.
