### ISSUE TITLE
scikit-build does not support mingw python

### ISSUE THREAD

**Issue by Zibri** [msys2/MINGW-packages#20936]
```
Zibri@home MINGW64 /i/llama.cpp
# pip3 install numpy
Collecting numpy
  Using cached numpy-1.26.4.tar.gz (15.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Collecting ninja>=1.8.2
        Using cached ninja-1.11.1.1.tar.gz (132 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: ninja
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [30 lines of output]
            /tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:312: UserWarning: git archive did not support describe output
              warnings.warn("git archive did not support describe output")
            /tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/setuptools_scm/git.py:331: UserWarning: unprocessed git archival found (no export subst applied)
              warnings.warn("unprocessed git archival found (no export subst applied)")
            Traceback (most recent call last):
              File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 410, in build_wheel
                return self._build_with_temp_dir(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
                self.run_setup()
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
                exec(code, locals())
              File "<string>", line 32, in <module>
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr = cmaker.CMaker(cmake_executable)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/skbuild/cmaker.py", line 149, in __init__
                self.platform = get_platform()
                                ^^^^^^^^^^^^^^
              File "/tmp/pip-build-env-s2l7r1n_/overlay/lib/python3.11/site-packages/skbuild/platform_specifics/platform_factory.py", line 54, in get_platform
                raise RuntimeError(msg)
            RuntimeError: Unsupported platform: mingw64_nt-10.0-19045. Please contact the scikit-build team.
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build ninja
      ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


```

**Comment by Zibri** [comment]
apparently is due to this:
`RuntimeError: Unsupported platform: mingw64_nt-10.0-19045. Please contact the scikit-build team.
`

**Comment by Zibri** [comment]
I know I can install [mingw-w64-x86_64-ninja](https://packages.msys2.org/package/mingw-w64-x86_64-ninja)
and 
mingw-w64-x86_64-python-numpy

just  wondering why it fails if installed with pip

**Comment by lazka** [comment]
Someone would need to make scikit-build support MSYS2, I'd guess.

**Comment by lazka** [comment]
numpy now uses meson-python which works fine in MSYS2 (assuming the build dependencies are installed, pass "-v" if it fails to get details)
