### ISSUE TITLE
uv can't find /mingw64/bin/python

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MINGW-packages#21091]
### Description / Steps to reproduce the issue

- install `uv:p`
- `uv pip install x`
- get error

### Expected behavior

It should install

### Actual behavior

It does not find python even though it is installed

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [X] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

n/a

**Comment by ognevny** [comment]
uv is not provided for MINGW64 environment

**Comment by Kreijstal** [comment]
> uv is not provided for MINGW64 environment

it does not find `/ucrt64/bin/python` either

**Comment by ognevny** [comment]
I'll try to reproduce tomorrow

**Comment by ognevny** [comment]
according to uv's documentation, you need to create a virtual env first. but I get this message with python path set
```
uv venv --python=/ucrt64/bin/python.exe
  x Querying Python at C:/msys64/ucrt64/bin/python.exe failed with exit status exit code: 1
  | --- stdout:

  | --- stderr:
  | Traceback (most recent call last):
  |   File "<string>", line 1, in <module>
  | ModuleNotFoundError: No module named 'python'
  | ---
```
even when I tried to create venv with `python -m venv`, I still get the same error. feel free to open an issue upstream

**Comment by Kreijstal** [comment]
> according to uv's documentation, you need to create a virtual env first. but I get this message with python path set
> 
> ```
> uv venv --python=/ucrt64/bin/python.exe
>   x Querying Python at C:/msys64/ucrt64/bin/python.exe failed with exit status exit code: 1
>   | --- stdout:
> 
>   | --- stderr:
>   | Traceback (most recent call last):
>   |   File "<string>", line 1, in <module>
>   | ModuleNotFoundError: No module named 'python'
>   | ---
> ```
> 
> even when I tried to create venv with `python -m venv`, I still get the same error. feel free to open an issue upstream

Dont know why the package is there if it is broken, but ok. Also upstream probably only cares about msvc

**Comment by ognevny** [comment]
> Dont know why the package is there if it is broken, but ok. Also upstream probably only cares about msvc

I didn't test the package as I'm not a python developer. how did you understand that it cares only about msvc?

**Comment by ognevny** [comment]
https://github.com/astral-sh/uv/issues/3573

**Comment by ArchGuyWu** [comment]
> > Dont know why the package is there if it is broken, but ok. Also upstream probably only cares about msvc
> 
> I didn't test the package as I'm not a python developer. how did you understand that it cares only about msvc?

Just due to the bin path in windows is script, not bin.
