### ISSUE TITLE
kdiff3: Crashing when comparing to two text files

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#21713]
### Description / Steps to reproduce the issue

I've been able to reproduce this with quite a few files now. Local release and debug builds are now also showing this symptom.

Attached are two of the file comparisons I was able to reproduce this with.

[two_files.zip](https://github.com/user-attachments/files/16707116/two_files.zip)

### Expected behavior

Files are loaded correctly

### Actual behavior

Runtime crash:
```
warning: org.kde.kdiff3: Diff: A <-> B
warning: org.kde.kdiff3: Linediff: A <-> B
warning: org.kde.kdiff3: Enter: calcDiff3LineListUsingAB
warning: org.kde.kdiff3: Leave: calcDiff3LineListUsingAB
[Thread 32544.0x5034 exited with code 0]
[Thread 32544.0x6a3c exited with code 0]
[Thread 32544.0x1aa0 exited with code 0]
[Thread 32544.0x30ec exited with code 0]
[New Thread 32544.0x32e8]
warning: org.kde.kdiff3: Loading A:  "C:/msys64/home/Hernan/.bash_history"
warning: org.kde.kdiff3: Loading B:  "C:/msys64/home/Hernan/.bash_logout"
warning: org.kde.kdiff3: Diff: A <-> B
warning: org.kde.kdiff3: Linediff: A <-> B
warning: org.kde.kdiff3: Enter: calcDiff3LineListUsingAB
warning: org.kde.kdiff3: Leave: calcDiff3LineListUsingAB

Thread 1 received signal SIGFPE, Arithmetic exception.
0x00007ff7171744ed in getBestFirstLine (line=..., nofLines=nofLines@entry=1, firstLine=..., visibleLines=0)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/difftextwindow.cpp:588
588             qint32 numberPages = std::floor(nofLines / visibleLines);
(gdb) bt
#0  0x00007ff7171744ed in getBestFirstLine (line=..., nofLines=nofLines@entry=1, firstLine=..., visibleLines=0)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/difftextwindow.cpp:588
#1  0x00007ff717196bf8 in MergeResultWindow::setFastSelector (this=0x1583d580, i=...)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/mergeresultwindow.cpp:820
#2  0x00007ff717196d72 in MergeResultWindow::go (this=0x1583d580, eDir=MergeResultWindow::Direction::eUp,
    eEndPoint=MergeResultWindow::EndPoint::eEnd)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/mergeresultwindow.cpp:567
#3  0x00007ff717196ef4 in MergeResultWindow::slotGoTop (this=0x5fb9e0, this@entry=0x1583d580)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/mergeresultwindow.cpp:677
#4  0x00007ff71719bcdc in MergeResultWindow::merge (this=this@entry=0x1583d580, bAutoSolve=bAutoSolve@entry=true,
    defaultSelector=<optimized out>, defaultSelector@entry=e_SrcSelector::Min, bConflictsOnly=bConflictsOnly@entry=false,
    bWhiteSpaceOnly=bWhiteSpaceOnly@entry=false)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/mergeresultwindow.cpp:416
#5  0x00007ff71719bf43 in MergeResultWindow::init (this=this@entry=0x1583d580,
    pLineDataA=std::shared_ptr<std::vector<LineData, std::allocator<LineData> >> (use count 4, weak count 0) = {...}, sizeA=...,
    pLineDataB=std::shared_ptr<std::vector<LineData, std::allocator<LineData> >> (use count 4, weak count 0) = {...}, sizeB=...,
    pLineDataC=std::shared_ptr<std::vector<LineData, std::allocator<LineData> >> (empty) = {...}, sizeC=...,
    pDiff3LineList=pDiff3LineList@entry=0x7048d88, pTotalDiffStatus=pTotalDiffStatus@entry=0x70495c0, bAutoSolve=bAutoSolve@entry=true)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/mergeresultwindow.cpp:132
#6  0x00007ff71716df49 in KDiff3App::mainInit (this=0x7048930, pTotalDiffStatus=0x70495c0, inFlags=...)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/pdiff.cpp:380
#7  0x00007ff7171490de in KDiff3App::doFileCompare (this=this@entry=0x7048930) at C:/msys64/ucrt64/include/qt6/QtCore/qflags.h:74
#8  0x00007ff71717231c in KDiff3App::slotFileOpen (this=this@entry=0x7048930)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/pdiff.cpp:927
#9  0x00007ff7171525ee in KDiff3App::completeInit (this=0x7048930, fn1=..., fn2=..., fn3=...)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/kdiff3.cpp:580
#10 0x00007ff7171485d3 in KDiff3Shell::KDiff3Shell (this=this@entry=0x726780, fn1=..., fn2=..., fn3=..., __in_chrg=<optimized out>,
    __vtt_parm=<optimized out>) at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/kdiff3_shell.cpp:39
#11 0x00007ff717145662 in operator() (__closure=0x274c860)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/main.cpp:195
#12 0x00007ff7171456ed in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, qMain(qint32, char**)::<lambda()> >::call (f=..., arg=<optimized out>) at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:136
#13 QtPrivate::FunctorCallable<qMain(qint32, char**)::<lambda()> >::call<QtPrivate::List<>, void> (f=..., arg=<optimized out>)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:345
#14 QtPrivate::QCallableObject<qMain(qint32, char**)::<lambda()>, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x0, r=0x0, a=0x0, ret=0x0) at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:555
#15 0x00007ffc782f50f1 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#16 0x00007ffc782fa840 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
--Type <RET> for more, q to quit, c to continue without paging--
#17 0x00007ffc772c5e71 in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#18 0x00007ffc782bb5f8 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#19 0x00007ffc782bfa54 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#20 0x00007ffc77d7b80e in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#21 0x00007ffc78469e70 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#22 0x00007ffc77d7b7f5 in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#23 0x00007ffc782c7214 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#24 0x00007ffc782c5527 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#25 0x00007ff7171470ff in qMain (argc=<optimized out>, argv=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-kdiff3/src/kdiff3-1.11.2/src/main.cpp:198
#26 0x00007ff7171cd7e4 in qtEntryPoint() ()
#27 0x00007ff7171412e9 in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:258
#28 0x00007ff7171413d6 in WinMainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:148
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANG32
- [ ] CLANGARM64

### Are you willing to submit a PR?

Only if I can find the source of the issue

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system with the attached files.

**Comment by hmartinez82** [comment]
Will do once I'm home which, unfortunately, won't be until after the 22nd :(

**Comment by lazka** [comment]
I also can't reproduce

**Comment by hmartinez82** [comment]
Ok, I can't repro it with the latest version. 😊
