### ISSUE TITLE
Matplotlib (Python) totally broken on UCRT64 (at least)

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#22608]
### Description / Steps to reproduce the issue

Given:

```
$ cat plot_test.py
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 1.0 + 0.01, 0.01)
s = np.cos(2*2*np.pi*t)
plt.plot(t, s, '-', lw=2)

plt.xlabel('time (s)')
plt.ylabel('voltage (mV)')
plt.title('About as simple as it gets, folks')
plt.grid(True)

plt.axes().set_aspect('equal', 'datalim')


plt.show()
```

one gets

```
$ python plot_test.py
Traceback (most recent call last):
  File "C:/msys64/tmp/plot_test.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
SyntaxError: source code string cannot contain null bytes
```

### Expected behavior

It should open a window with a plot.

### Actual behavior

It prints errors

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [ ] CLANG64
- [ ] CLANGARM64

**Comment by podsvirov** [comment]
It's work for me as expected but only after commenting one line:
```python
#plt.axes().set_aspect('equal', 'datalim')
```
![Screenshot 2024-11-21 204239](https://github.com/user-attachments/assets/5ec4fed6-f338-430d-b42e-7d2256a7f2fc)

**Comment by angelog0** [comment]
But all python scripts using matplotlib I have, worked until two months ago.. the above too...

**Comment by lazka** [comment]
> It's work for me as expected but only after commenting one line:
> 
> ```python
> #plt.axes().set_aspect('equal', 'datalim')
> ```

same here

**Comment by angelog0** [comment]
This is another example taken from [here](https://en.wikipedia.org/wiki/Logistic_map#Graphical_representation):

```
$ cat logistic_map.py
import numpy as np
import matplotlib.pyplot as plt

interval = (2.8, 4)  # start, end
accuracy = 0.0001
reps = 600  # number of repetitions
numtoplot = 200
lims = np.zeros(reps)

fig, biax = plt.subplots()
fig.set_size_inches(16, 9)

lims[0] = np.random.rand()
for r in np.arange(interval[0], interval[1], accuracy):
    for i in range(reps - 1):
        lims[i + 1] = r * lims[i] * (1 - lims[i])

    biax.plot([r] * numtoplot, lims[reps - numtoplot :], "b.", markersize=0.02)

biax.set(xlabel="r", ylabel="x", title="logistic map")
plt.show()
```

On WSL I have

```
$ python3 --version
Python 3.12.3

$ python3 logistic_map.py
```

and the image shows up.

On MSYS2/UCRT64:

```
$ python3 --version
Python 3.12.7

$ python3 logistic_map.py
Traceback (most recent call last):
  File "C:/msys64/home/angelo/programming/circle_3p/logistic_map.py", line 2, in <module>
    import matplotlib.pyplot as plt
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/__init__.py", line 159, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/rcsetup.py", line 28, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:/msys64/ucrt64/lib/python3.12/site-packages/matplotlib/colors.py", line 57, in <module>
    from matplotlib import _api, _cm, cbook, scale
SyntaxError: source code string cannot contain null bytes
```

**Comment by lazka** [comment]
Does `pacman -Qkk mingw-w64-ucrt-x86_64-python-matplotlib` give any errors? (checking if all files are unaltered)

**Comment by angelog0** [comment]
@lazka wrote:

> Does pacman -Qkk mingw-w64-ucrt-x86_64-python-matplotlib give any errors?

```
$ LANG= pacman -Qkk mingw-w64-ucrt-x86_64-python-matplotlib
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib/rcsetup.pyi (SHA256 checksum mismatch)
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib/sankey.py (SHA256 checksum mismatch)
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib/sankey.pyi (SHA256 checksum mismatch)
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib/scale.py (SHA256 checksum mismatch)
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib/scale.pyi (SHA256 checksum mismatch)
[...]
warning: mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/share/licenses/python-matplotlib/LICENSE (SHA256 checksum mismatch)
mingw-w64-ucrt-x86_64-python-matplotlib: 1214 total files, 132 altered files
```

Trying to reinstall:

```
$ pacman -Scc

$ pacman -S mingw-w64-ucrt-x86_64-python-matplotlib
attenzione: mingw-w64-ucrt-x86_64-python-matplotlib-3.9.2-2 è aggiornato ma sarà reinstallato
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (1) mingw-w64-ucrt-x86_64-python-matplotlib-3.9.2-2

Dimensione totale dei pacchetti da scaricare:    6,95 MiB
Dimensione totale dei pacchetti da installare:  34,89 MiB

:: Vuoi procedere con l'installazione? [S/n]
:: Download dei pacchetti in corso...
 mingw-w64-ucrt-x86_64-python-matplotli...     6,9 MiB  1966 KiB/s 00:04 [#######################################] 100%
(1/1) verifica delle chiavi presenti nel portachiavi                     [#######################################] 100%
(1/1) verifica dell'integrità dei pacchetti                              [#######################################] 100%
(1/1) caricamento dei file dei pacchetti                                 [#######################################] 100%
(1/1) controllo dei conflitti in corso                                   [#######################################] 100%
errore: impossibile eseguire l'operazione richiesta (file in conflitto)
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/__pycache__/pylab.cpython-312.opt-1.pyc è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/__pycache__/pylab.cpython-312.pyc è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib-3.9.2.dist-info/LICENSE è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib-3.9.2.dist-info/METADATA è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/matplotlib-3.9.2.dist-info/RECORD è già presente nel filesystem
[...]
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/mpl_toolkits/mplot3d/tests/test_art3d.py è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/mpl_toolkits/mplot3d/tests/test_axes3d.py è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/mpl_toolkits/mplot3d/tests/test_legend3d.py è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/pylab.py è già presente nel filesystem
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/share/licenses/python-matplotlib/LICENSE è già presente nel filesystem
Si sono verificati degli errori, nessun pacchetto è stato aggiornato.
```

So.. How should I proceed?

**Comment by angelog0** [comment]
I did also

```
$ pacman -Rscn mingw-w64-ucrt-x86_64-python-matplotlib
controllo delle dipendenze in corso...
:: mingw-w64-ucrt-x86_64-python-fonttools richiede facoltativamente mingw-w64-ucrt-x86_64-python-matplotlib: for visualizing DesignSpaceDocument and resulting VariationModel

Pacchetti (1) mingw-w64-ucrt-x86_64-python-matplotlib-3.9.2-2


:: Vuoi rimuovere questi pacchetti? [S/n]
:: Elaborazione delle modifiche al pacchetto...
(1/1) rimozione in corso di mingw-w64-ucrt-x86_64-python-matplotlib      [#######################################] 100%
```

and then

```
$ pacman -Scc

Directory della cache: /var/cache/pacman/pkg/
:: Vuoi rimuovere TUTTI i file dalla cache? [S/n]
rimozione di tutti i file dalla cache in corso...

Directory del database: /var/lib/pacman/
:: Vuoi rimuovere i repository inutilizzati? [S/n]
rimozione dei repository inutilizzati in corso...

angelo@Tatooine MSYS: ~
$ pacman --needed -S mingw-w64-ucrt-x86_64-python-matplotlib
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (1) mingw-w64-ucrt-x86_64-python-matplotlib-3.9.2-2

Dimensione totale dei pacchetti da scaricare:    6,95 MiB
Dimensione totale dei pacchetti da installare:  34,89 MiB

:: Vuoi procedere con l'installazione? [S/n]
:: Download dei pacchetti in corso...
 mingw-w64-ucrt-x86_64-python-matplotli...     6,9 MiB  2006 KiB/s 00:04 [#######################################] 100%
(1/1) verifica delle chiavi presenti nel portachiavi                     [#######################################] 100%
(1/1) verifica dell'integrità dei pacchetti                              [#######################################] 100%
(1/1) caricamento dei file dei pacchetti                                 [#######################################] 100%
(1/1) controllo dei conflitti in corso                                   [#######################################] 100%
errore: impossibile eseguire l'operazione richiesta (file in conflitto)
mingw-w64-ucrt-x86_64-python-matplotlib: /ucrt64/lib/python3.12/site-packages/__pycache__/pylab.cpython-312.opt-1.pyc è già presente nel filesystem
[...]
```

as above..

**Comment by lazka** [comment]
> It seems I have fixed the issue with:
> 
> ```
> pacman --needed -S mingw-w64-ucrt-x86_64-python-matplotlib --overwrite '*'
> ```
> 
> not sure it is the best solution...

It's a fine solution. In case it was due to a pip install you could have uninstalled first via pip, but worst case you got left over unused files now.
