### ISSUE TITLE
freecad: Segfault when opening Prefereces

### ISSUE THREAD

**Issue by hmartinez82** [msys2/MINGW-packages#22600]
### Description / Steps to reproduce the issue

- Install FreeCAD 1.0rc2-5
- Click on the Edit menu then Preferences

This is also happening with 1.0.0

### Expected behavior

Preferences dialog shows up

### Actual behavior

```
[Thread 23096.0x5410 exited with code 0]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffc058974bc in Gui::PythonWrapper::getWrapperName (this=this@entry=0x5f9537, obj=obj@entry=0x5223ca70)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/PythonWrapper.cpp:848
848         const QMetaObject* meta = obj->metaObject();
(gdb) bt
#0  0x00007ffc058974bc in Gui::PythonWrapper::getWrapperName (this=this@entry=0x5f9537, obj=obj@entry=0x5223ca70)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/PythonWrapper.cpp:848
#1  0x00007ffc0589f9c6 in Gui::UiLoaderPy::load (this=0x5220d4f0, args=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/UiLoader.cpp:607
#2  0x00007ffc05961aa0 in Py::PythonExtension<Gui::UiLoaderPy>::method_varargs_call_handler (
    _self_and_name_tuple=<optimized out>, _args=0x1d69ece0)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/CXX/Python3/ExtensionOldType.hxx:309
#3  0x00007ffcc3553460 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#4  0x00007ffcc3518e3f in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#5  0x00007ffcc35191db in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#6  0x00007ffcc35c87a2 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#7  0x00007ffcc3476982 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#8  0x00007ffcc3498023 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#9  0x00007ffcc3497bd7 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#10 0x00007ffcc34976e3 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#11 0x00007ffc0589f234 in Gui::PySideUicModule::loadUi (this=<optimized out>, args=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/UiLoader.cpp:185
#12 0x00007ffc0595f0f1 in Py::ExtensionModule<Gui::PySideUicModule>::invoke_method_varargs (this=this@entry=0x310fcb0,
    method_def=<optimized out>, args=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/CXX/Python3/ExtensionModule.hxx:182
#13 0x00007ffc96ea980f in Py::method_varargs_call_handler (_self_and_name_tuple=<optimized out>, _args=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/CXX/Python3/Objects.hxx:238
#14 0x00007ffcc3553460 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#15 0x00007ffcc3518e3f in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#16 0x00007ffcc35191db in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#17 0x00007ffcc35c87a2 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#18 0x00007ffcc35196e5 in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#19 0x00007ffcc3565d3a in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#20 0x00007ffcc356484c in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#21 0x00007ffcc3519fad in ?? () from C:\msys64\ucrt64\bin\libpython3.12.dll
#22 0x00007ffc05b004f9 in Py::Callable::apply (this=<optimized out>, args=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/CXX/Python3/Objects.hxx:3261
#23 0x00007ffc058a12e0 in Gui::PrefPagePyProducer::Produce (this=0x5bb6670)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/WidgetFactory.cpp:248
#24 0x00007ffc96ec34c9 in Base::Factory::Produce (this=0x580b6a0, sClassName=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Base/Factory.cpp:51
#25 0x00007ffc058a2de0 in Gui::WidgetFactoryInst::createPreferencePage (this=<optimized out>, sName=<optimized out>,
    parent=parent@entry=0x0) at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/WidgetFactory.cpp:117
#26 0x00007ffc056a824a in Gui::Dialog::DlgPreferencesImp::createPreferencePage (pageName="AddonManagerOptions",
    groupName="Addon Manager")
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/DlgPreferencesImp.cpp:284
#27 0x00007ffc056aa42f in Gui::Dialog::DlgPreferencesImp::createPageInGroup (this=this@entry=0x5fa6b0,
    groupItem=groupItem@entry=0x5220cdc0, pageName="AddonManagerOptions")
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/DlgPreferencesImp.cpp:315
#28 0x00007ffc056aa7fc in Gui::Dialog::DlgPreferencesImp::setupPages (this=this@entry=0x5fa6b0)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/DlgPreferencesImp.cpp:199
#29 0x00007ffc056aacaa in Gui::Dialog::DlgPreferencesImp::DlgPreferencesImp (this=this@entry=0x5fa6b0,
    parent=<optimized out>, fl=..., fl@entry=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/DlgPreferencesImp.cpp:140
#30 0x00007ffc05615ded in StdCmdDlgPreferences::activated (this=<optimized out>, iMsg=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/CommandStd.cpp:429
#31 0x00007ffc05604f56 in Gui::Command::_invoke (this=this@entry=0x582f8d0, id=id@entry=0, disablelog=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Command.cpp:444
#32 0x00007ffc0560557e in Gui::Command::invoke (this=0x582f8d0, i=0, trigger=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Command.cpp:408
#33 0x00007ffc055f4bc6 in Gui::Action::onActivated (this=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Action.cpp:111
#34 0x00007ffc05bc04de in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}::operator()() const (__closure=__closure@entry=0x5faa80)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:152
#35 0x00007ffc05ac81b9 in QtPrivate::FunctorCallBase::call_internal<void, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}>(void**, QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**)::{lambda()#1}&&) (args=<optimized out>, fn=...)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:65
#36 QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Gui::Action::*)()>::call(void (Gui::Action::*)(), Gui::Action*, void**) (f=&virtual Gui::Action::onActivated(), o=<optimized out>, arg=<optimized out>)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:151
#37 0x00007ffc05adcd02 in QtPrivate::FunctionPointer<void (Gui::Action::*)()>::call<QtPrivate::List<>, void>(void (Gui::Action::*)(), Gui::Action*, void**) (f=<optimized out>, o=0x5223ca70, arg=0x7ffd1ccfdba5 <ucrtbase!memmove+213>)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:199
#38 QtPrivate::QCallableObject<void (Gui::Action::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=-17891602, this_=<optimized out>, r=0x5223ca70, a=0x7ffd1ccfdba5 <ucrtbase!memmove+213>, ret=0x0)
    at C:/msys64/ucrt64/include/qt6/QtCore/qobjectdefs_impl.h:570
#39 0x00007ffcc2eacbbe in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#40 0x00007ffcbf94d6b4 in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#41 0x00007ffca30a20ae in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#42 0x00007ffca30aa99f in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#43 0x00007ffca2f4afb8 in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#44 0x00007ffca2ef63c5 in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#45 0x00007ffca2f0113e in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#46 0x00007ffc055dd9ac in Gui::GUIApplication::notify (this=0x5ff800, receiver=0x113f52b0, event=0x5fb760)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/GuiApplication.cpp:93
#47 0x00007ffcc2bb9d98 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#48 0x00007ffca2eff79f in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#49 0x00007ffca2f59fad in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#50 0x00007ffca2f5c16b in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#51 0x00007ffca2ef63c5 in ?? () from C:\msys64\ucrt64\bin\Qt6Widgets.dll
#52 0x00007ffc055dd9ac in Gui::GUIApplication::notify (this=0x5ff800, receiver=0x10d37e10, event=0x5fbd50)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/GuiApplication.cpp:93
#53 0x00007ffcc2bb9d98 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#54 0x00007ffcbf518876 in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#55 0x00007ffcbf56d083 in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#56 0x00007ffcc2d78e46 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#57 0x00007ffcbf8c2309 in ?? () from C:\msys64\ucrt64\bin\Qt6Gui.dll
#58 0x00007ffcc2bc5e73 in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#59 0x00007ffcc2bc3b4f in ?? () from C:\msys64\ucrt64\bin\Qt6Core.dll
#60 0x00007ffc055a985f in (anonymous namespace)::tryRunEventLoop (mainApp=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Application.cpp:2196
#61 0x00007ffc055a9b49 in (anonymous namespace)::runEventLoop (mainApp=...)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Application.cpp:2225
#62 0x00007ffc055ad0d9 in Gui::Application::runApplication ()
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Gui/Application.cpp:2302
#63 0x00007ff783e51d91 in qMain (argc=<optimized out>, argv=<optimized out>)
    at X:/Github/MINGW-packages/mingw-w64-freecad/src/FreeCAD-1.0.0/src/Main/MainGui.cpp:295
#64 0x00007ff783e5430c in qtEntryPoint() ()
#65 0x00007ff783e512e9 in __tmainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:259
#66 0x00007ff783e513d6 in WinMainCRTStartup () at C:/M/B/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:149
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26100

### MINGW environments affected

- [ ] MINGW64
- [ ] MINGW32
- [X] UCRT64
- [X] CLANG64
- [X] CLANGARM64

**Comment by hmartinez82** [comment]
The clang64 build stack trace has more symbols:
```
(lldb) Process 21056 launched: 'C:\msys64\clang64\bin\FreeCAD_d.exe' (x86_64)
Process 21056 stopped
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ffbf8f55a01: Access violation reading location 0xffffffffffffffff
    frame #0: 0x00007ffbf8f55a01 libFreeCADGui_d.dll`Gui::PythonWrapper::getWrapperName(this=<unavailable>, obj=0x000001f3ffd46d00) const at PythonWrapper.cpp:848:36
   845  const char* PythonWrapper::getWrapperName(QObject* obj) const
   846  {
   847  #if defined (HAVE_SHIBOKEN) && defined(HAVE_PYSIDE)
-> 848      const QMetaObject* meta = obj->metaObject();
   849      while (meta) {
   850          const char* typeName = meta->className();
   851          PyTypeObject* exactType = Shiboken::Conversions::getPythonTypeObject(typeName);
(lldb) bt
* thread #1, stop reason = Exception 0xc0000005 encountered at address 0x7ffbf8f55a01: Access violation reading location 0xffffffffffffffff
  * frame #0: 0x00007ffbf8f55a01 libFreeCADGui_d.dll`Gui::PythonWrapper::getWrapperName(this=<unavailable>, obj=0x000001f3ffd46d00) const at PythonWrapper.cpp:848:36
    frame #1: 0x00007ffbf8f5e08d libFreeCADGui_d.dll`Gui::UiLoaderPy::load(this=<unavailable>, args=<unavailable>) at UiLoader.cpp:607:45
    frame #2: 0x00007ffbf8f61a27 libFreeCADGui_d.dll`Py::PythonExtension<Gui::UiLoaderPy>::method_varargs_call_handler(_self_and_name_tuple=<unavailable>, _args=0x000001f3c3686e30) at ExtensionOldType.hxx:309:26
    frame #3: 0x00007ffc98caed1b libpython3.12.dll`PyCMethod_GetClass + 619
    frame #4: 0x00007ffc98c5763b libpython3.12.dll`PyObject_Vectorcall + 235
    frame #5: 0x00007ffc98d79a87 libpython3.12.dll`_PyEval_EvalFrameDefault + 44039
    frame #6: 0x00007ffc98d6e4ee libpython3.12.dll`PyEval_EvalCode + 190
    frame #7: 0x00007ffc98ddb932 libpython3.12.dll`PyErr_DisplayException + 194
    frame #8: 0x00007ffc98ddb0f1 libpython3.12.dll`PyRun_StringFlags + 113
    frame #9: 0x00007ffbf8f57c6d libFreeCADGui_d.dll`Gui::PySideUicModule::loadUi(this=<unavailable>, args=0x0000001510799be8) at UiLoader.cpp:185:24
    frame #10: 0x00007ffbf8f614f4 libFreeCADGui_d.dll`Py::ExtensionModule<Gui::PySideUicModule>::invoke_method_varargs(this=<unavailable>, method_def=<unavailable>, args=<unavailable>) at ExtensionModule.hxx:182:20
    frame #11: 0x00007ffc76b08f40 libFreeCADBase_d.dll`method_varargs_call_handler(_self_and_name_tuple=<unavailable>, _args=0x000001f3b4b72f50) at cxx_extensions.cxx:1657:23
    frame #12: 0x00007ffc98caed1b libpython3.12.dll`PyCMethod_GetClass + 619
    frame #13: 0x00007ffc98c5763b libpython3.12.dll`PyObject_Vectorcall + 235
    frame #14: 0x00007ffc98d79a87 libpython3.12.dll`_PyEval_EvalFrameDefault + 44039
    frame #15: 0x00007ffc98c57c94 libpython3.12.dll`_PyFunction_Vectorcall + 84
    frame #16: 0x00007ffc98c57e69 libpython3.12.dll`_PyObject_Call_Prepend + 169
    frame #17: 0x00007ffc98cd61ec libpython3.12.dll`_PySuper_Lookup + 15276
    frame #18: 0x00007ffc98ccc701 libpython3.12.dll`_PyStaticType_Dealloc + 2289
    frame #19: 0x00007ffc98c57868 libpython3.12.dll`_PyObject_Call + 120
    frame #20: 0x00007ffbf8f62f89 libFreeCADGui_d.dll`Gui::PrefPagePyProducer::Produce() const [inlined] Py::Callable::apply(this=0x000000151079a1e0, args=0x000000151079a1d0) const at Objects.hxx:3261:32
    frame #21: 0x00007ffbf8f62f7a libFreeCADGui_d.dll`Gui::PrefPagePyProducer::Produce(this=0x000001f3c0fe8300) const at WidgetFactory.cpp:248:34
    frame #22: 0x00007ffc76b4dfb5 libFreeCADBase_d.dll`Base::Factory::Produce(this=<unavailable>, sClassName=<unavailable>) const at Factory.cpp:51:31
    frame #23: 0x00007ffbf8f621fb libFreeCADGui_d.dll`Gui::WidgetFactoryInst::createPreferencePage(this=<unavailable>, sName="AddonManagerOptions", parent=<unavailable>) const at WidgetFactory.cpp:117:44
    frame #24: 0x00007ffbf8bfee98 libFreeCADGui_d.dll`Gui::Dialog::DlgPreferencesImp::createPreferencePage(pageName="AddonManagerOptions", groupName="Addon Manager") at DlgPreferencesImp.cpp:284:44
    frame #25: 0x00007ffbf8bfe22b libFreeCADGui_d.dll`Gui::Dialog::DlgPreferencesImp::createPageInGroup(this=0x000000151079a538, groupItem=0x000001f3ffd267a0, pageName="AddonManagerOptions") at DlgPreferencesImp.cpp:315:32
    frame #26: 0x00007ffbf8bfc43f libFreeCADGui_d.dll`Gui::Dialog::DlgPreferencesImp::DlgPreferencesImp(QWidget*, QFlags<Qt::WindowType>) [inlined] Gui::Dialog::DlgPreferencesImp::setupPages(this=0x000000151079a538) at DlgPreferencesImp.cpp:199:13
    frame #27: 0x00007ffbf8bfc3e8 libFreeCADGui_d.dll`Gui::Dialog::DlgPreferencesImp::DlgPreferencesImp(this=0x000000151079a538, parent=<unavailable>, fl=<unavailable>) at DlgPreferencesImp.cpp:140:5
    frame #28: 0x00007ffbf8ab7bfe libFreeCADGui_d.dll`StdCmdDlgPreferences::activated(this=<unavailable>, iMsg=<unavailable>) at CommandStd.cpp:429:36
    frame #29: 0x00007ffbf8a8afdb libFreeCADGui_d.dll`Gui::Command::_invoke(this=0x000001f3b6c0dee0, id=0, disablelog=<unavailable>) at Command.cpp:444:17
    frame #30: 0x00007ffbf8a8ad6d libFreeCADGui_d.dll`Gui::Command::invoke(this=0x000001f3b6c0dee0, i=0, trigger=<unavailable>) at Command.cpp:408:5
    frame #31: 0x00007ffc7b3d7d08 Qt6Core.dll`void doActivate<false>(QObject*, int, void**) + 1528
    frame #32: 0x00007ffc988a8c9a Qt6Gui.dll`QAction::activate(QAction::ActionEvent) + 314
    frame #33: 0x00007ffc7ba54275 Qt6Widgets.dll`QMenuPrivate::activateCausedStack(QList<QPointer<QWidget>> const&, QAction*, QAction::ActionEvent, bool) + 117
    frame #34: 0x00007ffc7ba518d4 Qt6Widgets.dll`QMenuPrivate::activateAction(QAction*, QAction::ActionEvent, bool) + 740
    frame #35: 0x00007ffc7ba58fb9 Qt6Widgets.dll`QMenu::mouseReleaseEvent(QMouseEvent*) + 425
    frame #36: 0x00007ffc7b8c2cc2 Qt6Widgets.dll`QWidget::event(QEvent*) + 2258
    frame #37: 0x00007ffc7ba596e4 Qt6Widgets.dll`QMenu::event(QEvent*) + 1300
    frame #38: 0x00007ffc7b869c1b Qt6Widgets.dll`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 315
    frame #39: 0x00007ffc7b86c4f5 Qt6Widgets.dll`QApplication::notify(QObject*, QEvent*) + 6917
    frame #40: 0x00007ffbf8a41218 libFreeCADGui_d.dll`Gui::GUIApplication::notify(this=0x000000151079f2c0, receiver=0x000001f3c1b479f0, event=0x000000151079b430) at GuiApplication.cpp:93:34
    frame #41: 0x00007ffc7b37ed18 Qt6Core.dll`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
    frame #42: 0x00007ffc7b86a235 Qt6Widgets.dll`QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) + 837
    frame #43: 0x00007ffc7b8de374 Qt6Widgets.dll`QWidgetWindow::handleMouseEvent(QMouseEvent*) + 3092
    frame #44: 0x00007ffc7b8dcf55 Qt6Widgets.dll`QWidgetWindow::event(QEvent*) + 117
    frame #45: 0x00007ffc7b869c1b Qt6Widgets.dll`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 315
    frame #46: 0x00007ffc7b86ac49 Qt6Widgets.dll`QApplication::notify(QObject*, QEvent*) + 601
    frame #47: 0x00007ffbf8a41218 libFreeCADGui_d.dll`Gui::GUIApplication::notify(this=0x000000151079f2c0, receiver=0x000001f3d606c080, event=0x000000151079bb30) at GuiApplication.cpp:93:34
    frame #48: 0x00007ffc7b37ed18 Qt6Core.dll`QCoreApplication::notifyInternal2(QObject*, QEvent*) + 200
    frame #49: 0x00007ffc9844052d Qt6Gui.dll`QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2461
    frame #50: 0x00007ffc984b010a Qt6Gui.dll`QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 458
    frame #51: 0x00007ffc7b52e240 Qt6Core.dll`QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 96
    frame #52: 0x00007ffc9880f4d9 Qt6Gui.dll`QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 25
    frame #53: 0x00007ffc7b38a5da Qt6Core.dll`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 1194
    frame #54: 0x00007ffc7b37f503 Qt6Core.dll`QCoreApplication::exec() + 147
    frame #55: 0x00007ffbf89709c6 libFreeCADGui_d.dll`Gui::Application::runApplication() [inlined] (anonymous namespace)::tryRunEventLoop(mainApp=0x000000151079f2c0) at Application.cpp:2196:13
    frame #56: 0x00007ffbf89707d2 libFreeCADGui_d.dll`Gui::Application::runApplication() [inlined] (anonymous namespace)::runEventLoop(mainApp=0x000000151079f2c0) at Application.cpp:2225:9
    frame #57: 0x00007ffbf89707d2 libFreeCADGui_d.dll`Gui::Application::runApplication() at Application.cpp:2302:5
    frame #58: 0x00007ff743ec2eef FreeCAD_d.exe`qMain(argc=1, argv=<unavailable>) at MainGui.cpp:295:13
    frame #59: 0x00007ff743ed5878 FreeCAD_d.exe`main(argc=<unavailable>, argv=<unavailable>, envp=<unavailable>) at crtexewin.c:67:10
    frame #60: 0x00007ff743ec1303 FreeCAD_d.exe`__tmainCRTStartup at crtexe.c:259:15
    frame #61: 0x00007ff743ec1156 FreeCAD_d.exe`WinMainCRTStartup at crtexe.c:149:9
    frame #62: 0x00007ffd1debdbe7 kernel32.dll`BaseThreadInitThunk + 23
    frame #63: 0x00007ffd1f85fbec ntdll.dll`RtlUserThreadStart + 44
```
