### ISSUE TITLE
glog crashes when llvm libunwind is installed

### ISSUE THREAD

**Issue by giraldeau** [msys2/MINGW-packages#3321]
I found an interesting bug while compiling a ceres-solver example, which depends on glog. The glog exported target references the non-existent `C:\building\mingw64\lib\libunwind.a` library. Notice that this libunwind library belongs to llvm, and not gcc.

When glog uses the llvm libunwind, unit tests crash in `unw_getcontext()`. The solution is to recompile glog without `mingw-w64-x86_64-libunwind`. If libunwind package is installed, then glog will link with it and this causes a crash. I guess that we cannot mix the gcc/llvm unwind implementations.

As a reference, here is the backtrace: 

```
(gdb) run
Starting program: /e/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/demangle_unittest.exe
[New Thread 21496.0x4f48]

Program received signal SIGSEGV, Segmentation fault.
0x000000006630fc50 in unw_getcontext ()
   from /e/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/libglog.dll
(gdb) bt
#0  0x000000006630fc50 in unw_getcontext ()
   from /e/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/libglog.dll
#1  0x000000006630f97f in _Unwind_Backtrace ()
   from /e/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/libglog.dll
#2  0x00000000663209bb in _GLOBAL__sub_I__ZN3fLB26FLAGS_symbolize_stacktraceE ()
   from /e/MINGW-packages/mingw-w64-glog/src/build-x86_64-w64-mingw32/libglog.dll
#3  0x0000000066310b72 in __do_global_ctors ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/gccmain.c:61
#4  0x00000000663012cf in __DllMainCRTStartup (hDllHandle=0x66300000, dwReason=1, lpreserved=0x22fb00)
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtdll.c:189
#5  0x0000000077676ca8 in ntdll!TpAllocTimer () from /c/Windows/SYSTEM32/ntdll.dll
#6  0x000000007767d0d7 in ntdll!RtlCreateTagHeap () from /c/Windows/SYSTEM32/ntdll.dll
#7  0x00000000776dbd09 in ntdll!EtwEventSetInformation () from /c/Windows/SYSTEM32/ntdll.dll
#8  0x000000007766a36e in ntdll!LdrInitializeThunk () from /c/Windows/SYSTEM32/ntdll.dll
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by revelator** [comment]
yep seing something similar. not sure how to get around it though if clang needs this library ? maybe install it into the clang subdir in lib, it seems to be picked up anyway even if i move it there physically by clang anyway, but atleast it does not interfere with gcc.

**Comment by dragon-archer** [comment]
This should have been fixed by #4935, glog's cmake files no longer hardcode build path now.
