### ISSUE TITLE
mingw-w64-i686-python2-pip not working at all

### ISSUE THREAD

**Issue by magikmw** [msys2/MINGW-packages#390]
I have trouble using mingw-w64-i686-python2-pip in current (as of 2014-12-16) version of the pip package (mingw-w64-i686-python2-pip-1.5.6-1). After clean installation of MSYS2 and the mingw32 toolchain + above package (with dependencies) the problem manifests as such (in the mingw32 shell of course):

```
$ pip
Traceback (most recent call last):
  File "C:\msys64\mingw32\bin\pip-script.py", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pkg_resources.py", line 455, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pkg_resources.py", line 2531, in load_entry_point
    return ep.load()
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pkg_resources.py", line 2241, in load
['__name__'])
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pip/__init__.py", line 10, in <module>
from pip.util import get_installed_distributions, get_prog
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pip/util.py", line 18, in <module>
from pip._vendor.distlib import version
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
    from .compat import string_types
  File "C:/msys64/mingw32/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler`
```

I've googled around to find the issue could to be with the python interpreter not being built with SSL enabled. I've tried re-building the mingw python package from this repo, with no effect.

**Comment by kpwsyang** [comment]
I have the similar problem withe the pip now, no matter I use it under mingw32 or mingw64
the pip version is mingw-w64-i686-python2-pip 8.0.3-2 
It used to work correctly before I update all packages to the latest version.
I have already running the pacman -Sy and pacman -Su. The systems reports all my packages are up to date.
but when I running the pip, it always report:

> 
$ pip freeze
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip-script.py", line 9, in <module>
    load_entry_point('pip==8.0.3', 'console_scripts', 'pip')()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/index.py", line 29, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
>

**Comment by vladipus** [comment]
I recommend using the official Python builds, even under Mingw. You can also utilize the virtualenv tool, if needef.

**Comment by Alexpux** [comment]
This issue maybe related to new openssl build. Need to check.
@vladipus, we use our own Pyton build because:
1. We not depends on any 3rd party installations
2. It is relocatable. You don't need to set any environment variables
3. We can easily application with python library

**Comment by mattn** [comment]
Maybe same as https://github.com/Alexpux/MSYS2-packages/issues/482

**Comment by Alexpux** [comment]
We'll need to rebuild all pythons because of openssl changes

**Comment by Alexpux** [comment]
Fixed packages uploaded.
