### ISSUE TITLE
Openshadinglanguage build  segfault

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#4719]
Here is complete backtrace:

````
Program received signal SIGSEGV, Segmentation fault.
0x000000006fc6a0c9 in __cxxabiv1::__si_class_type_info::__do_dyncast (
    this=0x6fd359e0 <typeinfo for std::__cxx11::numpunct<char>>, src2dst=0,
    access_path=__cxxabiv1::__class_type_info::__contained_public,
    dst_type=0x6fd359e0 <typeinfo for std::__cxx11::numpunct<char>>,
    obj_ptr=0x6fd265c0 <(anonymous namespace)::numpunct_c>,
    src_type=0x6fd35580 <typeinfo for std::locale::facet>,
    src_ptr=0x6fd265c0 <(anonymous namespace)::numpunct_c>, result=...)
    at ../../../../gcc-8-20181123/libstdc++-v3/libsupc++/si_class_type_info.cc:51
51      {
(gdb) bt
#0  0x000000006fc6a0c9 in __cxxabiv1::__si_class_type_info::__do_dyncast (
    this=0x6fd359e0 <typeinfo for std::__cxx11::numpunct<char>>, src2dst=0,
    access_path=__cxxabiv1::__class_type_info::__contained_public,
    dst_type=0x6fd359e0 <typeinfo for std::__cxx11::numpunct<char>>,
    obj_ptr=0x6fd265c0 <(anonymous namespace)::numpunct_c>,
    src_type=0x6fd35580 <typeinfo for std::locale::facet>,
    src_ptr=0x6fd265c0 <(anonymous namespace)::numpunct_c>, result=...)
    at ../../../../gcc-8-20181123/libstdc++-v3/libsupc++/si_class_type_info.cc:51
#1  0x000000006fd25946 in __cxxabiv1::__dynamic_cast (
    src_ptr=0x6fd265c0 <(anonymous namespace)::numpunct_c>,
    src_type=0x6fd35580 <typeinfo for std::locale::facet>,
    dst_type=0x6fd359e0 <typeinfo for std::__cxx11::numpunct<char>>, src2dst=0)
    at ../../../../gcc-8-20181123/libstdc++-v3/libsupc++/dyncast.cc:71
#2  0x000000006fd1d17e in std::use_facet<std::__cxx11::numpunct<char> > (
    __loc=...)
    at C:/repo/mingw-w64-gcc/src/build-x86_64-w64-mingw32/x86_64-w64-mingw32/libstdc++-v3/include/bits/locale_classes.tcc:139
#3  0x0000000000d73c1a in OpenImageIO_v1_8::Strutil::strtof (
    nptr=nptr@entry=0x22d920 "180.0", endptr=endptr@entry=0x22d8c8)
    at /usr/src/debug/oiio-Release-1.8.16/src/libutil/strutil.cpp:1141
#4  0x0000000000d73c74 in OpenImageIO_v1_8::Strutil::strtof (
    nptr=nptr@entry=0x22d920 "180.0", endptr=endptr@entry=0x22d8c8)
    at /usr/src/debug/oiio-Release-1.8.16/src/libutil/strutil.cpp:1144
    
...
...

#14380 0x0000000000d73c74 in OpenImageIO_v1_8::Strutil::strtof (
    nptr=nptr@entry=0x22d920 "180.0", endptr=endptr@entry=0x22d8c8)
    at /usr/src/debug/oiio-Release-1.8.16/src/libutil/strutil.cpp:1144
#14381 0x0000000000d73d4a in OpenImageIO_v1_8::Strutil::stof (
    s=0x22d920 "180.0", pos=pos@entry=0x0)
    at /usr/src/debug/oiio-Release-1.8.16/src/libutil/strutil.cpp:1218


#14382 0x0000000000d73dd5 in OpenImageIO_v1_8::Strutil::stof (s=...,
    pos=pos@entry=0x0)
    at C:/building/msys64/mingw64/include/c++/8.2.1/bits/basic_string.h:2290
#14383 0x000000006b273897 in OpenImageIO_v1_8::Strutil::from_string<float> (
    s=...) at C:/building/msys64/mingw64/include/OpenImageIO/string_view.h:301
#14384 osllex ()
    at /usr/src/debug/OpenShadingLanguage-Release-1.9.12/src/liboslcomp/osllex.l:234
#14385 0x000000006b26a5a5 in oslparse ()
    at /usr/src/debug/build-x86_64-w64-mingw32/src/liboslcomp/oslgram.cpp:1647


#14386 0x000000006b271e22 in OSL_v1_9::pvt::OSLCompilerImpl::osl_parse_buffer (
    this=this@entry=0xdb60ed0,
    preprocessed_buffer="#line 79 \"C:\\\\repo\\\\mingw-w64-openshadinglanguage\\\\19\\\\src\\\\OpenShadingLanguage-Release-1.9.12\\\\src\\\\shaders\\\\stdosl.h\"\nnormal degrees (normal x) { return x*(180.0/3.1415926535897932); }\nvector degree"...)
    at /usr/src/debug/OpenShadingLanguage-Release-1.9.12/src/liboslcomp/osllex.l:389
#14387 0x000000006b25bea9 in OSL_v1_9::pvt::OSLCompilerImpl::compile (
    this=0xdb60ed0, filename=...,
    options=std::vector of length 7, capacity 8 = {...}, stdoslpath=...)
    at /usr/src/debug/OpenShadingLanguage-Release-1.9.12/src/liboslcomp/oslcomp.cpp:554
#14388 0x000000006b25c5f2 in OSL_v1_9::OSLCompiler::compile (
    this=this@entry=0x22fd98, filename=...,
    options=std::vector of length 7, capacity 8 = {...}, stdoslpath=...)
    at C:/building/msys64/mingw64/include/OpenImageIO/string_view.h:301
#14389 0x0000000000401bc9 in main (argc=9, argv=0xdb60260)
    at C:/building/msys64/mingw64/include/OpenImageIO/string_view.h:301
````

Problem is from function in OpenImageIO:
````
float
Strutil::strtof (const char *nptr, char **endptr)
{
    // Can use strtod_l on platforms that support it
#if defined (__linux__) || defined(__APPLE__) || defined(__FreeBSD__) || defined(__FreeBSD_kernel__) || defined(__GLIBC__)
    // static initialization inside function is thread-safe by C++11 rules!
    static locale_t c_loc = newlocale(LC_ALL_MASK, "C", nullptr);
# ifdef __APPLE__
    // On OSX, strtod_l is for some reason drastically faster than strtof_l.
    return static_cast<float>(strtod_l (nptr, endptr, c_loc));
# else
    return strtof_l (nptr, endptr, c_loc);
# endif
#elif defined (_MSC_VER)
    // Windows has _strtod_l
    static _locale_t c_loc = _create_locale(LC_ALL, "C");
    return static_cast<float>(_strtod_l (nptr, endptr, c_loc));
#else
    // On platforms without strtof_l...
    std::locale native; // default ctr gets current global locale
    char nativepoint = std::use_facet<std::numpunct<char>>(native).decimal_point();
    // If the native locale uses decimal, just directly use strtof.
    if (nativepoint == '.')
        return strtof (nptr, endptr);
    // Complex case -- CHEAT by making a copy of the string and replacing
    // the decimal, then use system strtof!
    std::string s (nptr);
    const char* pos = strchr (nptr, nativepoint);
    if (pos) {
        s[pos-nptr] = nativepoint;
        auto d = strtof (s.c_str(), endptr);
        if (endptr)
            *endptr = (char *)nptr + (*endptr - s.c_str());
        return d;
    }
    // No decimal point at all -- use regular strtof
    return strtof (s.c_str(), endptr);
#endif
````

Function ```` _create_locale```` present in mingw0w64 import library but doesnt present in ````msvcrt.dll```` in Win7

**Comment by MehdiChinoune** [comment]
closing since the package has been updated
