### ISSUE TITLE
Running MINGW shell through SSH causes build failure

### ISSUE THREAD

**Issue by Isopod** [msys2/MINGW-packages#5632]
I am trying to use MSYS2 over SSH with the native Windows 10 OpenSSH server (shipped by Microsoft). After logging in via SSH, I launch the shell like this:
```
set MSYSTEM=MINGW64
C:/msys64/usr/bin/bash.exe --login
```
At first glance it seems to work, but I get a weird error when trying to build a package:
```
makepkg -s
```
```
[...]
[75/1263] Generating Gdk-3.0.gir with a custom command.
FAILED: gdk/Gdk-3.0.gir 
"C:/msys64/mingw64/bin/g-ir-scanner.EXE" "-pthread" "-mms-bitfields" "-IC:/msys64/mingw64/include/gobject-introspection-1.0" "-IC:/msys64/mingw64/include" "-IC:/msys64/mingw64/lib/libffi-3.2.1/include" "-IC:/msys64/mingw64/include/glib-2.0" "-IC:/msys64/mingw64/lib/glib-2.0/include" "-IC:/msys64/mingw64/include" "--no-libtool" "--namespace=Gdk" "-

-nsversion=3.0" "--warn-all" "--output" "gdk/Gdk-3.0.gir" "--c-include=gdk/gdk.h" "--quiet" "-DGDK_COMPILATION" "-IC:/builds/isopod/gtk3-build/src/gtk+-3.24.9/gdk" "-IC:/builds/isopod/gtk3-build/src/build-x86_64/gdk" "-I./." "-I../gtk+-3.24.9/." "-I./gdk/x11" "-I../gtk+-3.24.9/gdk/x11" "-I./gdk/." "-I../gtk+-3.24.9/gdk/." "--filelist=C:/builds/isopod/gtk3-build/src/build-x86_64/gdk/ffe01f7@@gdk-3@sha/Gdk_3.0_gir_filelist" "--include=cairo-1.0" "--include=Gio-2.0" "--include=GdkPixbuf-2.0" "--include=Pango-1.0" "--symbol-prefix=gdk" "--identifier-prefix=Gdk" "--pkg-export=gdk-3.0" "--cflags-begin" "-DG_LOG_USE_STRUCTURED=1" "-DGLIB_MIN_REQUIRED_VERSION=GLIB_VERSION_2_52" "-DGLIB_MAX_ALLOWED_VERSION=GLIB_VERSION_2_54" "-DGTK_VERSION=\"3.24.9\"" "-D_GNU_SOURCE" "-I./." "-I../gtk+-3.24.9/." "-I./gdk/x11" "-I../gtk+-3.24.9/gdk/x11" "-I./gdk/." "-I../gtk+-3.24.9/gdk/." "-IC:/msys64/mingw64/include/gdk-pixbuf-2.0" "-IC:/msys64/mingw64/include/libpng16" "-IC:/msys64/mingw64/include" "-IC:/msys64/mingw64/lib/libffi-3.2.1/include" "-IC:/msys64/mingw64/include/glib-2.0" "-IC:/msys64/mingw64/lib/glib-2.0/include" "-IC:/msys64/mingw64/include/cairo" "-IC:/msys64/mingw64/include/pixman-1" "-IC:/msys64/mingw64/include/freetype2" "-IC:/msys64/mingw64/include/harfbuzz" "-IC:/msys64/mingw64/include/pango-1.0" "-IC:/msys64/mingw64/include/fribidi" "-IC:/msys64/mingw64/include/gio-win32-2.0" "-DG_ENABLE_DEBUG" "--cflags-end" "--library" "gdk-3" "-LC:/builds/isopod/gtk3-build/src/build-x86_64/gdk" "--extra-library=m" "-LC:/msys64/mingw64/lib" "--extra-library=gdk_pixbuf-2.0" "--extra-library=gobject-2.0" "--extra-library=intl" "--extra-library=glib-2.0" "--extra-library=cairo" "--extra-library=pango-1.0" "--extra-library=fribidi" "--extra-library=cairo-gobject" "--extra-library=epoxy" "--extra-library=gmodule-2.0" "--extra-library=gio-2.0" "--extra-library=pangocairo-1.0" "--extra-library=advapi32" "--extra-library=comctl32" "--extra-library=dwmapi" "--extra-library=imm32" "--extra-library=setupapi" "--extra-library=winmm" "--extra-library=pangowin32-1.0" "--sources-top-dirs" "C:/builds/isopod/gtk3-build/src/gtk+-3.24.9/subprojects/" "--sources-top-dirs" "C:/builds/isopod/gtk3-build/src/build-x86_64/subprojects/"
Microsoft Windows [Version 10.0.18362.30]
(c) 2019 Microsoft Corporation. All rights reserved.

user@WIN10 C:\builds\isopod\gtk3-build\src\build-x86_64>gdk/gdkversionmacros.h:35: Warning: Gdk: multiple comment blocks documenting 'GDK_DISABLE_DEPRECATION_WARNINGS:' identifier (already seen at gdk.c:107).
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\g-ir-scanner-script.py", line 93, in <module>
    sys.exit(scanner_main(sys.argv))
  File "C:/msys64/mingw64/lib/gobject-introspection\giscanner\scannermain.py", line 580, in scanner_main
    shlibs = create_binary(transformer, options, args)
  File "C:/msys64/mingw64/lib/gobject-introspection\giscanner\scannermain.py", line 421, in create_binary
    gdump_parser.parse()
  File "C:/msys64/mingw64/lib/gobject-introspection\giscanner\gdumpparser.py", line 110, in parse
    tree = self._execute_binary_get_tree()
  File "C:/msys64/mingw64/lib/gobject-introspection\giscanner\gdumpparser.py", line 183, in _execute_binary_get_tree
    subprocess.check_call(args, stdout=sys.stdout, stderr=sys.stderr)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:/msys64/mingw64/lib/python3.7\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```

Note that **the same build completes successfully** when launched from a local shell started by double-clicking on `C:\msys64\mingw64.exe`. I made a [step-by-step illustration](https://user-images.githubusercontent.com/2358109/61714589-823a5180-ad5b-11e9-8392-d00dd287ebae.png) to show what I did in both cases.

Here are the full logs of both the successful and the failed run:
* [log-good.txt](https://github.com/msys2/MINGW-packages/files/3422159/log-good.txt) (via local MINGW64 terminal)
* [log-bad.txt](https://github.com/msys2/MINGW-packages/files/3422160/log-bad.txt) (via SSH)

This is the package I am trying to build:
* [gtk3-build.zip](https://github.com/msys2/MINGW-packages/files/3422177/gtk3-build.zip)

(It is basically the same as the GTK3 package shipped by MSYS2, just with an additional patch, which shouldn't matter here. I don't want to rebuild everything yet again with the stock GTK3 because it takes forever. I am very certain that the same problem will also occur with the stock PKGBUILD.)

**Comment by mati865** [comment]
You should build mingw packages under MSYS2 shell and run `makepkg-mingw` instead of `makepkg`.

**Comment by Isopod** [comment]
Thanks, unfortunately the result is the same.  
* [msys-log.txt](https://github.com/msys2/MINGW-packages/files/3422432/msys-log.txt)

**Comment by TidbitSoftware** [comment]
@Isopod Just happened upon this looking for something else, and it may be too late, perhaps something is missing in your default profile/environment when logging in via SSH (i.e. .bashrc or .bash_profile might not be sourced; ans exported variable is not being passed to a child process)?
