### ISSUE TITLE
python2-matplotlib: ImportError: Failed to import any qt binding

### ISSUE THREAD

**Issue by smalltalkman** [msys2/MINGW-packages#5750]
After installing matplotlib via `pacman -S mingw-w64-{i686,x86_64}-python2-matplotlib`, execute `import matplotlib.pyplot as plt` in python2 with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:/gym/softwares/msys64/mingw32/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 168, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```
and
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 63, in pylab_setup
    [backend_name], 0)
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "D:/gym/softwares/msys64/mingw64/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 168, in <module>
    raise ImportError("Failed to import any qt binding")
ImportError: Failed to import any qt binding
```

**Comment by lazka** [comment]
We've dropped all Python 2 packages because Python 2 is EOL. Sorry :/
