### ISSUE TITLE
python2 crashes on PyQt5.QtCore import

### ISSUE THREAD

**Issue by mlperini** [msys2/MINGW-packages#5770]
mingw64/bin/python2 cannot import PyQt5.QtCore

```
$ /mingw64/bin/python2
Python 2.7.16 (default, Aug 15 2019, 17:51:40)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5.QtCore
Segmentation fault

```

This started recently. Folks on my team who've updated recently have the same issue.

I've traced it in GDB, but I have limited experience with building MSYS2 packages for debugging, so it's limited to the stock stacktrace:

```
(gdb) bt
#0  0x0000000066947c89 in QEventDispatcherWin32::event(QEvent*) ()
   from c:\msys64\mingw64\bin\Qt5Core.dll
#1  0x00000000667da90c in QString::fromUtf16(unsigned short const*, int) ()
   from c:\msys64\mingw64\bin\Qt5Core.dll
#2  0x000000006f22921a in initQtCore ()
   from C:\msys64\mingw64\lib\python2.7\site-packages\PyQt5\QtCore.pyd
#3  0x000000006f2292ca in initQtCore ()
   from C:\msys64\mingw64\lib\python2.7\site-packages\PyQt5\QtCore.pyd
#4  0x000000006f0c15c8 in ?? ()
   from C:\msys64\mingw64\lib\python2.7\site-packages\PyQt5\QtCore.pyd
#5  0x000000006cef7017 in libpython2.7!PyImport_AppendInittab ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#6  0x000000006cef5130 in libpython2.7!PyImport_ImportFrozenModule ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#7  0x000000006cef5394 in libpython2.7!PyImport_ImportFrozenModule ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#8  0x000000006cef5d86 in libpython2.7!PyImport_ImportModuleLevel ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#9  0x000000006ced9460 in libpython2.7!PyAST_FromNode ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#10 0x000000006ce4bea1 in libpython2.7!PyObject_Call ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#11 0x000000006cedb339 in libpython2.7!PyEval_CallObjectWithKeywords ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#12 0x000000006cedef99 in libpython2.7!PyEval_EvalFrameEx ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#13 0x000000006cee48ae in libpython2.7!PyEval_EvalCodeEx ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#14 0x000000006cee4a8f in libpython2.7!PyEval_EvalCode ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#15 0x000000006cefd5b4 in libpython2.7!PyGILState_Release ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#16 0x000000006ceffdef in libpython2.7!PyRun_InteractiveOneFlags ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#17 0x000000006cefff7e in libpython2.7!PyRun_InteractiveLoopFlags ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#18 0x000000006cf005be in libpython2.7!PyRun_AnyFileExFlags ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#19 0x000000006cf10cdf in libpython2.7!Py_Main ()
   from c:\msys64\mingw64\bin\libpython2.7.dll
#20 0x000000000040138c in ?? ()
#21 0x00000000004014bb in ?? ()
#22 0x00007ff9bf3f7974 in KERNEL32!BaseThreadInitThunk ()
   from C:\Windows\System32\kernel32.dll
#23 0x00007ff9c05ca271 in ntdll!RtlUserThreadStart ()
   from C:\Windows\SYSTEM32\ntdll.dll
#24 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 

```

Hope someone can tell what's gone wrong.

Thanks
Matt

**Comment by lazka** [comment]
python2 is no longer supported and all libraries have been removed.
