### ISSUE TITLE
python: sqlite 3.30 breaks python package

### ISSUE THREAD

**Issue by lovetox** [msys2/MINGW-packages#5847]
```
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.7\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:/msys64/mingw64/lib/python3.7\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: Die angegebene Prozedur wurde nicht gefunden.
>>>

```

i guess python package has to be rebuild?

**Comment by lazka** [comment]
sqlite3_enable_shared_cache, sqlite3_progress_handler and sqlite3_trace seem to be missing now.

**Comment by lazka** [comment]
Looks like this was disabled in da77e76b03a7ec @Alexpux any reason for that?

**Comment by lazka** [comment]
I've opened #5851
