### ISSUE TITLE
Issues with python3-pip

### ISSUE THREAD

**Issue by Ede123** [msys2/MINGW-packages#5889]
Just updated to "mingw-w64-x86_64-python3-pip 19.3.1-1" and found some issues.

Are these related to the Python 3.8 update or to 7712a7476f35aafa8695c7ab1dafa60e36b7f407 @lazka (the second issue references contextlib2).

While installing:
```
sed: C:/msys64/mingw64/bin/pip3.7-script.py kann nicht gelesen werden: No such file or directory
Error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_3NJqTi/.INSTALL; post_upgrade 19.3.1-1 19.2.3-1 ) failed to execute correctly
```

After installing, when calling `pip3 show`
```
$ pip3 show
Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\pip3-script.py", line 11, in <module>
    load_entry_point('pip==19.3.1', 'console_scripts', 'pip3')()
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pip\_internal\main.py", line 45, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pip\_internal\commands\__init__.py", line 96, in create_command
    module = importlib.import_module(module_path)
  File "C:/msys64/mingw64/lib/python3.8\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pip\_internal\commands\show.py", line 13, in <module>
    from pip._internal.cli.base_command import Command
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pip\_internal\cli\base_command.py", line 14, in <module>
    from pip._internal.cli.command_context import CommandContextMixIn
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pip\_internal\cli\command_context.py", line 6, in <module>
    from pip._vendor.contextlib2 import ExitStack
ModuleNotFoundError: No module named 'pip._vendor.contextlib2'
```

**Comment by lazka** [comment]
> Are these related to the Python 3.8 update or to [7712a74](https://github.com/msys2/MINGW-packages/commit/7712a7476f35aafa8695c7ab1dafa60e36b7f407) @lazka (the second issue references contextlib2).

yeah, that commit fixes the error (once it's in the repo)

**Comment by lazka** [comment]
Things should work again.

**Comment by Ede123** [comment]
Thanks, fix confirmed.
