### ISSUE TITLE
mingw-w64-python-jsonschema dependencies

### ISSUE THREAD

**Issue by phrrk** [msys2/MINGW-packages#6051]
Hi,
I did report an issue about a month ago about python-jsonschema dependencies (#5949).  This was partially corrected by #5950, but it seems that the unsatisfied dependency upon importlib_metadata remains.  The report below is from a new MSYS installation made yesterday, and I  believe it was fully up to date.

Jim

Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\jsonschema-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3251, in <module>
    def _initialize_master_working_set():
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:/msys64/mingw64/lib/python3.8/site-packages\pkg_resources\__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by jsonschema

**Comment by lazka** [comment]
try now

**Comment by phrrk** [comment]
looks good.

Thanks
