### ISSUE TITLE
mingw-w64-i686-python3-pip: error on run

### ISSUE THREAD

**Issue by sergpolkin** [msys2/MINGW-packages#6055]
Fresh installed MSYS2 on Windows7
```
$ uname -a
MINGW32_NT-6.1-7601 w7-vm 3.0.7-338.i686 2019-07-11 11:17 UTC i686 Msys
```
```
$ pip3
Traceback (most recent call last):
  File "C:/msys32/mingw32/lib/python3.8/site-packages\appdirs.py", line 560, in <module>
    import win32com.shell
ModuleNotFoundError: No module named 'win32com'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys32\mingw32\bin\pip3-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "C:/msys32/mingw32/lib/python3.8/site-packages\pkg_resources\__init__.py", line 80, in <module>
    import appdirs
  File "C:/msys32/mingw32/lib/python3.8/site-packages\appdirs.py", line 564, in <module>
    from ctypes import windll
  File "C:/msys32/mingw32/lib/python3.8\ctypes\__init__.py", line 453, in <module>
    pythonapi = PyDLL("libpython%d.%d%s.dll" % (_sys.version_info[:2] + (_sys.abiflags,)), None)
  File "C:/msys32/mingw32/lib/python3.8\ctypes\__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] The parameter is incorrect
```
i missed some packages?

**Comment by lazka** [comment]
Is your Win7 updated?

**Comment by sergpolkin** [comment]
Yes, this is because of the old version.
`KB2533623 update is required to continue.`

**Comment by lazka** [comment]
ok, thanks for confirming!
