### ISSUE TITLE
python-gmpy2: Error on import

### ISSUE THREAD

**Issue by logiconcepts819** [msys2/MINGW-packages#6058]
In the 64-bit MinGW environment, importing the gmpy2 module results in the error shown below.

```
logic@LAPTOP-0OF3O041 MINGW64 ~
$ /mingw64/bin/python3
Python 3.8.0 (default, Oct 25 2019, 06:23:40)  [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpy2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python3.8/site-packages\gmpy2\__init__.py", line 1, in <module>
    from .gmpy2 import *
SystemError: Size of PY_LONG_LONG and mp_bitcnt_t not compatible (_WIN64 && MPIR)
```

The build guides for MSYS2 in the gmpy and gmpy2 repos suggest changing mp_bitcnt_t from unsigned long to unsigned long long for 64-bit builds:

```
# Compile GMP
  $ cd gmp-6.1.2/
  $ ./configure --prefix=/mingw64/opt --enable-static --disable-shared --enable-fat --with-pic

    *Experimental for mingw64 build*

    mp_bitcnt_t should really be a 64-bit unsigned integer. The following sed
    command makes the change. It should only be used for 64-bit builds.

    This will require changes to gmpy2 source also. See gmpy2_convert_utils.h.

  $ mv gmp.h gmp.h.original
  $ sed 's/typedef\s*unsigned\s*long\s*int\s*mp_bitcnt_t/typedef unsigned long long int  mp_bitcnt_t/g' gmp.h.original > gmp.h
```

**Comment by lazka** [comment]
PR welcome

**Comment by lazka** [comment]
I've reported this upstream: https://github.com/aleaxit/gmpy/issues/268
