### ISSUE TITLE
Asciidoctor does not work

### ISSUE THREAD

**Issue by angelog0** [msys2/MINGW-packages#6264]
Trying to rebuild some docs 

```
$ asciidoctor tee-5A.adoc
C:/msys64/mingw64/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
        from C:/msys64/mingw64/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
        from C:/msys64/mingw64/bin/asciidoctor:23:in `<main>'

```
from MinTTY-MINGW64.

I would suggest to remove this package, it never worked...

**Comment by Alexpux** [comment]
Probably it need to be rebuilded for ruby  2.7

**Comment by Alexpux** [comment]
@angelog0 try it again after packages updates

**Comment by angelog0** [comment]
Now it seems to work. Thanks.
