### ISSUE TITLE
libvirt possibly require changes to portablexdr

### ISSUE THREAD

**Issue by Alexpux** [msys2/MINGW-packages#6384]
libvirt not building anymore. During build I have error:
````
..\\/..\\/libvirt-6.2.0\\/src\\/logging\\/log_protocol.x:24: syntax error
cannot shutdown /mingw64/bin/portable-rpcgen -o -:  at ../../libvirt-6.2.0/src/rpc/genprotocol.pl line 140.
````

From log.protocol.x:
````
21  struct virLogManagerProtocolDomain {
22     virLogManagerProtocolUUID uuid;
23     virLogManagerProtocolNonNullString name;
24  };
25  typedef struct virLogManagerProtocolDomain virLogManagerProtocolDomain;
26  
27  struct virLogManagerProtocolLogFilePosition {
28      unsigned hyper inode;
29      unsigned hyper offset;
30  };
31  typedef struct virLogManagerProtocolLogFilePosition virLogManagerProtocolLogFilePosition;

````

@rwmjones do you have ideas?

**Comment by rwmjones** [comment]
Hello Alexsey, the answer is I don't know.  I forwarded the question to the libvirt team: https://www.redhat.com/archives/libvir-list/2020-April/msg00640.html

**Comment by zippy2** [comment]
There was no change nor in log_protocol.x nor in genprotocol.pl for quite some time now. I wonder if it is portable-rpcgen that changed.

**Comment by Alexpux** [comment]
@rwmjones ok thanks!

**Comment by Alexpux** [comment]
@zippy2 portablexdr not changed for a years

**Comment by rwmjones** [comment]
Right, we haven't changed portablexdr for years.  It may be better for the build not to try rebuilding the .c and .h files at all.  I wonder if the generated files are no longer shipped with the tarball or something like that.

**Comment by berrange** [comment]
When was the last successful build of libvirt with msys2 ?   We had major build system changes in 6.1.0 which purged GNULIB, and msys2 is not a supported build env from libvirt upstream POV, so there's easily a chance that it was broken by this.

mingw64 (on Fedora) is the only Windows build platform combo we actively test & supported.

It would be useful to validate previous releases of libvirt to determine whether this is a regression libvirt, or a regression in the msys build environment

**Comment by Alexpux** [comment]
@berrange  last successful build was 5.9.0

**Comment by berrange** [comment]
In 5.10.0 release, we stopped including any non-autotools related auto-generated source files in the release tarballs.  Thus in 5.9.0 you used the files for RPC protocol from the tarball, where as in 5.10.0 and later you need to run rpcgen to create them.

**Comment by berrange** [comment]
I would also note that when libvirt only aims to support cross-compiled builds for Windows, so when we're doing mingw32/64 builds of libvirt in our CI system, although we're linking to portablexdr, we're using the native rpcgen, not the portablexdr rpcgen.

When I attempt to run portable-rpcgen with libvirt I see the same failure you report in the initial issue description. Some debugging shows portable-rpcgen is crashing

```
$ gdb --args /home/berrange/usr/portablexdr/bin/portable-rpcgen -o -  -h  ../../src/locking/lock_protocol.x
[Detaching after vfork from child process 64976]
/* This file was generated by PortableXDR rpcgen 4.9.1
 * ANY CHANGES YOU MAKE TO THIS FILE MAY BE LOST!
 * The input file was ../../src/locking/lock_protocol.x
 */


Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f1665b in __strrchr_avx2 () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7f1665b in __strrchr_avx2 () from /lib64/libc.so.6
#1  0x000000000040424c in write_basename_caps () at rpcgen_codegen.c:76
#2  0x0000000000404bf0 in gen_prologue (filename=<optimized out>) at rpcgen_codegen.c:109
#3  0x0000000000403dc9 in do_rpcgen (filename=0x7fffffffd80f "../../src/locking/lock_protocol.x", out=<optimized out>) at rpcgen_main.c:226
#4  0x00000000004013e1 in main (argc=5, argv=0x7fffffffd3f8) at rpcgen_main.c:122

```

So AFAICT,  portable-rpcgen is broken when telling it to use "-o -" to write to stdout, because "output_filename" is NULL when write_basename_caps tries to call strchr on it.

**Comment by Biswa96** [comment]
Would anyone like to check the linked pull request? It adds rpcsvc-proto package which provides rpcgen program. With that I was able to compile libvirt master branch.
