### ISSUE TITLE
[BUG] Python ctypes.util is broken

### ISSUE THREAD

**Issue by keder** [msys2/MINGW-packages#6388]
Encountered an error trying to build llvm project in mingw environment:
```
cd /D/llvm_10.0.0_Release_mingw_x86_64/projects/libcxx/src && /D/msys2/mingw64/bin/python.exe D:/llvm/10.0.0/llvm/projects/libcxx/utils/merge_archives.py -o D:/llvm_10.0.0_Release_mingw_x86_64/lib/libc++.a --ar D:/msys2/mingw64/
bin/ar.exe D://llvm_10.0.0_Release_mingw_x86_64/lib/libc++.a D:/llvm_10.0.0_Release_mingw_x86_64/lib/libc++abi.a
Traceback (most recent call last):
  File "D:/via/external/llvm/10.0.0/llvm/projects/libcxx/utils/merge_archives.py", line 11, in <module>
    from ctypes.util import find_library
  File "D:/msys2/mingw64/lib/python3.8/ctypes/__init__.py", line 457, in <module>
    pythonapi = PyDLL("libpython%d.%d%s.dll" % (_sys.version_info[:2] + (_sys.abiflags,)), None)
  File "D:/msys2/mingw64/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] The parameter is incorrect
```
Similarly in python console:
```python
Python 3.8.2 (default, Apr  9 2020, 13:17:39)  [GCC 9.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:/msys2/mingw64/lib/python3.8/ctypes/__init__.py", line 457, in <module>
    pythonapi = PyDLL("libpython%d.%d%s.dll" % (_sys.version_info[:2] + (_sys.abiflags,)), None)
  File "D:/msys2/mingw64/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 87] The parameter is incorrect
```

**Comment by Alexpux** [comment]
I’m build llvm few days ago without problem

**Comment by keder** [comment]
Well, problem is in python module, probably you have used older python version to build. I have made clean reinstall of msys, updated all packages, installed `mingw64/mingw-w64-x86_64-python` and problem still persists.

**Comment by keder** [comment]
And I use Windows 7 as host system, by the way.

**Comment by Alexpux** [comment]
@keder I’m build llvm with latest packages because all packages in repo are builded myself. You can see that our llvm package depends on libffi-7.dll

**Comment by Alexpux** [comment]
@keder here is my output from cmd:
````
D:\msys64\mingw64\bin>python
Python 3.8.2 (default, Apr  9 2020, 13:17:39)  [GCC 9.3.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ctypes.util import find_library
>>> 
````

**Comment by lazka** [comment]
@keder is your Windows 7 up to date? Python has dropped support for older Windows 7 with Python 3.8.

**Comment by lazka** [comment]
See https://github.com/msys2/MINGW-packages/issues/6055#issuecomment-568063612 for which Windows patch you need to install.

**Comment by keder** [comment]
Indeed, KB2533623 fixes this problem. Thank you!
