### ISSUE TITLE
libxml2 x86 tests fail over: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by salowenh** [msys2/MINGW-packages#6675]
Passes on x64.

```
make[2]: Entering directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-i686/python/tests'
## running Python regression tests
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 80, in <module>
    test.test1()
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 54, in test1
    self.failUnlessXmlError(libxml2.readFile,
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 30, in failUnlessXmlError
    f(*args)
  File "C:/dev/MINGW-packages/mingw-w64-libxml2/src/libxml2-2.9.10/python/libxml2.py", line 1374, in readFile
    ret = libxml2mod.xmlReadFile(filename, encoding, options)
SystemError: <built-in function xmlReadFile> returned a result with an error set
-- tstLastError.py

make[2]: *** [Makefile:672: tests] Error 1
make[2]: Leaving directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-i686/python/tests'
make[1]: *** [Makefile:997: tests] Error 2
make[1]: Leaving directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-i686/python'
make: *** [Makefile:2104: runtests] Error 2
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by Biswa96** [comment]
Looks like it should be reported to upstream repository.

**Comment by salowenh** [comment]
Thanks. Will do that. any way to skip the tests?

**Comment by Biswa96** [comment]
The checks can be skipped with `makepkg-mingw --nocheck` command.

**Comment by lazka** [comment]
@salowenh thanks for reporting it upstream.

Let's close this then.
