### ISSUE TITLE
Cannot use any pip

### ISSUE THREAD

**Issue by kovalp** [msys2/MINGW-packages#6739]
```
koval@DESKTOP-B5CLTB9 MINGW64 ~
$ pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    load_entry_point('pip==20.1.1', 'console_scripts', 'pip')()
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "/usr/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "/usr/lib/python3.8/site-packages/pip/_internal/index/collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "/usr/lib/python3.8/site-packages/pip/_vendor/requests/__init__.py", line 43, in <module>
    from pip._vendor import urllib3
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connection.py", line 68, in <module>
    class HTTPConnection(_HTTPConnection, object):
  File "/usr/lib/python3.8/site-packages/pip/_vendor/urllib3/connection.py", line 96, in HTTPConnection
    default_socket_options = [(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)]
AttributeError: module 'socket' has no attribute 'TCP_NODELAY'

```

**Comment by 1480c1** [comment]
perhaps try updating python?

https://github.com/msys2/MSYS2-packages/issues/2050

**Comment by Biswa96** [comment]
It was added in msys2/python package, maybe not in the mingw-64-python one.

**Comment by 1480c1** [comment]
based on seeing `/usr/bin/pip` I think he is using the msys2 one

**Comment by kovalp** [comment]
I freshly installed python

`pacman -S python
`
then 

`pacman -S python-pip
`
and then I could not run pip.

**Comment by 1480c1** [comment]
can you print the output of 
```bash
command -v python
python --version
pip --version
```
?

**Comment by kovalp** [comment]
```

koval@DESKTOP-B5CLTB9 MSYS ~
$ command -v python
/usr/bin/python

koval@DESKTOP-B5CLTB9 MSYS ~
$ python --version
Python 3.8.5

koval@DESKTOP-B5CLTB9 MSYS ~
$ pip --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8)

koval@DESKTOP-B5CLTB9 MSYS ~

```

**Comment by kovalp** [comment]
Is it difficult to reproduce? Can I provide any other info perhaps?

**Comment by 1480c1** [comment]
Hmm, the versions I currently have
```bash
cddeg@DESKTOP-VUQFBCN MSYS ~
$ command -v python
/usr/bin/python

cddeg@DESKTOP-VUQFBCN MSYS ~
$ python --version
Python 3.8.5

cddeg@DESKTOP-VUQFBCN MSYS ~
$ pip --version
pip 20.2 from /usr/lib/python3.8/site-packages/pip (python 3.8)
```
Now, obviously, the answer would be to try to upgrade pip, but as you have shown in the opening text, that's what you were doing.

Could you try doing `pacman -R python-pip` and then `pacman -Syy` and `pacman -S python-pip`?

**Comment by kovalp** [comment]
```
I am also wondering about the old version of pip. Doing the commands you suggested, pacman still installs python-pip-20.1.1-1

koval@DESKTOP-B5CLTB9 MSYS ~
$ pacman -R python-pip
checking dependencies...

Packages (1) python-pip-20.1.1-1

Total Removed Size:  7.55 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/1) removing python-pip                                                             [#################################################] 100%

koval@DESKTOP-B5CLTB9 MSYS ~
$ pacman -Syy
:: Synchronizing package databases...
 mingw32                                                  472.5 KiB   191 KiB/s 00:02 [#################################################] 100%
 mingw32.sig                                              438.0   B  0.00   B/s 00:00 [#################################################] 100%
 mingw64                                                  475.0 KiB   233 KiB/s 00:02 [#################################################] 100%
 mingw64.sig                                              438.0   B  0.00   B/s 00:00 [#################################################] 100%
 msys                                                     189.8 KiB   455 KiB/s 00:00 [#################################################] 100%
 msys.sig                                                 438.0   B  0.00   B/s 00:00 [#################################################] 100%

koval@DESKTOP-B5CLTB9 MSYS ~
$ pacman -S python-pip
resolving dependencies...
looking for conflicting packages...

Packages (1) python-pip-20.1.1-1

Total Installed Size:  7.55 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                        [#################################################] 100%
(1/1) checking package integrity                                                      [#################################################] 100%
(1/1) loading package files                                                           [#################################################] 100%
(1/1) checking for file conflicts                                                     [#################################################] 100%
(1/1) checking available disk space                                                   [#################################################] 100%
:: Processing package changes...
(1/1) installing python-pip                                                           [#################################################] 100%


```

**Comment by 1480c1** [comment]
```bash
cddeg@DESKTOP-VUQFBCN MSYS ~
$ pacman -R python-pip
checking dependencies...

Packages (1) python-pip-20.1.1-1

Total Removed Size:  7.55 MiB

:: Do you want to remove these packages? [Y/n] Y
:: Processing package changes...
(1/1) removing python-pip                                                                                                                                          [####################################################################################################] 100%

cddeg@DESKTOP-VUQFBCN MSYS ~
$ pacman -S python-pip
resolving dependencies...
looking for conflicting packages...

Packages (1) python-pip-20.1.1-1

Total Installed Size:  7.55 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                                                                                                     [####################################################################################################] 100%
(1/1) checking package integrity                                                                                                                                   [####################################################################################################] 100%
(1/1) loading package files                                                                                                                                        [####################################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                                  [####################################################################################################] 100%
(1/1) checking available disk space                                                                                                                                [####################################################################################################] 100%
:: Processing package changes...
(1/1) installing python-pip                                                                                                                                        [####################################################################################################] 100%

cddeg@DESKTOP-VUQFBCN MSYS ~
$ command -v pip
/usr/bin/pip

cddeg@DESKTOP-VUQFBCN MSYS ~
$ pip --version
pip 20.1.1 from /usr/lib/python3.8/site-packages/pip (python 3.8

cddeg@DESKTOP-VUQFBCN MSYS ~
$ pip install --upgrade pip
Collecting pip
  Using cached pip-20.2-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-20.2
```
now this is even more confusing, could you perhaps do the same pacman commands just with python instead of python-pip?

**Comment by kovalp** [comment]
Doing this with python updated the version of python from python-3.8.5-1 to python-3.8.5-2. Subsequent installation of python-pip still resulted in an outdated version of pip python-pip-20.1.1-1. However, this pip was operational, so I could do 
```
pip install --upgrade pip
Collecting pip
  Downloading pip-20.2-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.6 MB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.1.1
    Uninstalling pip-20.1.1:
      Successfully uninstalled pip-20.1.1
Successfully installed pip-20.2

```
Voilà.

Thank you!
The issue is solved for me.

**Comment by 1480c1** [comment]
Nice

**Comment by kovalp** [comment]
What is the policy about closing of the issues? Shall I close it?

**Comment by 1480c1** [comment]
I think so

**Comment by kovalp** [comment]
Thank you!
