### ISSUE TITLE
Please upgrade rust to 1.45.2

### ISSUE THREAD

**Issue by abcfy2** [msys2/MINGW-packages#6758]
New version 1.45.2 has been released: https://blog.rust-lang.org/2020/08/03/Rust-1.45.2.html. Please upgrade.

**Comment by omerakgoz34** [comment]
1.46.0 :'(
Why it's still out-dated?

**Comment by 1480c1** [comment]
probably because nobody has submitted an update pr and the current packagers are still busy trying to update the other packages as well

**Comment by 1480c1** [comment]
If you want to help, you can edit this file in a fork and open a pr for it https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-rust/PKGBUILD

The main changes should be to the pkgver and checking if the patch files are still needed, or if they need to be updated or if new patches need to be applied if something else broke. The final change of sha256sums can be autoupdated using updpkgsums 

@lazka or @Biswa96 can probably comment more since they know more about PKGBUILDS than I do

**Comment by lazka** [comment]
Someone needs to do the work.

**Comment by abcfy2** [comment]
I find rust support compile on MSYS2: https://github.com/rust-lang/rust#mingw

But I can't compile on my PC, anyone can help?

```shell
  ./x.py build
downloading https://static.rust-lang.org/dist/2020-08-03/rust-std-1.45.2-x86_64-pc-windows-gnu.tar.xz
extracting C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/build/cache/2020-08-03/rust-std-1.45.2-x86_64-pc-windows-gnu.tar.xz
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 981, in main
    bootstrap(help_triggered)
  File "C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 945, in bootstrap
    build.download_stage0()
  File "C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 386, in download_stage0
    self._download_stage0_helper(filename, pattern, tarball_suffix)
  File "C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 441, in _download_stage0_helper
    unpack(tarball, tarball_suffix, self.bin_root(), match=pattern, verbose=self.verbose)
  File "C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/src/bootstrap/bootstrap.py", line 123, in unpack
    tar.extract(member, dst)
  File "D:/msys64/mingw64/lib/python3.8/tarfile.py", line 2067, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "D:/msys64/mingw64/lib/python3.8/tarfile.py", line 2139, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "D:/msys64/mingw64/lib/python3.8/tarfile.py", line 2180, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/build/x86_64-pc-windows-gnu/stage0/rust-std-1.45.2-x86_64-pc-windows-gnu/rust-std-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_std-3ba04ca44a839e11.rlib'

```

**Comment by mati865** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/abcfy/projects/MINGW-packages/mingw-w64-rust/rustc-1.46.0-src/build/x86_64-pc-windows-gnu/stage0/rust-std-1.45.2-x86_64-pc-windows-gnu/rust-std-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/librustc_std_workspace_std-3ba04ca44a839e11.rlib'`

This path has 262 characters but Windows limits paths to 260 characters.

I've already opened https://github.com/msys2/MINGW-packages/pull/6932
