### ISSUE TITLE
libxml2 check() fails on msys 20200903

### ISSUE THREAD

**Issue by salowenh** [msys2/MINGW-packages#6950]
Building libxml2 fails on `check()`:
```
make[2]: Entering directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-x86_64/python/tests'
## running Python regression tests
TypeError: 'NoneType' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 80, in <module>
    test.test1()
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 54, in test1
    self.failUnlessXmlError(libxml2.readFile,
  File "../../../libxml2-2.9.10/python/tests/tstLastError.py", line 30, in failUnlessXmlError
    f(*args)
  File "C:/dev/MINGW-packages/mingw-w64-libxml2/src/libxml2-2.9.10/python/libxml2.py", line 1374, in readFile
    ret = libxml2mod.xmlReadFile(filename, encoding, options)
SystemError: <built-in function xmlReadFile> returned a result with an error set
-- tstLastError.py

make[2]: *** [Makefile:672: tests] Error 1
make[2]: Leaving directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-x86_64/python/tests'
make[1]: *** [Makefile:997: tests] Error 2
make[1]: Leaving directory '/c/dev/MINGW-packages/mingw-w64-libxml2/src/build-shared-x86_64/python'
make: *** [Makefile:2104: runtests] Error 2
[1m[31m==> ERROR:(B[m[1m A failure occurred in check().(B[m
[1m    Aborting...(B[m
```
Full log: [mingw-w64-libxml2-2.9.10-4-x86_64-check.log](https://github.com/msys2/MINGW-packages/files/5181958/mingw-w64-libxml2-2.9.10-4-x86_64-check.log)

**Comment by Biswa96** [comment]
1. Either jump into the code and solve the issue and upstream the changes.
2. or, use `--nocheck` option with `makepkg-mingw` to ignore the checks.

**Comment by salowenh** [comment]
Thanks @Biswa96 , I did use `--nocheck` to bypass but that's probably comes with some impact on the confidence in the build quality.  
I'll be happy to get into the code and try to fix it, it will require some onboarding time as I'm not familiar with it so it'll prbably take some time :D 
Opened an issue so it'll be known

**Comment by lazka** [comment]
See https://gitlab.gnome.org/GNOME/libxml2/-/issues/175

**Comment by lazka** [comment]
Feel free to look into debugging this, if not I'd suggest we leave this up to upstream.
