### ISSUE TITLE
[arm-none-eabi-gdb] Doesn't work due to faulty python paths

### ISSUE THREAD

**Issue by devjoa** [msys2/MINGW-packages#6997]
The 9.2-1 version doesn't work, due to faulty python paths.

Please change this PKGBUILD to match the standard MSYS2 MinGW GDB version [https://packages.msys2.org/package/mingw-w64-x86_64-gdb]

Everything works fine when I used the patches from the referenced PKGBUILD, and changed modified its build script:
```
_realname=gdb
_target=arm-none-eabi
pkgbase=mingw-w64-${_target}-${_realname}
pkgname="${MINGW_PACKAGE_PREFIX}-${_target}-${_realname}"
pkgver=9.2
pkgrel=2
pkgdesc="GNU Debugger (${_target})"
arch=('any')
url="https://www.gnu.org/software/gdb/"
license=('GPL')
groups=("${MINGW_PACKAGE_PREFIX}-${_target}-toolchain")
depends=("${MINGW_PACKAGE_PREFIX}-expat"
         "${MINGW_PACKAGE_PREFIX}-libiconv"
         "${MINGW_PACKAGE_PREFIX}-ncurses"
         "${MINGW_PACKAGE_PREFIX}-python"
         "${MINGW_PACKAGE_PREFIX}-readline"
         "${MINGW_PACKAGE_PREFIX}-xxhash"
         "${MINGW_PACKAGE_PREFIX}-zlib")
checkdepends=('dejagnu' 'bc')
makedepends=("${MINGW_PACKAGE_PREFIX}-iconv"
             "${MINGW_PACKAGE_PREFIX}-xz")
options=('staticlibs' '!distcc' '!ccache')
source=(https://ftp.gnu.org/gnu/gdb/${_realname}-${pkgver}.tar.xz{,.sig}
        'gdb-perfomance.patch'
        'gdb-fix-using-gnu-print.patch'
        'gdb-7.12-dynamic-libs.patch'
        'python-configure-path-fixes.patch'
        'gdb-fix-tui-with-pdcurses.patch'
        'gdb-9.1-lib-order.patch'
        'gdb-home-is-userprofile.patch'
        'gdb-windows-aslr.patch')
validpgpkeys=('F40ADB902B24264AA42E50BF92EDB04BFF325CF3')
sha256sums=('360cd7ae79b776988e89d8f9a01c985d0b1fa21c767a4295e5f88cb49175c555'
            'SKIP'
            'a0a2d974e80b656646c87cc669fda798182a35b001aab933567c41b880530aa0'
            '29fce74348a2862dd3856da58cd3c6c40a910cbdb95e5003d571c33a04532b78'
            '9de9c30bbb8cd2c6f60414b5a34cdf1fae27238293fb6007c628a8b821f88e0b'
            '6378e1a96e3bedc2a160f0f6780cb973ce6139017f2786e7ab97f8bcd9824d27'
            'f70cc0a0633d01adf777eb57a82f8c9880f6511d55e44c1dc415ddebc7467e0b'
            'dcfbfb2e3fc90a51e11202529e34c1b3dcc17e352067ffdfc58b63c1deab9523'
            'a63ba094dcd9bf0c0f98c6dce5825590b2cf7014834fd3bec5f88fe25d90228a'
            '7c40bd442dcd4eb32310b1b6979a96fd41253f4b3128ad0fac2f8ebff132666b')

prepare() {
  cd ${srcdir}/${_realname}-${pkgver}

  # https://sourceware.org/bugzilla/show_bug.cgi?id=15412
  patch -p1 -i ${srcdir}/gdb-perfomance.patch

  patch -p1 -i ${srcdir}/gdb-fix-using-gnu-print.patch

  # https://sourceware.org/bugzilla/show_bug.cgi?id=21078
  patch -p1 -i ${srcdir}/gdb-7.12-dynamic-libs.patch

  patch -p1 -i ${srcdir}/python-configure-path-fixes.patch

  patch -p1 -i ${srcdir}/gdb-fix-tui-with-pdcurses.patch
  patch -p1 -i ${srcdir}/gdb-9.1-lib-order.patch
  patch -p1 -i ${srcdir}/gdb-home-is-userprofile.patch

  # https://sourceware.org/bugzilla/show_bug.cgi?id=26037
  patch -p1 -i ${srcdir}/gdb-windows-aslr.patch

  # hack! - libiberty configure tests for header files using "$CPP $CPPFLAGS"
  sed -i "/ac_cpp=/s/\$CPPFLAGS/\$CPPFLAGS -O2/" libiberty/configure
}

build() {
  [[ -d ${srcdir}/build-${MINGW_CHOST}-${_target} ]] && rm -rf ${srcdir}/build-${MINGW_CHOST}-${_target}
  mkdir ${srcdir}/build-${MINGW_CHOST}-${_target} && cd ${srcdir}/build-${MINGW_CHOST}-${_target}
  
  if [ "${CARCH}" != "x86_64" ]; then
    LDFLAGS+=" -Wl,--large-address-aware"
  fi

  if check_option "debug" "y"; then
    CFLAGS+=" -O0"
    CXXFLAGS+=" -O0"
  fi
  

  CPPFLAGS+=" -I${MINGW_PREFIX}/include/ncurses"
  CFLAGS+=" -I${MINGW_PREFIX}/include/ncurses"
  CXXFLAGS+=" -I${MINGW_PREFIX}/include/ncurses"
  LDFLAGS+=" -fstack-protector"

  ../${_realname}-${pkgver}/configure \
    --build=${MINGW_CHOST} \
    --host=${MINGW_CHOST} \
    --target=${_target} \
    --prefix=${MINGW_PREFIX} \
    --enable-languages=c,c++ \
    --enable-64-bit-bfd \
    --disable-werror \
    --disable-win32-registry \
    --disable-rpath \
    --with-curses \
    --with-system-gdbinit=${MINGW_PREFIX}/etc/gdbinit \
    --with-system-readline \
    --with-python=${MINGW_PREFIX}/bin/python \
    --with-expat \
    --with-libiconv-prefix=${MINGW_PREFIX} \
    --with-zlib \
    --with-lzma \
    --enable-tui \
    --enable-source-highlight=no

  make
}

package() {
  cd ${srcdir}/build-${MINGW_CHOST}-${_target}
  make DESTDIR=${pkgdir} install-gdb

  # Remove unwanted files
  rm -rf ${pkgdir}${MINGW_PREFIX}/share/{gdb,man,info}

  rm -rf ${pkgdir}${MINGW_PREFIX}/include
  rm -rf ${pkgdir}${MINGW_PREFIX}/lib
}

```

**Comment by mingwandroid** [comment]
Please make a PR with your changes on github. That way you get the credit and a warm fuzzy feeling inside from having contributed to MSYS2 :-)

**Comment by GitMensch** [comment]
Should be closed as the related PR was merged.

Additional question @devjoa: is there a reason that you don't use gdb-multiarch?

@lazka Do you know of a reason to keep the arm-none-eabi-gdb packages? They definitely had their historic reasons but with the gdb-multiarch package I'm not sure this is the case any more (other than current setups/dependencies, but those could be fixed by a transitional package / PKGBUILD updates).

**Comment by devjoa** [comment]
> Additional question @devjoa: is there a reason that you don't use gdb-multiarch?
Sorry @GitMesnch. I wasn't aware that the [mingw-w64-x86_64-gdb-multiarch](https://packages.msys2.org/package/mingw-w64-x86_64-gdb-multiarch?repo=mingw64) package was available as a managed package for MSYS2. I found arm-none-eabi-gdb package first, and I didn't investigate further into this due to that I knowed that the gdb-multiarch package is only available as AUR in Arch Linux and I wanted things to be easy to manage for my colleagues when I tried to introduce CMake for my colleagues.
So I made an assumption that was wrong. ;-)

**Comment by sdbbs** [comment]
Just wanted to say, I've tried to install `pacman -S mingw-w64-x86_64-arm-none-eabi-gdb`; and I got:

```
$ pacman -Ss mingw-w64-x86_64-arm-none-eabi-gdb
mingw64/mingw-w64-x86_64-arm-none-eabi-gdb 9.2-4 (mingw-w64-x86_64-arm-none-eabi-toolchain) [installed]
    GNU Tools for ARM Embedded Processors - GDB (mingw-w64)
```

However, it segfaults immediately:

```
$ arm-none-eabi-gdb
Segmentation fault
```

Looking at it with "normal" gdb:

```
$ gdb --args arm-none-eabi-gdb
GNU gdb (GDB) 12.1
...
(No debugging symbols found in arm-none-eabi-gdb)
(gdb) r
Starting program: C:\msys64\mingw64\bin\arm-none-eabi-gdb.exe
[New Thread 24480.0x5b00]
[New Thread 24480.0x3590]
[New Thread 24480.0x538c]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffe8aa2094d in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
(gdb) bt
#0  0x00007ffe8aa2094d in ?? () from C:\msys64\mingw64\bin\libpython3.9.dll
#1  0x00007ff660ced9d8 in ?? ()
#2  0x00007ff660ddb8e9 in ?? ()
#3  0x00007ff660d93214 in ?? ()
#4  0x00007ff660c7cd81 in ?? ()
#5  0x00007ff660c7db2d in ?? ()
#6  0x00007ff660fcfeb7 in ?? ()
#7  0x00007ff660ad13b1 in ?? ()
#8  0x00007ff660ad14e6 in ?? ()
#9  0x00007ffe9b357034 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#10 0x00007ffe9bea2651 in ntdll!RtlUserThreadStart () from C:\WINDOWS\SYSTEM32\ntdll.dll
#11 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) quit
A debugging session is active.

        Inferior 1 [process 24480] will be killed.

Quit anyway? (y or n) y
```

... I can see it is libpython3.9.dll which is failing, which is why I suspect this problem is likely related to this issue.

>  is there a reason that you don't use gdb-multiarch?

Well, I tried to, but cannot quite get it to run correctly either - see https://stackoverflow.com/questions/72320763/gdb-multiarch-mingw64-cannot-determine-architecture-from-executable

**Comment by bananu7** [comment]
Same issue with `mingw64/mingw-w64-x86_64-arm-none-eabi-gdb 9.2-5`, this time segfaulting in python 3.10.

**Comment by GitMensch** [comment]
As noted in the referenced stackoverflow question `gdb-multiarch myexecutable.elf` should work (possibly with a warning during startup), `gdb-multiarch -iex "set osabi none" myexecutable.elf` should also fix the warning.

@devjoa  @mingwandroid: The question this leaves open: Shouldn't we get rid of the arm-none-eabi-gdb package, possibly by defining its package with two minimal shell scripts that start `gdb-multiarch -iex "set osabi none" %*` (arm-none-eabi-gdb.cmd, arm-none-eabi-gdb would use `$*`) and depend on gdb-multiarch?

**Comment by bananu7** [comment]
Yeah, I got the multiarch to work :)

**Comment by nvx** [comment]
Any update on this? Got bit by this today, sitching to gdb-multiarch worked fine.

Replacing the broken package with a small stub script or symlink would definitely reduce confusion.

**Comment by Skips75** [comment]
The `mingw64/mingw-w64-x86_64-arm-none-eabi-gdb` version 9.2-8 still reports segmentation fault, in `libpython3.11.dll`

**Comment by GitMensch** [comment]
... and multiarch still works, right?

I do think that this issue should be reopened until we have a proper fix, which is to remove the arm builds by a stub that depends on gdb-multiarch.
