### ISSUE TITLE
lldb doesn't work with Python

### ISSUE THREAD

**Issue by orgads** [msys2/MINGW-packages#7256]
```
$ winpty lldb test.exe
(lldb) target create "test.exe"
Current executable set to 'F:\Projects\test\debug\test.exe' (i686).
(lldb) script print('hello')
Python path configuration:
  PYTHONHOME = 'D:/a/_temp/msys/msys64/mingw32/bin'
  PYTHONPATH = (not set)
  program name = 'python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:/msys32/mingw32/bin/lldb.exe'
  sys.base_prefix = 'D:/a/_temp/msys/msys64/mingw32/bin'
  sys.base_exec_prefix = 'D:/a/_temp/msys/msys64/mingw32/bin'
  sys.executable = 'C:/msys32/mingw32/bin/lldb.exe'
  sys.prefix = 'D:/a/_temp/msys/msys64/mingw32/bin'
  sys.exec_prefix = 'D:/a/_temp/msys/msys64/mingw32/bin'
  sys.path = [
    'D:/a/_temp/msys/msys64/mingw32/bin/lib/python38.zip',
    'D:/a/_temp/msys/msys64/mingw32/bin/lib/python3.8',
    'D:/a/_temp/msys/msys64/mingw32/bin/lib/python3.8',
    'D:/a/_temp/msys/msys64/mingw32/bin/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00005150 (most recent call first):
<no Python frame>
```

Another attempt after manually setting `PYTHONPATH`:
```
$ export PYTHONPATH=C:/msys32/mingw32/lib/python3.8

$ winpty lldb test.exe
(lldb) target create "test.exe"
Current executable set to 'F:\Projects\test\debug\test.exe' (i686).
(lldb) script print('hello')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys32/mingw32/lib/python3.8/site-packages/lldb/__init__.py", line 95, in <module>
    import six
  File "C:/msys32/mingw32/lib/python3.8/site-packages/six.py", line 633, in <module>
    import struct
  File "C:/msys32/mingw32/lib/python3.8/struct.py", line 13, in <module>
    from _struct import *
ModuleNotFoundError: No module named '_struct'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'run_one_line' is not defined
Tr[0;c1;3e1mbaeck r(rmor:o st[e0mcenptyth ocn faalill lead satt)tem:pt
i ng t o eFvialluatee  '"p<rint('helslo')'
tring>", line 1, in <module>
NameError: name 'lldb' is not defined
(lldb) quit
```

**Comment by orgads** [comment]
Anybody? @Alexpux?

**Comment by Alexpux** [comment]
I'm with COVID in hospital so can't do or watch anything

**Comment by orgads** [comment]
Oh! So sad to hear that.

Get well soon!

**Comment by oltolm** [comment]
#7416 has been merged. This can be closed.
