### ISSUE TITLE
libxml2: Segmentation fault when parsing certain utf-8

### ISSUE THREAD

**Issue by Wormnest** [msys2/MINGW-packages#7955]
Under certain conditions I get a segmentation fault when calling libxml2 from python 3.

I have: `mingw64/mingw-w64-x86_64-libxml2 2.9.10-4 [installed]`

OS: Windows 10 Home, 64 bits

We discussed this on #gimp's irc channel and the segmentation fault only happens on Windows, not on Linux although they do see the '^' pointing at the wrong position.
Changing the word contrôlées to contrôxlées or controlées stops the crashing.

Although it looks like libxml2 is also doing something wrong, the crash seems specific to MINGW or at least Windows.

It is reproducible with the following test case for me:

```
#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

import os
import sys
import libxml2

def xml_error_handler(ctxt, error):
    print(f"--> xml_error_handler: {error}")
    pass

tmp   = '<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE sect2 PUBLIC "-//OASIS//DTD DocBook XML V4.3//EN" "http://www.docbook.org/xml/4.3/docbookx.dtd"><para>En outre, saturation et luminosités du calque <quote>Chrome</quote> sont modifiées (contrôlées par <guilabel>Chrome&nbsp;saturation</guilabel> et <guilabel>Chrome&nbsp;lightness</guilabel>).</para>'
tmp2  = '<?xml version="1.0" encoding="utf-8" ?>'
nl    = "\n"
tmp3  = '<!DOCTYPE sect2 PUBLIC "-//OASIS//DTD DocBook XML V4.3//EN" "http://www.docbook.org/xml/4.3/docbookx.dtd">'
tmp4  = '<para>En outre, saturation et luminosités du calque <quote>Chrome</quote> sont modifiées (contrôlées par <guilabel>Chrome&nbsp;saturation</guilabel> et <guilabel>Chrome&nbsp;lightness</guilabel>).</para>'
tmp4a = '<para>En outre, saturation et luminosités du calque <quote>Chrome</quote> sont modifiées (contrôlées par '
tmp4b = '<guilabel>Chrome&nbsp;saturation</guilabel> et '
tmp4c = '<guilabel>Chrome&nbsp;lightness</guilabel>).</para>'


tmp_total = tmp2 + nl + tmp3 + nl + tmp4a + nl + tmp4b + tmp4c
tmp_total4 = tmp2 + nl + tmp3 + nl + tmp4

libxml2.registerErrorHandler(xml_error_handler, None)

xml = tmp           # Segmentation fault
#xml = tmp_total4    # Segmentation fault
#xml = tmp_total     # parsing done

try:
    ctxt = libxml2.createDocParserCtxt(xml)
    ctxt.replaceEntities(0)
    ctxt.parseDocument()
    print("\n--> parsing done\n", file=sys.stderr)
except:
    print("\n--> Exception parsing translation as xml\n", file=sys.stderr)

```

Part of the irc discussion:

```
<Jehan> Wormnest: in any case, we don't get segfaults. libxml does its job and complains normally here. Maybe there is a bug in libxml on Windows. Or maybe indeed it's patched wrong by MSYS2. ??
<ankh> or it's a problem in the python loibrary
<ankh> i do see a problem going on though, which i consider a libxml bug
<ankh> the error message about nbsp undefined starts in the middle of a UTF8 character, so starts with garbage
<ankh> if in the definition of tmp you change contrôlées to contrôxlées does it still crash? (and in tmp4)
<ankh> or change ô to an o
<ankh> Wormnest, ^
<Wormnest> ankh: tmp with contrôxlées works
<Wormnest> controlées works too

<ankh> Wormnest, ok, so looks like the crash is becasue of the malformed utf-8 character in the error message, and looks to me that this is libxml bug, truncating a string in the middle of a character
<ankh> but the crash is probably mingw, yes
<ankh> so two separate bugs really
<ankh> libxml2 is doing something bad - although not a bug as such, it could for sure be improved - and this is triggering a crash in the Windows port, so the crash part is a mingw bug

```

**Comment by lazka** [comment]
```
#0  function_code_fastcall (co=<optimized out>, args=0x14b53077ce0, nargs=2,
    globals=globals@entry=0x14b52cba780) at ../Python-3.8.7/Objects/call.c:280
#1  0x00007ffe04a6e5f1 in _PyFunction_Vectorcall (
    func=func@entry=0x14b52ca5280, stack=<optimized out>,
    nargsf=nargsf@entry=2, kwnames=<optimized out>)
    at ../Python-3.8.7/Objects/call.c:410
#2  0x00007ffe04a6f779 in PyVectorcall_Call (callable=0x14b52ca5280,
    tuple=tuple@entry=0x14b53077cc0, kwargs=<optimized out>)
    at ../Python-3.8.7/Objects/call.c:199
#3  0x00007ffe04a6f90d in PyObject_Call (callable=0x14b52ca5280,
    args=args@entry=0x14b53077cc0, kwargs=0x0)
    at ../Python-3.8.7/Objects/call.c:227
#4  0x00007ffe04a6f9ac in PyEval_CallObjectWithKeywords (
    callable=<optimized out>, args=args@entry=0x14b53077cc0,
    kwargs=kwargs@entry=0x0) at ../Python-3.8.7/Objects/call.c:809
#5  0x00007ffe09f74ee0 in libxml_xmlErrorFuncHandler (ctx=<optimized out>,
    msg=<optimized out>) at ../../libxml2-2.9.10/python/libxml.c:1644
#6  0x00007ffe06945ded in xmlParserPrintFileContextInternal (
    input=input@entry=0x14b530d1110,
    channel=channel@entry=0x7ffe09f74e1f <libxml_xmlErrorFuncHandler>,
    data=data@entry=0x0) at ../libxml2-2.9.10/error.c:208
#7  0x00007ffe069463b3 in xmlReportError (err=err@entry=0x14b52c65198,
    ctxt=ctxt@entry=0x14b52c64f50,
    str=str@entry=0x14b52bd6400 "Entity 'nbsp' not defined\n",
    channel=0x7ffe09f74e1f <libxml_xmlErrorFuncHandler>, channel@entry=0x0,
    data=data@entry=0x0) at ../libxml2-2.9.10/error.c:406
#8  0x00007ffe069474bf in __xmlRaiseError (schannel=0x0,
    channel=0x7ffe069465bd <xmlParserError>, data=0x14b52c64f50,
    ctx=0x14b52c64f50, nod=0x0, domain=1, code=27, level=XML_ERR_ERROR,
    file=0x0, line=1, str1=0x14b52c52891 "nbsp", str2=0x0, str3=0x0, int1=0,
    col=320, msg=0x7ffe06a2ddfa "Entity '%s' not defined\n")
    at ../libxml2-2.9.10/error.c:633
#9  0x00007ffe0694b244 in xmlErrMsgStr (ctxt=0x17babfe398,
    ctxt@entry=0x14b52c64f50, error=error@entry=XML_WAR_UNDECLARED_ENTITY,
    msg=msg@entry=0x7ffe06a2ddfa "Entity '%s' not defined\n",
    val=val@entry=0x14b52c52891 "nbsp") at ../libxml2-2.9.10/parser.c:778
#10 0x00007ffe069533df in xmlParseEntityRef (ctxt=ctxt@entry=0x14b52c64f50)
    at ../libxml2-2.9.10/parser.c:7544
#11 0x00007ffe0695d4fc in xmlParseReference (ctxt=ctxt@entry=0x14b52c64f50)
    at ../libxml2-2.9.10/parser.c:7066
#12 0x00007ffe0695df09 in xmlParseContent (ctxt=ctxt@entry=0x14b52c64f50)
    at ../libxml2-2.9.10/parser.c:9871
#13 0x00007ffe0695e5d4 in xmlParseElement (ctxt=ctxt@entry=0x14b52c64f50)
    at ../libxml2-2.9.10/parser.c:9911
#14 0x00007ffe06961a80 in xmlParseDocument (ctxt=0x14b52c64f50)
    at ../libxml2-2.9.10/parser.c:10747
#15 0x00007ffe09f7c902 in libxml_xmlParseDocument (self=<optimized out>,
    args=<optimized out>) at ../../libxml2-2.9.10/python/libxml2-py.c:4958
#16 0x00007ffe04a6e0cd in cfunction_call_varargs (func=0x14b533836d0,
    args=0x14b52feedc0, kwargs=0x0) at ../Python-3.8.7/Objects/call.c:757
#17 0x00007ffe04a6fa2c in PyCFunction_Call (func=<optimized out>,
    args=<optimized out>, kwargs=<optimized out>)
    at ../Python-3.8.7/Objects/call.c:772
#18 0x00007ffe04a6e77e in _PyObject_MakeTpCall (
    callable=callable@entry=0x14b533836d0, args=<optimized out>, nargs=1,
    keywords=keywords@entry=0x0) at ../Python-3.8.7/Objects/call.c:159
#19 0x00007ffe04b2b98a in _PyObject_Vectorcall (kwnames=0x0,
    nargsf=<optimized out>, args=0x14b53307be8, callable=0x14b533836d0)
    at ../Python-3.8.7/Include/cpython/abstract.h:125
#20 call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>,
    tstate=0x14b510acc70) at ../Python-3.8.7/Python/ceval.c:4963
#21 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at ../Python-3.8.7/Python/ceval.c:3469
#22 0x00007ffe04b246bc in PyEval_EvalFrameEx (f=f@entry=0x14b53307a60,
    throwflag=throwflag@entry=0) at ../Python-3.8.7/Python/ceval.c:741
#23 0x00007ffe04a6dec8 in function_code_fastcall (co=<optimized out>,
    args=0x14b52e167b8, nargs=1, globals=globals@entry=0x14b5307d6c0)
    at ../Python-3.8.7/Objects/call.c:283
#24 0x00007ffe04a6e5f1 in _PyFunction_Vectorcall (func=<optimized out>,
    stack=<optimized out>, nargsf=<optimized out>, kwnames=<optimized out>)
    at ../Python-3.8.7/Objects/call.c:410
#25 0x00007ffe04b2ba29 in _PyObject_Vectorcall (kwnames=0x0,
    nargsf=<optimized out>, args=<optimized out>, callable=0x14b533afaf0)
    at ../Python-3.8.7/Include/cpython/abstract.h:127
#26 call_function (kwnames=0x0, oparg=<optimized out>,
    pp_stack=<synthetic pointer>, tstate=0x14b510acc70)
    at ../Python-3.8.7/Python/ceval.c:4963
#27 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>)
    at ../Python-3.8.7/Python/ceval.c:3486
#28 0x00007ffe04b246bc in PyEval_EvalFrameEx (f=f@entry=0x14b52e16640,
    throwflag=throwflag@entry=0) at ../Python-3.8.7/Python/ceval.c:741
#29 0x00007ffe04b24ea2 in _PyEval_EvalCodeWithName (_co=0x14b5306c5b0,
    globals=<optimized out>, locals=<optimized out>, args=<optimized out>,
    argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0,
    kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0,
    defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0,
    closure=closure@entry=0x0, name=name@entry=0x0,
    qualname=qualname@entry=0x0) at ../Python-3.8.7/Python/ceval.c:4298
#30 0x00007ffe04b25008 in PyEval_EvalCodeEx (_co=_co@entry=0x14b5306c5b0,
    globals=globals@entry=0x14b52cba780, locals=locals@entry=0x14b52cba780,
    args=args@entry=0x0, argcount=argcount@entry=0, kws=kws@entry=0x0,
    kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0,
    kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0)
    at ../Python-3.8.7/Python/ceval.c:4327
#31 0x00007ffe04b25062 in PyEval_EvalCode (co=co@entry=0x14b5306c5b0,
    globals=globals@entry=0x14b52cba780, locals=locals@entry=0x14b52cba780)
    at ../Python-3.8.7/Python/ceval.c:718
#32 0x00007ffe04b5deb2 in run_eval_code_obj (co=co@entry=0x14b5306c5b0,
    globals=globals@entry=0x14b52cba780, locals=locals@entry=0x14b52cba780)
    at ../Python-3.8.7/Python/pythonrun.c:1165
#33 0x00007ffe04b5df5b in run_mod (mod=mod@entry=0x14b52c56478,
    filename=filename@entry=0x14b52ea16b0,
    globals=globals@entry=0x14b52cba780, locals=locals@entry=0x14b52cba780,
    flags=flags@entry=0x17babff990, arena=arena@entry=0x14b52cb7a30)
    at ../Python-3.8.7/Python/pythonrun.c:1187
```

**Comment by lazka** [comment]
This is https://gitlab.gnome.org/GNOME/libxml2/-/issues/64
