### ISSUE TITLE
ucrt: python segfault importing opencv

### ISSUE THREAD

**Issue by LABPBS** [msys2/MINGW-packages#8534]
```
Python 3.8.9 (default, Apr 13 2021, 15:55:02)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
[New Thread 2172.0xab4]

Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000180001430 in unw_init_local () from F:\msys64\ucrt64\bin\libunwind.dll
(gdb) bt
#0  0x0000000180001430 in unw_init_local () from F:\msys64\ucrt64\bin\libunwind.dll
#1  0x000000018000340c in libunwind!_Unwind_Backtrace () from F:\msys64\ucrt64\bin\libunwind.dll
```
libunwind?

mingw64:
```
Python 3.8.9 (default, Apr 13 2021, 15:54:59)  [GCC 10.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
libunwind:      pc not in table, pc=0xFFFFFFFFFFFFFFFF
>>>
```

**Comment by Biswa96** [comment]
Please share the solution which fixes the issue.

**Comment by LABPBS** [comment]
Sorry about that

It was fixed with clang 12
