### ISSUE TITLE
mingw-w64-python-sphinx-4.0.1: requirements not fulfilled?

### ISSUE THREAD

**Issue by heljkon** [msys2/MINGW-packages#8685]
In PR https://github.com/msys2/MINGW-packages/pull/8677 I had to fix the packaging because directories weren't created by make install. This was because the documentation was not generated by sphinx as qemu's configure considered sphinx broken. To no documentation was generated and copied for install.

IMHO Sphinx seems to be broken indeed, because important requirements don't match anymore according to 
/mingw64/lib/python3.8/site-packages/Sphinx-4.0.1-py3.8.egg-info/requires.txt
Jinja2<3.0,>=2.3
MarkupSafe<2.0

These were recently updated to 
2.0.0 (mingw-w64-python-markupsafe)
3.0.0 (mingw-w64-python-jinja)

Do I understand that right? Do you see any solution to this? I already tried to fool qemu's configure, but I won't change platform files (/mingw64/lib/python3.8/site-packages/Sphinx-4.0.1-py3.8.egg-info/requires.txt) while building. 

This is the failure I received:
```
[746/1335] Generating QEMU manual with a custom command
FAILED: docs/docs.stamp
"env" "CONFDIR=C:/msys64/mingw64/etc/" "C:/msys64/mingw64/bin/sphinx-build.EXE" "-Dversion=6.0.0" "-Drelease=" "-Ddepfile=docs/docs.d" "-Ddepfile_stamp=docs/docs.stamp" "-b" "html" "-d" "C:/Qemu/tools/hyperv/src/msys2/pkg/mingw-w64-qemu-6.0.0/src/build-x86_64/docs/manual.p" "C:/Qemu/tools/hyperv/src/msys2/pkg/mingw-w64-qemu-6.0.0/src/qemu-6.0.0/docs" "C:/Qemu/tools/hyperv/src/msys2/pkg/mingw-w64-qemu-6.0.0/src/build-x86_64/docs/manual"
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (MarkupSafe 2.0.0 (c:/msys64/mingw64/lib/python3.8/site-packages), Requirement.parse('MarkupSafe<2.0'), {'Sphinx'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\mingw64\bin\sphinx-build-script.py", line 33, in <module>
    sys.exit(load_entry_point('Sphinx==4.0.1', 'console_scripts', 'sphinx-build')())
  File "C:\msys64\mingw64\bin\sphinx-build-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:/msys64/mingw64/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:/msys64/mingw64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sphinx/application.py", line 41, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "C:/msys64/mingw64/lib/python3.8/site-packages/sphinx/registry.py", line 24, in <module>
    from pkg_resources import iter_entry_points
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:/msys64/mingw64/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'MarkupSafe<2.0' distribution was not found and is required by Sphinx
ninja: build stopped: subcommand failed.
make: *** [Makefile:152: run-ninja] Error 1

```

**Comment by naveen521kk** [comment]
it's problematic. the best thing would be to revert back to 3.*

**Comment by heljkon** [comment]
Did you mean reverting markupsafe and jinja - because reverting sphinx wouldn't help, in my opinion.
Anyway, someone with more knowledge and longer experience with this project will need to decide..

**Comment by naveen521kk** [comment]
sphinx 3.* doesn't depend on markup safe

maybe we should revert jinja or patch sphinx to remove version requirement.

**Comment by heljkon** [comment]
Well, as I understand it, you updated to sphinx 4.
If it comes to test modifying the requirement via patch, then lets try this with sphinx 4.
I will go on to fool qemu if necessary and test via my failing build.

How about this?

**Comment by naveen521kk** [comment]
Ok, I will instead make it work those version rather than reverting.

**Comment by heljkon** [comment]
OK, If you are using the CI, then I guess I will be able to download the resulting sphinx packages and use these for my tests.

**Comment by naveen521kk** [comment]
I would applying this commit https://github.com/sphinx-doc/sphinx/commit/85f58874ecd9feb391e24f9d0197bef5cc637a87#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7 and it should fix things

**Comment by heljkon** [comment]
So you will build the package via CI, because I can't apply this to the binaries, right?
I tried to find the files:

```
$ find lib/ -name rst.py
lib/python3.8/site-packages/sphinx/domains/rst.py
lib/python3.8/site-packages/sphinx/util/rst.py
$ find lib/ -name jinja2glue.py
lib/python3.8/site-packages/sphinx/jinja2glue.py
$ find lib/ -name setup.py
lib/python3.8/site-packages/pkg_resources/tests/data/my-test-package-source/setup.py
lib/python3.8/test/libregrtest/setup.py
$ find lib/ -name setup.py -exec grep Jinja2 {} \;
$
```

**Comment by naveen521kk** [comment]
Well, you should wait for the package to be built on #8686 and download the artefact and install that.  You can't directly apply that patch after you install that package.

If you need sphinx locally, maybe use pip?

**Comment by heljkon** [comment]
I'll just wait, that's easy...

**Comment by naveen521kk** [comment]
@heljkon can you download https://github.com/msys2/MINGW-packages/suites/2748593112/artifacts/60776427 and install it and check if it works?

**Comment by heljkon** [comment]
I will do so

**Comment by heljkon** [comment]
Just one thing I thought about. Seems you didn't increment the pkgrel. It is still 1. I guess 4.0.1 already was put to the repos, Will this work?

**Comment by naveen521kk** [comment]
oh forgot.
