### ISSUE TITLE
shiboken2-qt5: Shiboken is broken (import error) :-(

### ISSUE THREAD

**Issue by podsvirov** [msys2/MINGW-packages#9294]
Package info:
```bash
$ pacboy -Qi shiboken2-qt5:i
Name            : mingw-w64-i686-shiboken2-qt5
Version         : 5.15.2-4
Description     : CPython bindings generator for C++ libraries (mingw-w64)
Architecture    : any
URL             : https://doc.qt.io/qtforpython-5/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : mingw-w64-i686-clang  mingw-w64-i686-python
                  mingw-w64-i686-qt5
Optional Deps   : None
Required By     : mingw-w64-i686-pyside2-qt5
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3.10 MiB
Packager        : CI (msys2-autobuild/235648ed/1027423538)
Build Date      : Tue Jul 13 23:44:57 2021
Install Date    : Thu Jul 22 03:09:27 2021
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

Reproduce:
```bash
$ python
Python 3.9.6 (default, Jul 12 2021, 05:46:43)  [GCC 10.3.0 32 bit] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import shiboken2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:/msys32/mingw32/lib/python3.9/site-packages/shiboken2/__init__.py", line 27, in <module>
    from .shiboken2 import *
ModuleNotFoundError: No module named 'shiboken2.shiboken2'
>>>
```

Cc: @Alexpux @lazka @Biswa96 @raccoonmonk @jeremyd2019

**Comment by podsvirov** [comment]
Similar unresolved [discussion](https://github.com/Nuitka/Nuitka/issues/844).
