### ISSUE TITLE
mingw-w64-x86_64-gdb cannot source python module

### ISSUE THREAD

**Issue by 3N4N** [msys2/MINGW-packages#9735]
In Windows 10 system, I have the following in my `~/.gdbinit` (`C:\User\ACER\.gdbinit`):

```gdb
source ~/.gef.py
```
Where [`~/.gef.py`](https://gef.readthedocs.io/en/master/) is a set of commands written in python.

In MSYS2 shell, gdb can source it no problem. But in MINGW64 shell, from both mintty and Windows Terminal, it gives the following error.

```bash
ACER@DESKTOP-5F09VFS MINGW64 ~
$ gdb --silent
Traceback (most recent call last):
  File "c:/msys64\mingw64\share\gdb/python/gdb/__init__.py", line 130, in _execute_file
    exec(compiled, globals, globals)
  File "C:\Users\ACER/.gef.py", line 10657, in <module>
    pythonbin = which("python3")
  File "C:\Users\ACER/.gef.py", line 1104, in which
    raise FileNotFoundError("Missing file `{:s}`".format(program))
FileNotFoundError: Missing file `python3`
(gdb) shell which python3
/mingw64/bin/python3
(gdb)
```

The errmsg says it can't find python3 executable. But as the `which` command shows, there is python3 installed in MINGW64 shell. So what's happening here? My guess is the filepath, `C:\Users\ACER/.gef.py`, is causing the problem. But that should cause problems in MSYS2 shell, too, which it doesn't.

**Comment by 3N4N** [comment]
Sorry. Copied the wrong name there.

```bash
ACER@DESKTOP-5F09VFS:~$ pacman -Ss mingw-w64-ucrt-x86_64-gdb
ucrt64/mingw-w64-ucrt-x86_64-gdb 10.2-2 (mingw-w64-ucrt-x86_64-toolchain)
    GNU Debugger (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-gdb-multiarch 10.2-2 (mingw-w64-ucrt-x86_64-toolchain)
    GNU Debugger (supports all targets)
ucrt64/mingw-w64-ucrt-x86_64-gdbm 1.19-1
    GNU database library (mingw-w64)
ACER@DESKTOP-5F09VFS:~$ pacman -Ss mingw-w64-x86_64-gdb
mingw64/mingw-w64-x86_64-gdb 10.2-2 (mingw-w64-x86_64-toolchain) [installed]
    GNU Debugger (mingw-w64)
mingw64/mingw-w64-x86_64-gdb-multiarch 10.2-2 (mingw-w64-x86_64-toolchain) [installed]
    GNU Debugger (supports all targets)
mingw64/mingw-w64-x86_64-gdbm 1.19-1
    GNU database library (mingw-w64)
```

**Comment by GitMensch** [comment]
What about `(gdb) py print (sys.version)`?

**Comment by 3N4N** [comment]
@GitMensch, no difference.

```bash
$ gdb
Traceback (most recent call last):
  File "c:/msys64\mingw64\share\gdb/python/gdb/__init__.py", line 130, in _execute_file
    exec(compiled, globals, globals)
  File "C:\Users\ACER/.gef.py", line 10657, in <module>
    pythonbin = which("python3")
  File "C:\Users\ACER/.gef.py", line 1104, in which
    raise FileNotFoundError("Missing file `{:s}`".format(program))
FileNotFoundError: Missing file `python3`
(gdb) source ~/.gef.py
Traceback (most recent call last):
  File "c:/msys64\mingw64\share\gdb/python/gdb/__init__.py", line 130, in _execute_file
    exec(compiled, globals, globals)
  File "C:\Users\ACER/.gef.py", line 10657, in <module>
    pythonbin = which("python3")
  File "C:\Users\ACER/.gef.py", line 1104, in which
    raise FileNotFoundError("Missing file `{:s}`".format(program))
FileNotFoundError: Missing file `python3`
```
