### ISSUE TITLE
pywin32 ImportError for win32files on Windows7

### ISSUE THREAD

**Issue by wb8tyw** [msys2/MINGW-packages#9751]
I am trying to port the d-rats applications from python2 to python3, etc.

My test system is frozen at Windows 7 since Windows 10 is not supported by the hardware vendor.

I thought that msys2 mingw-64 would make the easiest deployment for end users for the python packages that are available, but have hit an issue with the mingw-w64-x86_64-python-pywin32 package.

`$ python d_rats/dplatform.py
dPlatform  : Config dir: C:/Users/malmberg/AppData/Roaming/D-RATS-EV
dPlatform  : Default dir: C:/Users/malmberg/Desktop
dPlatform  : Log file (foo): C:/Users/malmberg/AppData/Roaming/D-RATS-EV/logs/foo.txt
Traceback (most recent call last):
  File "\\aviary\home\work\d-rats\D-Rats\d_rats\dplatform.py", line 787, in <module>
    do_test()
  File "\\aviary\home\work\d-rats\D-Rats\d_rats\dplatform.py", line 777, in do_test
    printlog("dPlatform", " : Serial ports: %s" % __pform.list_serial_ports())
  File "\\aviary\home\work\d-rats\D-Rats\d_rats\dplatform.py", line 617, in list_serial_ports
    import win32file # type: ignore
ImportError: DLL load failed while importing win32file: The specified module could not be found.
`
Any help would be appreciated.

**Comment by lazka** [comment]
See #9752

**Comment by raedrizqie** [comment]
ah ok..

I built my pywin32 locally with `-static-libgcc -static-libstdc++ -static -lwinpthread`

I didn't put pywintypesXX.dll and pythoncomXX.dll in System32 folder. I never had import error like the one reported here.

**Comment by MehdiChinoune** [comment]
running ntldd suggests that it is still linked to some external dll libraries:
```
Check runtime dependencies for mingw-w64-clang-x86_64-python-pywin32
  /clang64/lib/python3.9/site-packages/win32/_win32sysloader.pyd runtime dependencies:
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000288232c0000)
  /clang64/lib/python3.9/site-packages/win32/_winxptheme.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001a398ff0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001a398c90000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001a398dd0000)
  /clang64/lib/python3.9/site-packages/win32/mmapfile.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000022eecd90000)
  /clang64/lib/python3.9/site-packages/win32/odbc.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002b27c970000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002b27c970000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002b27cab0000)
  /clang64/lib/python3.9/site-packages/win32/perfmon.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000200c7750000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000200c7750000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000200c7630000)
  /clang64/lib/python3.9/site-packages/win32/servicemanager.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001ef5c9f0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001ef5c740000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001ef5c5c0000)
  /clang64/lib/python3.9/site-packages/win32/timer.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001b0f9220000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001b0f8f40000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001b0f8e20000)
  /clang64/lib/python3.9/site-packages/win32/win32api.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002982bba0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002982b8c0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002982b7a0000)
  /clang64/lib/python3.9/site-packages/win32/win32clipboard.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000189b34c0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000189b30f0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000189b3230000)
  /clang64/lib/python3.9/site-packages/win32/win32console.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000016b1fc60000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000016b1fc60000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000016b1fda0000)
  /clang64/lib/python3.9/site-packages/win32/win32cred.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000021f4e0f0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000021f4e0f0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000021f4e230000)
  /clang64/lib/python3.9/site-packages/win32/win32crypt.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000026632[3500](https://github.com/MehdiChinoune/MINGW-packages/runs/5486305517?check_suite_focus=true#step:7:3500)00)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000026632350000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000026632200000)
  /clang64/lib/python3.9/site-packages/win32/win32event.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000020b390d0000)
  /clang64/lib/python3.9/site-packages/win32/win32evtlog.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001fa7c540000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001fa7c540000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001fa7c340000)
  /clang64/lib/python3.9/site-packages/win32/win32file.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000138dc2c0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000138dc2c0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000138dc0a0000)
  /clang64/lib/python3.9/site-packages/win32/win32gui.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001c6c1670000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001c6c1350000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001c6c1120000)
  /clang64/lib/python3.9/site-packages/win32/win32help.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000023cb8760000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000023cb8760000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000023cb85a0000)
  /clang64/lib/python3.9/site-packages/win32/win32inet.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000297c9da0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000297c9da0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000297c9c60000)
  /clang64/lib/python3.9/site-packages/win32/win32job.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000214874e0000)
  /clang64/lib/python3.9/site-packages/win32/win32lz.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001cf8c900000)
  /clang64/lib/python3.9/site-packages/win32/win32net.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001d98e110000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001d98e110000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001d98e000000)
  /clang64/lib/python3.9/site-packages/win32/win32pdh.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002e42b270000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002e42b270000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002e42b3b0000)
  /clang64/lib/python3.9/site-packages/win32/win32pipe.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000165c70d0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000165c70d0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000165c7210000)
  /clang64/lib/python3.9/site-packages/win32/win32print.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000265eaa20000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000265eaa20000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000265ea910000)
  /clang64/lib/python3.9/site-packages/win32/win32process.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000028c8f4d0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000028c8f4d0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000028c8f330000)
  /clang64/lib/python3.9/site-packages/win32/win32profile.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001a8d02f0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001a8d02f0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001a8d01d0000)
  /clang64/lib/python3.9/site-packages/win32/win32ras.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000020796340000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000020796340000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000207961f0000)
  /clang64/lib/python3.9/site-packages/win32/win32security.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000294927f0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000029492460000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000029492330000)
  /clang64/lib/python3.9/site-packages/win32/win32service.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000018ad1aa0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000018ad1aa0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000018ad1930000)
  /clang64/lib/python3.9/site-packages/win32/win32trace.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000027a361c0000)
  /clang64/lib/python3.9/site-packages/win32/win32transaction.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000241015f0000)
  /clang64/lib/python3.9/site-packages/win32/win32ts.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000023c697e0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000023c697e0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000023c69920000)
  /clang64/lib/python3.9/site-packages/win32/win32wnet.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000028fa4[3600](https://github.com/MehdiChinoune/MINGW-packages/runs/5486305517?check_suite_focus=true#step:7:3600)00)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000028fa4360000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000028fa4240000)
  /clang64/lib/python3.9/site-packages/win32/winxpgui.pyd runtime dependencies:
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000202f2f90000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000202f2c70000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x00000202f2db0000)
  /clang64/lib/python3.9/site-packages/win32comext/adsi/adsi.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001388b7a0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001388b7a0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001388b670000)
  /clang64/lib/python3.9/site-packages/win32comext/authorization/authorization.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002026d5e0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002026d5e0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002026d720000)
  /clang64/lib/python3.9/site-packages/win32comext/axcontrol/axcontrol.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001c4d5610000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001c4d5610000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001c4d54c0000)
  /clang64/lib/python3.9/site-packages/win32comext/axdebug/axdebug.pyd runtime dependencies:
  	axscript.pyd => not found
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000015366fe0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000015366fe0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000015367120000)
  /clang64/lib/python3.9/site-packages/win32comext/axscript/axscript.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000022c0c840000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000022c0c840000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000022c0c610000)
  /clang64/lib/python3.9/site-packages/win32comext/bits/bits.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x00000183369d0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x00000183369d0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000018336b10000)
  /clang64/lib/python3.9/site-packages/win32comext/directsound/directsound.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002023e100000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002023de50000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002023dcd0000)
  /clang64/lib/python3.9/site-packages/win32comext/ifilter/ifilter.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001db80270000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001db80000000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001db80140000)
  /clang64/lib/python3.9/site-packages/win32comext/internet/internet.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000027b0ec90000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000027b0ec90000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000027b0edd0000)
  /clang64/lib/python3.9/site-packages/win32comext/mapi/mapi.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001bc85260000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001bc84ed0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001bc84d60000)
  /clang64/lib/python3.9/site-packages/win32comext/propsys/propsys.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x0000025fbf650000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x0000025fbf650000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x0000025fbf4b0000)
  /clang64/lib/python3.9/site-packages/win32comext/shell/shell.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000001fdb99d0000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000001fdb99d0000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000001fdb9760000)
  /clang64/lib/python3.9/site-packages/win32comext/taskscheduler/taskscheduler.pyd runtime dependencies:
  	pythoncom39.dll => not found
  	pywintypes39.dll => not found
  	libpython3.9.dll => C:\msys64\clang64\bin\libpython3.9.dll (0x000002ac57370000)
  	libc++.dll => C:\msys64\clang64\bin\libc++.dll (0x000002ac57100000)
  	libunwind.dll => C:\msys64\clang64\bin\libunwind.dll (0x000002ac57240000)
```

**Comment by raedrizqie** [comment]
i think, the only way to fix pywin32 missing dll is to put pythoncom and pywintypes dll in %SYSTEM32% folder (like upstream does)

**Comment by ZachBacon** [comment]
Absolutely not. Never put anything in system32. Just adjust your system
path to point to those dll's if you must, but do not put dll's into
system32 folder.

**Comment by MehdiChinoune** [comment]
Those libraries are not built with mingw, They are not part of any package.
If they could be built on mingw then we could just solve the problem by installing them in `${MINGW_PREFIX}/bin`

**Comment by ZachBacon** [comment]
In practice, it's still a bad idea. Even if you have to put them in a
separate folder, add that to the path, it's still better than to put it in
system32.

**Comment by MehdiChinoune** [comment]
> In practice, it's still a bad idea. Even if you have to put them in a separate folder, add that to the path, it's still better than to put it in system32.

Did I say something about putting them in system32?!

**Comment by ZachBacon** [comment]
You didn't, but I'm still reiterating for those contemplating it.

**Comment by lazka** [comment]
We currently patch this here: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-pywin32/010-workaround-broken-add-dll-dir.patch

Because our Python doesn't support `add_dll_directory()` yet, see https://github.com/msys2-contrib/cpython-mingw/issues/48

**Comment by MehdiChinoune** [comment]
Sorry, I found them under `${MINGW_PREFIX}/lib/python3.9/site-packages/pywin32_system32`.
I think somehow I executed the wrong command to search for them.
```
$ pacman -Fx pythoncom39\.dll
mingw64/mingw-w64-x86_64-python-pywin32 302-5
    mingw64/lib/python3.9/site-packages/pywin32_system32/pythoncom39.dll
ucrt64/mingw-w64-ucrt-x86_64-python-pywin32 302-5 [installed]
    ucrt64/lib/python3.9/site-packages/pywin32_system32/pythoncom39.dll
clang64/mingw-w64-clang-x86_64-python-pywin32 302-5 [installed]
    clang64/lib/python3.9/site-packages/pywin32_system32/pythoncom39.dll
$ pacman -Fx pywintypes39\.dll
mingw64/mingw-w64-x86_64-python-pywin32 302-5
    mingw64/lib/python3.9/site-packages/pywin32_system32/pywintypes39.dll
ucrt64/mingw-w64-ucrt-x86_64-python-pywin32 302-5 [installed]
    ucrt64/lib/python3.9/site-packages/pywin32_system32/pywintypes39.dll
clang64/mingw-w64-clang-x86_64-python-pywin32 302-5 [installed]
    clang64/lib/python3.9/site-packages/pywin32_system32/pywintypes39.dll
```
